DEFINE
	MEASURE '_Key Measures'[Contract Gross Profit] = [Total Contract Billings] - [Total Contract Costs]
	MEASURE '_Key Measures'[Contract Gross Profit %] = DIVIDE(
			[Contract Gross Profit],
			[Total Contract Billings]
		)
	MEASURE '_Key Measures'[Total Contract Billings] = SUM('CONTRACT_BILLABLE_F'[BILLABLE_ALL])
	MEASURE '_Key Measures'[Total Contract Costs] = SUM('CALLS_F'[Cost All])
	MEASURE '_Key Measures'[Job Monthly Cost] = SUM(JOB_MONTHLY_SUMMARY_F[Monthly Cost])
	MEASURE '_Key Measures'[Job Monthly Revenue] = SUM(JOB_MONTHLY_SUMMARY_F[Contract Earned Curr Mo])
	MEASURE '_Key Measures'[Job Monthly GP] = [Job Monthly Revenue] - [Job Monthly Cost]
	MEASURE '_Key Measures'[Job Actual GP%] = DIVIDE(
			[Job Monthly GP],
			[Job Monthly Revenue]
		)
	MEASURE '_Key Measures'[Project Revenue] = SUM(PROJECT_REVENUE_F[Amount])
	MEASURE '_Key Measures'[Project Revenue] =
		SUM(PROJECT_REVENUE_F[Amount])

	MEASURE '_Key Measures'[Project Cost] =
		SUM(PROJECT_COSTS_F[Amount])

	MEASURE '_Key Measures'[Project GP] =
		[Project Revenue] - [Project Cost]

	MEASURE '_Key Measures'[Project GP %] =
		DIVIDE(
			[Project GP],
			[Project Revenue]
		)

	MEASURE '_Key Measures'[Total GP %] =
		DIVIDE(
			SUMX(
				VALUES(PROJECTS_D[SurrogateProjectID]),
				[Project GP]
			),
			SUMX(
				VALUES(PROJECTS_D[SurrogateProjectID]),
				[Project Revenue]
			)
		)

	MEASURE '_Key Measures'[Project GP % (Formatted)] =
		FORMAT(
			[Project GP %],
			"0.0%"
		)


EVALUATE
	SUMMARIZECOLUMNS(
		"Contract Gross Profit", [Contract Gross Profit],
		"Contract Gross Profit %", [Contract Gross Profit %],
		"Total Contract Billings", [Total Contract Billings],
		"Total Contract Costs", [Total Contract Costs],
		"Job Monthly Cost", [Job Monthly Cost],
		"Job Monthly Revenue", [Job Monthly Revenue],
		"Job Monthly GP", [Job Monthly GP],
		"Job Actual GP%", [Job Actual GP%],
		"Project Revenue", [Project Revenue]
	)