table DIVISIONS_D
	lineageTag: 24ca026e-11eb-4dd2-a29c-a1eb19cd7d4a

	column DivisionCode
		dataType: string
		lineageTag: 1724eff6-a4db-4a50-bc50-7e0bee303697
		summarizeBy: none
		sourceColumn: DivisionCode

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: b56fdaa3-895d-46d9-95c1-13be6192c923
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4049a164-7e99-4331-b4d4-f27a75fcc548
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: ef29d508-5aa2-498b-a4bf-adde34c20cdc
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	partition DIVISIONS_D = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Source = AzureStorage.Blobs("https://stgreen.blob.core.windows.net"),
				    #"Navigation 1" = Source{[Name = "datasets"]}[Data],
				    #"https://stgreen blob core windows net/datasets/_DIVISIONS_D csv" = #"Navigation 1"{[#"Folder Path"="https://stgreen.blob.core.windows.net/datasets/",Name="DIVISIONS_D.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"https://stgreen blob core windows net/datasets/_DIVISIONS_D csv",[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Imported CSV",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"DivisionCode", type text}, {"Division", type text}, {"Region", type text}, {"Company", type text}})
				    in #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

