table Projects_ProjectMonth_Amend_F
	lineageTag: 49fbb8e1-f707-4611-adf3-a2494b6a79fe

	column 'Month End'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 045dbdae-62b6-4782-8747-cdbdcf9cdc5d
		summarizeBy: none
		sourceColumn: Month End

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Key'
		dataType: string
		lineageTag: 1cccf740-906e-4e42-affa-6a6b62d0f84a
		sourceColumn: Customer Key

	column SurrogateProjectID
		dataType: string
		lineageTag: 3c558f95-a536-4411-a5a5-c1e4b21e4d2c
		sourceColumn: SurrogateProjectID

	column 'Project Subsegment'
		dataType: string
		lineageTag: 898e9781-389c-4019-943e-fadc4389c348
		sourceColumn: Project Subsegment

	column Stream
		dataType: string
		lineageTag: 1d166b37-6026-44cb-8eaa-2e6e08be75ca
		sourceColumn: Stream

	column Methodology
		dataType: string
		lineageTag: e43e1bbd-d7d9-48d7-ac27-be2e6650cbfc
		sourceColumn: Methodology

	column 'Revenue Amount'
		dataType: double
		lineageTag: 7e634cd9-e96e-4da2-a464-36b6cca4d495
		summarizeBy: sum
		sourceColumn: Revenue Amount

	column 'Cost Amount'
		dataType: double
		lineageTag: 87e3ad8f-50f2-4896-949c-3cfeb93ec068
		summarizeBy: sum
		sourceColumn: Cost Amount

	column ActualCost_Mo
		dataType: double
		lineageTag: 0b2a634e-6eb3-458b-85ed-76095bf1a6be
		sourceColumn: ActualCost_Mo

	column ForecastCost_Mo
		dataType: double
		lineageTag: b37e0509-ab05-4cb5-afd0-a4554977ee64
		sourceColumn: ForecastCost_Mo

	column 'Orig Contract Amount'
		dataType: double
		lineageTag: 71f8be07-5080-4273-a567-bb7c25d9818f
		sourceColumn: Orig Contract Amount

	partition Projects_ProjectMonth_Amend_F = m
		mode: import
		source =
				let
				    // ----------------------------
				    // Job Cost (Amend inputs at Job × Month)
				    // ----------------------------
				    StartDate = #date(2020, 1, 1),
				
				    // Map Job Cost projects (Project Number = Job Number)
				    JobDim = Table.SelectRows(PROJECTS_D, each [Project Type] = "Job Cost"),
				    JobDimKeysRaw = Table.SelectColumns(JobDim,{"Project Number","Customer Number","Customer Key","SurrogateProjectID"}),
				    JobDimKeys = Table.TransformColumns(
				        JobDimKeysRaw,
				        {
				            {"Project Number", each if _ = null then null else Text.Upper(Text.Trim(Text.From(_))), type text},
				            {"Customer Number", each if _ = null then null else Text.Upper(Text.Trim(Text.From(_))), type text}
				        }
				    ),
				
				    // Build JobKey -> Job Number + Customer Number bridge from JOB_MONTHLY_SUMMARY_F
				    JobMapBase = Table.SelectRows(JOB_MONTHLY_SUMMARY_F, each [Period Date] >= StartDate),
				    JobMapBaseSlim = Table.SelectColumns(JobMapBase,{"Job Key","Job Number","Customer Number","Orig Contract Amount"}),
				    JobMapBaseClean = Table.TransformColumns(
				        JobMapBaseSlim,
				        {
				            {"Job Number", each if _ = null then null else Text.Upper(Text.Trim(Text.From(_))), type text},
				            {"Customer Number", each if _ = null then null else Text.Upper(Text.Trim(Text.From(_))), type text}
				        }
				    ),
				    JobMapGrouped =
				        Table.Group(
				            JobMapBaseClean,
				            {"Job Key"},
				            {
				                {"Job Number", each List.Max([Job Number]), type text},
				                {"Customer Number", each List.Max([Customer Number]), type text},
				                {"Orig Contract Amount", each List.Max([Orig Contract Amount]), type number}
				            }
				        ),
				
				    ActualSrc = Table.SelectRows(JOB_COST_DETAILS, each Date.From([TRAN_DATE]) >= StartDate),
				    ActualWithMonthEnd =
				        Table.AddColumn(
				            Table.SelectColumns(ActualSrc,{"JOB_KEY","TRAN_DATE","COST_AMT"}),
				            "Month End",
				            each Date.EndOfMonth(Date.From([TRAN_DATE])),
				            type date
				        ),
				    ActualGrouped = Table.Group(ActualWithMonthEnd,{"JOB_KEY","Month End"},{{"ActualCost_Mo", each List.Sum([COST_AMT]), type number}}),
				
				    FcstSrc = Table.SelectRows(JOB_COST_FORECASTS_F, each Date.From([Date]) >= StartDate),
				    FcstWithMonthEnd =
				        Table.AddColumn(
				            Table.SelectColumns(FcstSrc,{"JOB_KEY","Date","FORECAST_COSTS"}),
				            "Month End",
				            each Date.EndOfMonth(Date.From([Date])),
				            type date
				        ),
				    FcstGrouped = Table.Group(FcstWithMonthEnd,{"JOB_KEY","Month End"},{{"ForecastCost_Mo", each List.Sum([FORECAST_COSTS]), type number}}),
				
				    // Align Actual/Forecast by Job+Month
				    ActualLabeled = Table.RenameColumns(Table.AddColumn(ActualGrouped, "Kind", each "ActualCost_Mo", type text), {{"ActualCost_Mo", "Amount"}}),
				    FcstLabeled = Table.RenameColumns(Table.AddColumn(FcstGrouped, "Kind", each "ForecastCost_Mo", type text), {{"ForecastCost_Mo", "Amount"}}),
				    CostsCombined = Table.Combine({ActualLabeled, FcstLabeled}),
				    CostsGrouped = Table.Group(CostsCombined, {"JOB_KEY","Month End","Kind"}, {{"Amount", each List.Sum([Amount]), type number}}),
				    CostsPivoted = Table.Pivot(CostsGrouped, List.Distinct(CostsGrouped[Kind]), "Kind", "Amount", List.Sum),
				    EnsureActual = if List.Contains(Table.ColumnNames(CostsPivoted), "ActualCost_Mo") then CostsPivoted else Table.AddColumn(CostsPivoted, "ActualCost_Mo", each 0, type number),
				    EnsureForecast = if List.Contains(Table.ColumnNames(EnsureActual), "ForecastCost_Mo") then EnsureActual else Table.AddColumn(EnsureActual, "ForecastCost_Mo", each 0, type number),
				
				    // Join to JobMap to get Job Number + Customer Number + Orig Contract
				    WithJobMap = Table.NestedJoin(EnsureForecast, {"JOB_KEY"}, JobMapGrouped, {"Job Key"}, "JM", JoinKind.LeftOuter),
				    ExpandedJobMap = Table.ExpandTableColumn(WithJobMap, "JM", {"Job Number","Customer Number","Orig Contract Amount"}, {"Job Number","Customer Number","Orig Contract Amount"}),
				
				    // Join to PROJECTS_D using Project Number + Customer Number
				    WithDim = Table.NestedJoin(ExpandedJobMap, {"Job Number","Customer Number"}, JobDimKeys, {"Project Number","Customer Number"}, "D", JoinKind.LeftOuter),
				    ExpandedDim = Table.ExpandTableColumn(WithDim, "D", {"Customer Key","SurrogateProjectID"}, {"Customer Key","SurrogateProjectID"}),
				
				    JobsBase =
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Table.AddColumn(ExpandedDim, "Project Subsegment", each "Job Cost", type text),
				                    "Stream", each "Projects", type text
				                ),
				                "Methodology", each "Amend", type text
				            ),
				            "Revenue Amount", each null, type number
				        ),
				    JobsWithCost = Table.AddColumn(JobsBase, "Cost Amount", each [ActualCost_Mo], type number),
				    JobsSelect =
				        Table.SelectColumns(
				            JobsWithCost,
				            {"Month End","Customer Key","SurrogateProjectID","Project Subsegment","Stream","Methodology","Revenue Amount","Cost Amount","ActualCost_Mo","ForecastCost_Mo","Orig Contract Amount"}
				        ),
				
				    // ----------------------------
				    // Service Project billings (same for both methodologies)
				    // ----------------------------
				    ServiceProjects = Table.SelectRows(PROJECTS_D, each [Project Type] = "Service Project"),
				    ServiceKeys = Table.Distinct(Table.SelectColumns(ServiceProjects,{"Project Number","SurrogateProjectID"}),{"Project Number"}),
				    Billing = Table.SelectRows(CONTRACT_BILLABLE_F, each [WENNSOFT_BILLING_DATE] >= StartDate),
				    Joined = Table.NestedJoin(Billing, {"CONTRACT_NUMBER"}, ServiceKeys, {"Project Number"}, "P", JoinKind.Inner),
				    ExpandedSP = Table.ExpandTableColumn(Joined, "P", {"SurrogateProjectID"}, {"SurrogateProjectID"}),
				    WithMonthEndSP = Table.AddColumn(ExpandedSP, "Month End", each Date.EndOfMonth([WENNSOFT_BILLING_DATE]), type date),
				    ServiceSlim = Table.SelectColumns(WithMonthEndSP,{"Month End","Customer Key","SurrogateProjectID","BILLABLE_ALL"}),
				    ServiceGrouped = Table.Group(ServiceSlim,{"Customer Key","SurrogateProjectID","Month End"},{{"Revenue Amount", each List.Sum([BILLABLE_ALL]), type number}}),
				    ServiceWithCost = Table.AddColumn(ServiceGrouped, "Cost Amount", each null, type number),
				    ServiceWithInputs =
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.AddColumn(ServiceWithCost, "ActualCost_Mo", each null, type number),
				                "ForecastCost_Mo", each null, type number
				            ),
				            "Orig Contract Amount", each null, type number
				        ),
				    ServiceFinal = Table.AddColumn(
				        Table.AddColumn(
				            Table.AddColumn(ServiceWithInputs, "Project Subsegment", each "Service Project", type text),
				            "Stream", each "Projects", type text
				        ),
				        "Methodology", each "Amend", type text
				    ),
				    ServiceSelect = Table.SelectColumns(ServiceFinal,{"Month End","Customer Key","SurrogateProjectID","Project Subsegment","Stream","Methodology","Revenue Amount","Cost Amount","ActualCost_Mo","ForecastCost_Mo","Orig Contract Amount"}),
				
				    Combined = Table.Combine({JobsSelect, ServiceSelect}),
				    Typed = Table.TransformColumnTypes(Combined,{{"Revenue Amount", type number}, {"Cost Amount", type number}, {"Month End", type date}})
				 in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

