table RS_Measures
	isHidden
	lineageTag: dbca8cbc-d337-4cd0-8a6f-3ffd8a3a7945

	/// CRR methodology project revenue (job earned + service project billings), completed months only.
	measure 'Projects Revenue (CRR)' = CALCULATE(SUM(Projects_ProjectMonth_CRR_F[Revenue Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.1 Projects
		lineageTag: afd0578e-a50e-4ae8-a56f-c45a3281bf18

	/// CRR methodology project costs, completed months only.
	measure 'Projects Cost (CRR)' = CALCULATE(SUM(Projects_ProjectMonth_CRR_F[Cost Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.1 Projects
		lineageTag: 9d826691-8515-44ab-a099-7698525ca226

	/// CRR project gross profit.
	measure 'Projects GP (CRR)' = [Projects Revenue (CRR)] - [Projects Cost (CRR)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.1 Projects
		lineageTag: 11119134-a334-44ed-88a5-5f30953a328d

	/// CRR project gross margin.
	measure 'Projects GP % (CRR)' = DIVIDE([Projects GP (CRR)], [Projects Revenue (CRR)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 3. Gross Profit\3.1 Projects
		lineageTag: 7b7a9caf-55f1-4226-999d-9ba1ec2ec7ef

	/// Amend methodology service-project billings, completed months only.
	measure 'Projects Revenue (Amend - Service Project)' = CALCULATE(SUM(Projects_ProjectMonth_Amend_F[Revenue Amount]), Projects_ProjectMonth_Amend_F[Project Subsegment] = "Service Project", FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.1 Projects
		lineageTag: f2faece4-eb53-43f9-82d2-9d90b6b3ba00

	/// Amend job-cost project revenue from precomputed earned Revenue Amount, completed months only.
	measure 'Projects Revenue (Amend - Job Cost)' =
			CALCULATE(
			    SUM(Projects_ProjectMonth_Amend_F[Revenue Amount]),
			    Projects_ProjectMonth_Amend_F[Project Subsegment] = "Job Cost",
			    FYCALENDAR_D[Is Completed Month] = TRUE
			)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.1 Projects
		lineageTag: f483f9cf-c702-4a6b-9fe1-2c75caacfc9d

	/// Total Amend project revenue (job cost + service project), completed months only.
	measure 'Projects Revenue (Amend)' = CALCULATE([Projects Revenue (Amend - Job Cost)] + [Projects Revenue (Amend - Service Project)], FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.1 Projects
		lineageTag: 9261d9ba-e524-4b30-81fb-41ea02ad5aec

	/// Amend methodology project costs, completed months only.
	measure 'Projects Cost (Amend)' = CALCULATE(SUM(Projects_ProjectMonth_Amend_F[Cost Amount]), Projects_ProjectMonth_Amend_F[Project Subsegment] = "Job Cost", FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.1 Projects
		lineageTag: b9ecee3d-a016-463d-84a8-f0ad3bfa55c9

	/// Amend project gross profit.
	measure 'Projects GP (Amend)' = [Projects Revenue (Amend)] - [Projects Cost (Amend)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.1 Projects
		lineageTag: 424b940e-c774-415f-b1b8-db012b60e41e

	/// Amend project gross margin.
	measure 'Projects GP % (Amend)' = DIVIDE([Projects GP (Amend)], [Projects Revenue (Amend)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 3. Gross Profit\3.1 Projects
		lineageTag: 9f0cb4f7-c838-4384-af37-055e9d7bca38

	/// Variance between Amend and CRR project revenue.
	measure 'Projects Revenue Variance (Amend-CRR)' = [Projects Revenue (Amend)] - [Projects Revenue (CRR)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.1 Projects
		lineageTag: 8081108c-942d-4b53-9f09-4643b41a81a5

	/// Percent variance between Amend and CRR project revenue.
	measure 'Projects Revenue Variance %' = DIVIDE([Projects Revenue Variance (Amend-CRR)], [Projects Revenue (CRR)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Revenue\1.1 Projects
		lineageTag: 1d9eed3a-586f-4b91-8ed7-6079eeb41c25

	/// Service contract revenue from billings (CRR), completed months only.
	measure 'Service Contracts Revenue (CRR Billings)' = CALCULATE(SUM(SERVCONTRACTS_CustomerMonth_Billings_F[Revenue Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.2 Service Contracts
		lineageTag: 1fccdd30-172f-40ad-a145-3605bce3fc89

	/// Service contract revenue recognized on schedule (Amend), completed months only.
	measure 'Service Contracts Revenue (Amend Recognized)' = CALCULATE(SUM(SERVCONTRACTS_CustomerMonth_Recognized_Alt_F[Revenue Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.2 Service Contracts
		lineageTag: 872f1e41-de8a-4aac-97bc-b34e836ca977

	/// Variance between recognized and billed service contract revenue.
	measure 'Service Contracts Revenue Variance (Amend-CRR)' = [Service Contracts Revenue (Amend Recognized)] - [Service Contracts Revenue (CRR Billings)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.2 Service Contracts
		lineageTag: 6718f006-c0ec-4ce6-ab42-04ba349bfb2e

	/// Percent variance between recognized and billed service contract revenue.
	measure 'Service Contracts Revenue Variance %' = DIVIDE([Service Contracts Revenue Variance (Amend-CRR)], [Service Contracts Revenue (CRR Billings)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Revenue\1.2 Service Contracts
		lineageTag: cbc6c5e8-212a-4920-b212-533913688524

	/// T&M revenue from call-level billings (CRR), completed months only.
	measure 'T&M Revenue (CRR Call-Level)' = CALCULATE(SUM(TM_CustomerMonth_CRR_F[Revenue Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.3 T&M
		lineageTag: ea2ab74d-6d62-4ca7-8bfb-553cf434528a

	/// T&M revenue from call-detail billings (Amend), completed months only.
	measure 'T&M Revenue (Amend Call-Detail)' = CALCULATE(SUM(TM_CustomerMonth_Amend_F[Revenue Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.3 T&M
		lineageTag: b2300b2b-010e-4e25-823f-a63316323901

	/// Variance between call-detail and call-level T&M revenue.
	measure 'T&M Revenue Variance (Amend-CRR)' = [T&M Revenue (Amend Call-Detail)] - [T&M Revenue (CRR Call-Level)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.3 T&M
		lineageTag: 97c012ce-13af-460c-b4d6-48bf239e62e4

	/// Percent variance between call-detail and call-level T&M revenue.
	measure 'T&M Revenue Variance %' = DIVIDE([T&M Revenue Variance (Amend-CRR)], [T&M Revenue (CRR Call-Level)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 1. Revenue\1.3 T&M
		lineageTag: d26978f7-4ffa-4927-9605-6b3cfe36e154

	/// Legacy service projects stored as contracts, billings-based revenue, completed months only.
	measure 'Legacy Service Projects Revenue (Billings)' = CALCULATE(SUM(LEGACYPROJECTS_CustomerMonth_Billings_F[Revenue Amount]), FYCALENDAR_D[Is Completed Month] = TRUE)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.4 Legacy Service Projects
		lineageTag: bfeeacd1-71cf-406c-a904-5562a584f26b

	/// GL revenue (all markets) from POSTING_DATA_F, sign-adjusted.
	measure 'GL Revenue (Total)' = - CALCULATE(SUM(POSTING_DATA_F[PERDBLNC]), GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE")
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.5 GL
		lineageTag: db13d6d0-6412-4c12-a9cf-522109729ea4

	/// GL revenue mapped to Projects markets.
	measure 'GL Revenue (Projects)' = CALCULATE([GL Revenue (Total)], KEEPFILTERS(GL_ACCT_D[MARKET] IN {"O&M PROJECTS","SPECIAL PROJECT","PROJECTS","PLAN SPEC","CONTROLS","INDUSTRIAL","PERFORMANCE CONTRACT", "DESIGN BUILD"}))
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.5 GL
		lineageTag: e6fcf582-453e-41eb-96de-ae0fe1c22b5e

	/// GL revenue mapped to Spot/T&M markets.
	measure 'GL Revenue (Spot/T&M)' = CALCULATE([GL Revenue (Total)], KEEPFILTERS(GL_ACCT_D[MARKET] IN {"SPOT","O&M SPOT","INTERCOMPANY SPOT", "PROJECT REPAIR"}))
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.5 GL
		lineageTag: 7dbd27a9-1d52-4a7f-afac-d13ab92bc8ed

	/// GL revenue mapped to Contract markets.
	measure 'GL Revenue (Contracts)' = CALCULATE([GL Revenue (Total)], KEEPFILTERS(GL_ACCT_D[MARKET] IN {"ASSURED","CERTIFIED","INSPECTION","O&M"}))
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.5 GL
		lineageTag: fd90ce9d-867a-49f6-bbb9-708eff8e1a89

	/// GL revenue not captured by Projects/Spot/Contracts market buckets.
	measure 'GL Revenue (Other/Unmapped)' = [GL Revenue (Total)] - [GL Revenue (Projects)] - [GL Revenue (Spot/T&M)] - [GL Revenue (Contracts)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.5 GL
		lineageTag: 2b201657-cb86-4c64-b242-541ffe792afd

	column _
		lineageTag: aecc7c2b-f25a-46e0-8e58-8c8a466f17a0
		isNameInferred
		sourceColumn: [_]

	partition RS_Measures = calculated
		mode: import
		source = DATATABLE("_", INTEGER, {{1}})

