table FYCALENDAR_D
	lineageTag: 08601d45-a133-4be4-a463-75c45a804b28
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: c7f7812a-7693-4dd2-8a6f-8a7946ed0598
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: f86e0920-ddc5-43fb-91bd-13bdf678e07b
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = User

	column 'Fiscal Year Label'
		dataType: string
		lineageTag: 49c18a0e-c236-4ad3-b737-1e474c46ba12
		summarizeBy: none
		sourceColumn: Fiscal Year Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Default'
		dataType: string
		lineageTag: 63d4d936-cd53-4635-b37f-f95c031fcc3c
		summarizeBy: none
		sourceColumn: Fiscal Year Default

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Start Of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e075ddd-f12f-42ec-8e92-2123398d04d2
		summarizeBy: none
		sourceColumn: Fiscal Start Of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal End Of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e68cbb8-827f-4dc8-83e2-dc5247722d11
		summarizeBy: none
		sourceColumn: Fiscal End Of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 12bc35fb-6cbb-489e-813e-829bd4d9b9ff
		summarizeBy: sum
		sourceColumn: Fiscal Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: int64
		formatString: 0
		lineageTag: 98b44aae-ed58-4e56-9973-8bbc73b5fbcd
		summarizeBy: sum
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Default'
		dataType: string
		lineageTag: a51fe3ff-732c-4576-902c-cf1440a6c979
		summarizeBy: none
		sourceColumn: Fiscal Month Default

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: fbb53f9b-9d59-49a4-8957-ce122b490151
		summarizeBy: sum
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Label'
		dataType: string
		lineageTag: 882099ed-5464-46bb-9f65-62172a35ad82
		summarizeBy: none
		sourceColumn: Fiscal Quarter Label
		sortByColumn: 'Fiscal Quarter'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Of Quarter'
		dataType: int64
		formatString: 0
		lineageTag: ea2f1547-5233-4fb2-9b90-679808c62bea
		summarizeBy: sum
		sourceColumn: Fiscal Month Of Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Quarter Label'
		dataType: string
		lineageTag: b5ab7ed1-de94-40e3-b072-74e479b4cec0
		summarizeBy: none
		sourceColumn: Fiscal Year Quarter Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Start Of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b57a5919-881a-46b0-bd57-64c410fbf7a8
		summarizeBy: none
		sourceColumn: Fiscal Start Of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal End Of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 50f958a4-1842-4e46-8448-b575e9f52bed
		summarizeBy: none
		sourceColumn: Fiscal End Of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: 595a0a17-c369-4813-b820-f3cc811ad221
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Offset

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Month Label'
		dataType: string
		lineageTag: f888cedd-2947-47ae-b197-614bfd379f4d
		summarizeBy: none
		sourceColumn: Fiscal Quarter Month Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Day Of Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 135aeb17-3ae7-4e34-9962-d74fa6926f43
		summarizeBy: sum
		sourceColumn: Fiscal Day Of Quarter

		annotation SummarizationSetBy = Automatic

	column 'Is Current Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff598fbb-c663-4346-a058-65ff699cbe2c
		summarizeBy: none
		sourceColumn: Is Current Month

		annotation SummarizationSetBy = Automatic

	column 'Is Current Calendar Year'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ed285be0-c686-4996-a2d3-b2e20a031177
		summarizeBy: none
		sourceColumn: Is Current Calendar Year

		annotation SummarizationSetBy = Automatic

	column 'Is Current Fiscal Year'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cdc8cd9b-351b-4892-a406-07319a8e2e30
		summarizeBy: none
		sourceColumn: Is Current Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Week Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 352a0f94-76db-4aa6-a6b7-159223a1ddef
		summarizeBy: none
		sourceColumn: Week Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Is Current Week'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 81fe4916-b4f9-424e-b6a7-0d27540a4b96
		summarizeBy: none
		sourceColumn: Is Current Week

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Day Of Year'
		dataType: int64
		formatString: 0
		lineageTag: 3047a90f-e24b-4095-a4cc-a1b5313947d3
		summarizeBy: sum
		sourceColumn: Fiscal Day Of Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Of Year'
		dataType: int64
		formatString: 0
		lineageTag: bbbe5b1d-bff7-45bb-93a7-3370b89c88e3
		summarizeBy: sum
		sourceColumn: Fiscal Week Of Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Label'
		dataType: string
		lineageTag: 4b6983bd-d08c-4044-886d-8741989f439c
		summarizeBy: none
		sourceColumn: Fiscal Week Label

		annotation SummarizationSetBy = Automatic

	column 'Is Previous Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ad64ea0e-3489-4e6d-a752-84766b13a8cc
		summarizeBy: none
		sourceColumn: Is Previous Month

		annotation SummarizationSetBy = Automatic

	column 'Is Previous Fiscal Year'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 695d7e31-99e4-4e2c-afef-c4922bac7f1b
		summarizeBy: none
		sourceColumn: Is Previous Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Is Previous Week'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26946448-ae94-447e-8313-bf75ef049fc8
		summarizeBy: none
		sourceColumn: Is Previous Week

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Name'
		dataType: string
		lineageTag: 4829bb36-13ae-4263-97fc-efc8e2cd90d0
		summarizeBy: none
		sourceColumn: Fiscal Month Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Name Long'
		dataType: string
		lineageTag: 86824416-fc58-4353-af8e-779256ab36c4
		summarizeBy: none
		sourceColumn: Fiscal Month Name Long

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Name'
		dataType: string
		lineageTag: fe4ebbaa-7629-4fc7-92d1-de6398a79051
		summarizeBy: none
		sourceColumn: Fiscal Week Name

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 951ff7cf-3934-46de-b0fc-06c0cefd39f0
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'MMM Label'
		dataType: string
		lineageTag: 6880e1f6-af34-4504-89c3-c11840c67247
		summarizeBy: none
		sourceColumn: MMM Label

		annotation SummarizationSetBy = Automatic

	column 'Is Completed Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ac93c66b-336a-433b-b35f-8add60d50478
		summarizeBy: none
		sourceColumn: Is Completed Month

		annotation SummarizationSetBy = Automatic

	column 'Is Completed Quarter'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ac4209a9-5059-43f1-ba3f-2764d02abed0
		summarizeBy: none
		sourceColumn: Is Completed Quarter

		annotation SummarizationSetBy = Automatic

	column 'Month Letter' =
			
			SWITCH(
			    MONTH('FYCALENDAR_D'[Date]),
			     1, "J",
			     2, "F",
			     3, "M",
			     4, "A",
			     5, "M" & UNICHAR(8201), //Second Occurence
			     6, "J" & UNICHAR(8202), //Second Occurence
			     7, "J" & UNICHAR(8201), //Third Occurence
			     8, "A" & UNICHAR(8201), //Second Occurence
			     9, "S",
			     10, "O",
			     11, "N",
			     12, "D"
			)
		lineageTag: 3a6a69a2-89e3-460b-88ca-94148add224d
		summarizeBy: none
		sortByColumn: 'Fiscal Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition FYCALENDAR_D = m
		mode: import
		source = ```
				let
				    // The FiscalYearEnd determines in which month the fiscal year ends. If necessary you can adjust it. 
				    FiscalYearEnd = 9,
				
				    // Today is used throughout the fiscal logic and for determining current period flags
				    Today = Date.From(DateTime.LocalNow()),
				
				    // Sets the start date for your calendar
				    StartDate = #date(2020, 1, 1),
				
				    // The calendar runs until the end of the current year. Change this if you need your calendar to run to another date. 
				    EndDate = Date.AddYears(Date.EndOfYear(Today),1),
				
				    // The current Fiscal Year value is a helper value for other calculations
				    CurrentFiscalYear = Date.Year( Date.AddMonths( Today, 12 - FiscalYearEnd ) ),
				
				    ListOfDates =
				        List.Dates(
				            StartDate,
				            Duration.Days(EndDate - StartDate) + 1,
				            #duration(1, 0, 0, 0)
				        ),
				
				    MyDateTable =
				        Table.FromList(
				            ListOfDates,
				            Splitter.SplitByNothing(),
				            type table[Date = date],
				            null,
				            ExtraValues.Error
				        ),
				
				    Add_FiscalYearNumber =
				        Table.AddColumn(
				            MyDateTable,
				            "FiscalYear",
				            each Date.Year(Date.AddMonths([Date], 12 - FiscalYearEnd)),
				            Int64.Type
				        ),
				
				    Add_FiscalYearLabel =
				        Table.AddColumn(
				            Add_FiscalYearNumber,
				            "FiscalYearLabel",
				            each "FY" & Text.From([FiscalYear]),
				            Text.Type
				        ),
				
				    // Allows you to select the 'Current' or 'Previous' year dynamically. 
				    Add_FiscalYearDefault =
				        Table.AddColumn(
				            Add_FiscalYearLabel,
				            "FiscalYearDefault",
				            each
				                if [FiscalYear] = CurrentFiscalYear then "Current"
				                else if [FiscalYear] = (CurrentFiscalYear - 1) then "Previous"
				                else "FY" & Text.From([FiscalYear]),
				            Text.Type
				        ),
				
				    Add_FiscalStartOfYear =
				        Table.AddColumn(
				            Add_FiscalYearDefault,
				            "FiscalStartOfYear",
				            each [
				                Offset = if FiscalYearEnd = 12 then 0 else FiscalYearEnd - 12,
				                FiscalStartOfYear = Date.AddMonths(Date.StartOfYear([Date]), Offset)
				            ][FiscalStartOfYear],
				            Date.Type
				        ),
				
				    Add_FiscalEndOfYear =
				        Table.AddColumn(
				            Add_FiscalStartOfYear,
				            "FiscalEndOfYear",
				            each Date.AddMonths(Date.EndOfYear([Date]), FiscalYearEnd - 12),
				            Date.Type
				        ),
				
				    // -----------------------------------------------------
				    // Fiscal Day & Week of Fiscal Year
				    // -----------------------------------------------------
				
				    Add_FiscalDayOfYear =
				        Table.AddColumn(
				            Add_FiscalEndOfYear,
				            "FiscalDayOfYear",
				            each Number.From([Date] - [FiscalStartOfYear]) + 1,
				            Int64.Type
				        ),
				
				    Add_FiscalWeekOfYear =
				        Table.AddColumn(
				            Add_FiscalDayOfYear,
				            "FiscalWeekOfYear",
				            each Number.RoundUp([FiscalDayOfYear] / 7),
				            Int64.Type
				        ),
				
				    Add_FiscalWeekLabel =
				        Table.AddColumn(
				            Add_FiscalWeekOfYear,
				            "FiscalWeekLabel",
				            each
				                "FY" &
				                Text.From([FiscalYear]) &
				                " W" &
				                Text.PadStart(Text.From([FiscalWeekOfYear]), 2, "0"),
				            Text.Type
				        ),
				
				    // -----------------------------------------------------
				    // Continue existing logic
				    // -----------------------------------------------------
				
				    // A year Offset value indicates the relative position of the current year (based on today's date)
				    Add_FiscalYearOffset =
				        Table.AddColumn(
				            Add_FiscalWeekLabel,
				            "FiscalYearOffset",
				            each ([FiscalYear] - CurrentFiscalYear),
				            Int64.Type
				        ),
				
				    Add_FiscalMonthNumber =
				        Table.AddColumn(
				            Add_FiscalYearOffset,
				            "FiscalMonth",
				            each Date.Month(Date.AddMonths([Date], -FiscalYearEnd)),
				            Int64.Type
				        ),
				
				    // Allows you to select the 'Current' or 'Previous' month dynamically.
				    Add_FiscalMonthDefault =
				        Table.AddColumn(
				            Add_FiscalMonthNumber,
				            "FiscalMonthDefault",
				            each
				                if Date.IsInCurrentMonth([Date]) then "Current"
				                else if Date.IsInPreviousMonth([Date]) then "Previous"
				                else Text.From([FiscalMonth]),
				            Text.Type
				        ),
				
				    Add_FiscalQuarterNumber =
				        Table.AddColumn(
				            Add_FiscalMonthDefault,
				            "FiscalQuarter",
				            each Number.RoundUp([FiscalMonth] / 3),
				            Int64.Type
				        ),
				
				    Add_FiscalQuarterLabel =
				        Table.AddColumn(
				            Add_FiscalQuarterNumber,
				            "FiscalQuarterLabel",
				            each "FQ" & Text.From([FiscalQuarter]),
				            Text.Type
				        ),
				
				    Add_FiscalMonthOfQuarter =
				        Table.AddColumn(
				            Add_FiscalQuarterLabel,
				            "FiscalMonthOfQuarter",
				            each [FiscalMonth] - 3 * ([FiscalQuarter] - 1),
				            Int64.Type
				        ),
				
				    Add_FiscalYearQuarterLabel =
				        Table.AddColumn(
				            Add_FiscalMonthOfQuarter,
				            "FiscalYearQuarterLabel",
				            each "FY" & Text.From([FiscalYear]) & " Q" & Text.From([FiscalQuarter]),
				            Text.Type
				        ),
				
				    Add_FiscalStartOfQuarter =
				        Table.AddColumn(
				            Add_FiscalYearQuarterLabel,
				            "FiscalStartOfQuarter",
				            each Date.StartOfMonth(Date.AddMonths([Date], 1 - [FiscalMonthOfQuarter])),
				            Date.Type
				        ),
				
				    Add_FiscalEndOfQuarter =
				        Table.AddColumn(
				            Add_FiscalStartOfQuarter,
				            "FiscalEndOfQuarter",
				            each Date.EndOfMonth(Date.AddMonths([Date], 3 - [FiscalMonthOfQuarter])),
				            Date.Type
				        ),
				
				    // Quarter offset logic
				    Add_FiscalQuarterOffset =
				        Table.AddColumn(
				            Add_FiscalEndOfQuarter,
				            "FiscalQuarterOffset",
				            each [
				                CurrentFiscalMonth = Date.Month(Date.AddMonths(Today, -FiscalYearEnd)),
				                CurrentFiscalQuarter = Number.RoundUp(CurrentFiscalMonth / 3),
				                FiscalQuarterOffset =
				                    (([FiscalYear] - CurrentFiscalYear) * 4)
				                        + ([FiscalQuarter] - CurrentFiscalQuarter)
				            ][FiscalQuarterOffset],
				            Int64.Type
				        ),
				
				    Add_FiscalQuarterMonthLabel =
				        Table.AddColumn(
				            Add_FiscalQuarterOffset,
				            "FiscalQuarterMonthLabel",
				            each
				                "FQ"
				                    & Text.From([FiscalQuarter])
				                    & ": "
				                    & Date.ToText([FiscalStartOfQuarter], "MMM yyyy")
				                    & " - "
				                    & Date.ToText([FiscalEndOfQuarter], "MMM yyyy"),
				            Text.Type
				        ),
				
				    Add_FiscalDayOfQuarter =
				        Table.AddColumn(
				            Add_FiscalQuarterMonthLabel,
				            "FiscalDayOfQuarter",
				            each Number.From([Date] - [FiscalStartOfQuarter]) + 1,
				            Int64.Type
				        ),
				
				    // -----------------------------------------------------
				    // Current-period indicators
				    // -----------------------------------------------------
				
				    Add_IsCurrentMonth =
				        Table.AddColumn(
				            Add_FiscalDayOfQuarter,
				            "IsCurrentMonth",
				            each Date.Year([Date]) = Date.Year(Today)
				                and Date.Month([Date]) = Date.Month(Today),
				            type logical
				        ),
				
				    Add_IsCurrentCalendarYear =
				        Table.AddColumn(
				            Add_IsCurrentMonth,
				            "IsCurrentCalendarYear",
				            each Date.Year([Date]) = Date.Year(Today),
				            type logical
				        ),
				
				    Add_IsCurrentFiscalYear =
				        Table.AddColumn(
				            Add_IsCurrentCalendarYear,
				            "IsCurrentFiscalYear",
				            each [FiscalYear] = CurrentFiscalYear,
				            type logical
				        ),
				
				    CurrentWeekStart =
				        Date.AddDays(Today, 1 - Date.DayOfWeek(Today, Day.Monday)),
				
				    Add_WeekStart =
				        Table.AddColumn(
				            Add_IsCurrentFiscalYear,
				            "WeekStart",
				            each Date.AddDays([Date], 1 - Date.DayOfWeek([Date], Day.Monday)),
				            type date
				        ),
				
				    Add_IsCurrentWeek =
				        Table.AddColumn(
				            Add_WeekStart,
				            "IsCurrentWeek",
				            each [WeekStart] = CurrentWeekStart,
				            type logical
				        ),
				
				    // -----------------------------------------------------
				    // Previous-period indicators
				    // -----------------------------------------------------
				
				    Add_IsPreviousMonth =
				        Table.AddColumn(
				            Add_IsCurrentWeek,
				            "IsPreviousMonth",
				            each Date.IsInPreviousMonth([Date]),
				            type logical
				        ),
				
				    Add_IsPreviousFiscalYear =
				        Table.AddColumn(
				            Add_IsPreviousMonth,
				            "IsPreviousFiscalYear",
				            each [FiscalYear] = (CurrentFiscalYear - 1),
				            type logical
				        ),
				
				    PreviousWeekStart =
				        Date.AddDays(Today, 1 - Date.DayOfWeek(Today, Day.Monday) - 7),
				
				    Add_IsPreviousWeek =
				        Table.AddColumn(
				            Add_IsPreviousFiscalYear,
				            "IsPreviousWeek",
				            each [WeekStart] = PreviousWeekStart,
				            type logical
				        ),
				
				    // -----------------------------------------------------
				    // Column cleanup
				    // -----------------------------------------------------
				// -----------------------------------------------------
				// Additional fiscal month & week labels for CB-TI
				// -----------------------------------------------------
				
				Add_FiscalMonthName =
				    Table.AddColumn(
				        Add_IsPreviousWeek,
				        "FiscalMonthName",
				        each "FM" & Text.PadStart(Text.From([FiscalMonth]), 2, "0"),
				        Text.Type
				    ),
				
				Add_FiscalMonthNameLong =
				    Table.AddColumn(
				        Add_FiscalMonthName,
				        "FiscalMonthNameLong",
				        each "FM" & Text.PadStart(Text.From([FiscalMonth]), 2, "0") 
				            & " - " & Date.MonthName([Date]),
				        Text.Type
				    ),
				
				Add_FiscalWeekName =
				    Table.AddColumn(
				        Add_FiscalMonthNameLong,
				        "FiscalWeekName",
				        each "FW" & Text.PadStart(Text.From([FiscalWeekOfYear]), 2, "0"),
				        Text.Type
				    ),
				
				    #"Rename Columns" =
				        Table.TransformColumnNames(
				            Add_FiscalWeekName,
				            each [
				                SplitTextByTransition =
				                    Splitter.SplitTextByCharacterTransition({"a" .. "z"}, {"A" .. "Z"})(_),
				                CombineValues = Text.Combine(SplitTextByTransition, " "),
				                RemoveUnderscores = Text.Replace(CombineValues, "_", " ")
				            ][RemoveUnderscores]
				        ),
				
				    #"Inserted Month Name" =
				        Table.AddColumn(#"Rename Columns", "Month Name", each Date.MonthName([Date]), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Month Name", "MMM Label", each Text.Start([Month Name], 3)),
				    Add_IsCompletedMonth = Table.AddColumn(#"Added Custom", "Is Completed Month", each Date.EndOfMonth([Date])< Date.StartOfMonth(Date.From(DateTime.LocalNow())), type logical),
				    #"Added Custom1" = Table.AddColumn(Add_IsCompletedMonth, "Is Completed Quarter", each [Fiscal End Of Quarter] < Date.From(DateTime.LocalNow()), type logical)
				in
				    #"Added Custom1"
				```

	calendar Fiscal
		lineageTag: 71c24683-f75f-4b81-b7ae-683b30a6c32d

		calendarColumnGroup = year
			primaryColumn: 'Fiscal Year'
			associatedColumn: 'Fiscal Year Label'

		calendarColumnGroup = quarterOfYear
			primaryColumn: 'Fiscal Quarter'
			associatedColumn: 'Fiscal Quarter Label'

		calendarColumnGroup = monthOfYear
			primaryColumn: 'Fiscal Month'
			associatedColumn: 'Fiscal Month Name'

		calendarColumnGroup = weekOfYear
			primaryColumn: 'Fiscal Week Of Year'
			associatedColumn: 'Fiscal Week Name'

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

