table SC_CustomerMonth_Revenue
	lineageTag: f81fcd52-9d2f-4658-8465-7a232a678441

	column 'Customer Key'
		dataType: string
		lineageTag: 097dc48a-4f3e-46e7-ae28-4309b2694424
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

	column 'Month End'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e9eb3c1-f927-4d0c-b747-e199aa4c4e3a
		summarizeBy: none
		sourceColumn: Month End

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SC Revenue'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b9c111ba-8c7a-49c9-9ad0-fd7a20cff608
		summarizeBy: sum
		sourceColumn: SC Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition SC_CustomerMonth_Revenue = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = SERVCONTRACTS_REVENUE_F,
				
				    Typed =
				        Table.TransformColumnTypes(
				            Source,
				            {{"Date", type date}, {"AgreementKey", type text}, {"Amount", Currency.Type}}
				        ),
				
				    AddMonthEnd =
				        Table.AddColumn(
				            Typed,
				            "Month End",
				            each Date.EndOfMonth([Date]),
				            type date
				        ),
				
				    AddCustomerKey =
				        Table.AddColumn(
				            AddMonthEnd,
				            "Customer Key",
				            each
				                let
				                    t = [AgreementKey],
				                    pos = Text.PositionOf(t, "_", Occurrence.Last)
				                in
				                    if pos > 0 then Text.Start(t, pos) else null,
				            type text
				        ),
				
				    FilterValid =
				        Table.SelectRows(AddCustomerKey, each [Customer Key] <> null and [Customer Key] <> ""),
				
				    Grouped =
				        Table.Group(
				            FilterValid,
				            {"Customer Key", "Month End"},
				            {{"SC Revenue", each List.Sum([Amount]), Currency.Type}}
				        )
				in
				    Grouped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

