table '_Key Measures'
	lineageTag: edee0a95-274b-48e3-9abb-e41cca48e9fb

	/// Central selected-methods revenue across Projects, Service Contracts, and T&M.
	measure Revenue = SUM ( FINANCIALS_F[Revenue Amount] )
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 1. Revenue\1.2 Selected Methods
		lineageTag: b0a5e6ef-3e51-4d10-bbd3-1bdea3cc4804

	/// Central selected-methods cost across Projects, Service Contracts, and T&M.
	measure Cost = SUM ( FINANCIALS_F[Cost Amount] )
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 2. Cost\2.1 Selected Methods
		lineageTag: ddb90d73-ddae-41b5-a5f2-8444d45fc424

	/// Selected-methods gross profit = Revenue - Cost.
	measure 'Gross Profit' = [Revenue] - [Cost]
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 3. Gross Profit\3.1 Selected Methods
		lineageTag: 5c4fd06d-2b02-433d-826a-15892c0c6e05

	/// Service contract revenue only (completed months), intended as the revenue basis for retention metrics.
	measure 'Service Contract Revenue' = CALCULATE ( SUM ( SERVCONTRACTS_Financials_F[Revenue Amount] ), FYCALENDAR_D[Is Completed Month] = TRUE () )
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.1 Base
		lineageTag: 5ad68fe2-c1ac-4873-a32a-a946fd4adabc

	/// GL revenue from POSTING_DATA_F, filtered to GL_ACCT_D[ACCOUNT_TYPE] = REVENUE and completed months only. Sign convention uses (Credits - Debits) to return positive revenue.
	measure 'GL Revenue' =
			CALCULATE(
			    SUM(POSTING_DATA_F[CRDTAMNT]) - SUM(POSTING_DATA_F[DEBITAMT]),
			    GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			    'FYCALENDAR_D'[Is Completed Month] = TRUE
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 1. Revenue\1.1 GL
		lineageTag: 86628367-4060-4974-bd5f-4d4d2c9fad6e

	/// GL revenue subset for project-related markets (PROJECTS, O&M PROJECTS, PROJECT REPAIR), using the same sign convention as GL Revenue.
	measure 'GL Revenue (Projects)' =
			CALCULATE(
			    [GL Revenue],
			    GL_ACCT_D[MARKET] IN { "PROJECTS", "O&M PROJECTS", "PROJECT REPAIR" }
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 1. Revenue\1.1 GL
		lineageTag: 27a0ddaf-537b-4bda-bbce-5fe0baf866e8

	/// GL revenue (credits - debits) for revenue accounts, scoped to Service Contracts using STREAM_D/GL market mapping. Completed months only via [GL Revenue].
	measure 'GL Revenue (Service Contracts)' = CALCULATE ( [GL Revenue], STREAM_D[Stream] = "Service Contracts" )
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 1. Revenue\1.1 GL
		lineageTag: 169a95a0-b078-4bba-8888-639fd14eadbc

	/// GL revenue (credits - debits) for revenue accounts, scoped to T&M using STREAM_D/GL market mapping. Completed months only via [GL Revenue].
	measure 'GL Revenue (T&M)' = CALCULATE ( [GL Revenue], STREAM_D[Stream] = "T&M" )
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 1. Revenue\1.1 GL
		lineageTag: e8c4acc0-eb66-4b38-aa88-b4c16e814c71

	/// DEPRECATED: Prior-year service contract revenue for the current fiscal period selection (completed months). Superseded by R12M As Of metrics.
	measure 'Service Contract Revenue PY (FY Period)' = CALCULATE ( [Service Contract Revenue], SAMEPERIODLASTYEAR ( FYCALENDAR_D[Date] ) )
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\Base
		lineageTag: b5559eba-db1a-40a7-b6f3-a6c13cebf9cc

	/// DEPRECATED: Retention denominator for FY Period. Superseded by R12M As Of metrics.
	measure 'Retention Base PY (FY Period)' =
			VAR Customers = VALUES ( CUSTOMERS_D[Customer Key] )
			RETURN
			SUMX (
			    Customers,
			    VAR RevenuePY = [Service Contract Revenue PY (FY Period)]
			    RETURN IF ( RevenuePY > 0, RevenuePY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\Components
		lineageTag: 629c0203-9bc6-4da2-afd9-19f89cbed31c

	/// DEPRECATED: FY Period churn component. Superseded by R12M As Of metrics.
	measure 'Churn Revenue (FY Period)' =
			VAR Customers = VALUES ( CUSTOMERS_D[Customer Key] )
			RETURN
			SUMX (
			    Customers,
			    VAR RevenueCY = COALESCE ( [Service Contract Revenue], 0 )
			    VAR RevenuePY = COALESCE ( [Service Contract Revenue PY (FY Period)], 0 )
			    RETURN IF ( RevenuePY > 0 && RevenueCY = 0, RevenuePY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\Components
		lineageTag: f119ebf3-e4ad-4463-960c-cdfb15f5d523

	/// DEPRECATED: FY Period contraction component. Superseded by R12M As Of metrics.
	measure 'Contraction Revenue (FY Period)' =
			VAR Customers = VALUES ( CUSTOMERS_D[Customer Key] )
			RETURN
			SUMX (
			    Customers,
			    VAR RevenueCY = COALESCE ( [Service Contract Revenue], 0 )
			    VAR RevenuePY = COALESCE ( [Service Contract Revenue PY (FY Period)], 0 )
			    RETURN
			        IF ( RevenuePY > 0 && RevenueCY > 0 && RevenueCY < RevenuePY, RevenuePY - RevenueCY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\Components
		lineageTag: 9f7f8586-583c-48e4-89eb-a0fc03ada693

	/// DEPRECATED: FY Period upsell component. Superseded by R12M As Of metrics.
	measure 'Upsell Revenue (FY Period)' =
			VAR Customers = VALUES ( CUSTOMERS_D[Customer Key] )
			RETURN
			SUMX (
			    Customers,
			    VAR RevenueCY = COALESCE ( [Service Contract Revenue], 0 )
			    VAR RevenuePY = COALESCE ( [Service Contract Revenue PY (FY Period)], 0 )
			    RETURN IF ( RevenuePY > 0 && RevenueCY > RevenuePY, RevenueCY - RevenuePY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\Components
		lineageTag: 898a71c0-9cfc-4002-b8e1-258faa3a14f0

	/// DEPRECATED: FY Period NRR. Superseded by R12M As Of metrics.
	measure 'Net Revenue Retention % (FY Period)' =
			VAR BasePY = [Retention Base PY (FY Period)]
			VAR Numerator =
			    BasePY
			        - [Churn Revenue (FY Period)]
			        - [Contraction Revenue (FY Period)]
			        + [Upsell Revenue (FY Period)]
			RETURN
			IF ( BasePY > 0, DIVIDE ( Numerator, BasePY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\KPIs
		lineageTag: 191ad3fe-b90c-4713-be00-0e7e62d3e296

	/// DEPRECATED: FY Period GRR. Superseded by R12M As Of metrics.
	measure 'Gross Revenue Retention % (FY Period)' =
			VAR BasePY = [Retention Base PY (FY Period)]
			VAR Numerator = BasePY - [Churn Revenue (FY Period)] - [Contraction Revenue (FY Period)]
			RETURN
			IF ( BasePY > 0, DIVIDE ( Numerator, BasePY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\KPIs
		lineageTag: 059ece90-0c06-4b7d-acd0-0ddf7bf9619f

	/// DEPRECATED: FY Period churn rate. Superseded by R12M As Of metrics.
	measure 'Churn Rate % (FY Period)' =
			VAR BasePY = [Retention Base PY (FY Period)]
			RETURN
			IF ( BasePY > 0, DIVIDE ( [Churn Revenue (FY Period)], BasePY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 8. Deprecated\8.1 Retention\FY Period\KPIs
		lineageTag: 0c0a99cd-5af0-4ea2-9cd6-a334f4f19bb2

	/// Helper (hidden): last available service-contract month end within current non-date slice (e.g., Division/Contract filters), ignoring customer filters.
	measure 'Last SC Data Month End (In Slice)' =
			CALCULATE (
			    MAX ( SERVCONTRACTS_Financials_F[Month End] ),
			    REMOVEFILTERS ( FYCALENDAR_D[Date] ),
			    REMOVEFILTERS ( CUSTOMERS_D )
			)
		formatString: Long Date
		isHidden
		displayFolder: 7. Helper\7.1 Retention\R12M As Of
		lineageTag: 05f31032-8ab2-4ac8-920b-14f618a904a7

	/// Helper (hidden): as-of anchor month end for service contract rolling metrics. Clamped to last available month end in current slice and to the last completed month to avoid partial-month distortion.
	measure 'As Of Month End (SC)' =
			VAR SelectedMonthEnd =
			    EOMONTH ( CALCULATE ( MAX ( FYCALENDAR_D[Date] ), REMOVEFILTERS ( CUSTOMERS_D ) ), 0 )
			VAR LastDataMonthEnd =
			    [Last SC Data Month End (In Slice)]
			VAR LastCompletedMonthEnd =
			    CALCULATE ( MAX ( FYCALENDAR_D[Date] ), REMOVEFILTERS ( FYCALENDAR_D[Date] ), FYCALENDAR_D[Is Completed Month] = TRUE () )
			VAR EffectiveCap =
			    MIN ( LastDataMonthEnd, LastCompletedMonthEnd )
			RETURN
			IF ( ISBLANK ( EffectiveCap ), BLANK (), MIN ( SelectedMonthEnd, EffectiveCap ) )
		formatString: Long Date
		isHidden
		displayFolder: 7. Helper\7.1 Retention\R12M As Of
		lineageTag: f7db6df4-8c75-43e0-8be7-aeb263f74734

	/// Service contract revenue for the rolling 12 months ending at the as-of anchor month (completed months).
	measure 'Service Contract Revenue (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (SC)]
			RETURN
			IF (
			    ISBLANK ( AnchorDate ),
			    BLANK (),
			    CALCULATE ( [Service Contract Revenue], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ) )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.1 Base
		lineageTag: 06bacd2e-ee92-4536-a173-14753522d2b0

	/// Prior-year rolling 12-month service contract revenue aligned to the as-of anchor (completed months).
	measure 'Service Contract Revenue PY (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (SC)]
			VAR AnchorPY = EDATE ( AnchorDate, -12 )
			RETURN
			IF (
			    ISBLANK ( AnchorDate ),
			    BLANK (),
			    CALCULATE ( [Service Contract Revenue], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorPY, -12, MONTH ) )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.1 Base
		lineageTag: c4b7bf44-e5a3-45e9-8ad6-8f7e3a890a0f

	/// Retention denominator (R12M As Of): prior-year rolling revenue for customers that existed in the prior window.
	measure 'Retention Base PY (R12M As Of)' =
			SUMX (
			    VALUES ( CUSTOMERS_D[Customer Key] ),
			    VAR RevenuePY = [Service Contract Revenue PY (R12M As Of)]
			    RETURN IF ( RevenuePY > 0, RevenuePY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: 9a325994-61a8-4330-b910-0900e78d7c34

	/// Churn component (R12M As Of): lost revenue from customers with PY revenue but zero CY revenue in the rolling window.
	measure 'Churn Revenue (R12M As Of)' =
			SUMX (
			    VALUES ( CUSTOMERS_D[Customer Key] ),
			    VAR RevenueCY = [Service Contract Revenue (R12M As Of)]
			    VAR RevenuePY = [Service Contract Revenue PY (R12M As Of)]
			    RETURN IF ( RevenuePY > 0 && ( ISBLANK ( RevenueCY ) || RevenueCY = 0 ), RevenuePY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: 2c5b531f-5e3f-4b4f-a047-1d8455ea838f

	/// Contraction component (R12M As Of): decreases for retained customers (CY < PY) in the rolling window.
	measure 'Contraction Revenue (R12M As Of)' =
			SUMX (
			    VALUES ( CUSTOMERS_D[Customer Key] ),
			    VAR RevenueCY = COALESCE ( [Service Contract Revenue (R12M As Of)], 0 )
			    VAR RevenuePY = COALESCE ( [Service Contract Revenue PY (R12M As Of)], 0 )
			    RETURN IF ( RevenuePY > 0 && RevenueCY > 0 && RevenueCY < RevenuePY, RevenuePY - RevenueCY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: 12ab1f31-b1e4-41ad-9922-ac28d2c34bc6

	/// Upsell component (R12M As Of): increases for retained customers (CY > PY) in the rolling window.
	measure 'Upsell Revenue (R12M As Of)' =
			SUMX (
			    VALUES ( CUSTOMERS_D[Customer Key] ),
			    VAR RevenueCY = COALESCE ( [Service Contract Revenue (R12M As Of)], 0 )
			    VAR RevenuePY = COALESCE ( [Service Contract Revenue PY (R12M As Of)], 0 )
			    RETURN IF ( RevenuePY > 0 && RevenueCY > RevenuePY, RevenueCY - RevenuePY, 0 )
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: afcb9530-d884-49ba-9b8a-1f818099fc99

	/// Net Revenue Retention (NRR) for service contracts over rolling 12 months ending at the as-of anchor month.
	measure 'Net Revenue Retention % (R12M As Of)' =
			VAR BasePY = [Retention Base PY (R12M As Of)]
			VAR Numerator =
			    BasePY
			        - [Churn Revenue (R12M As Of)]
			        - [Contraction Revenue (R12M As Of)]
			        + [Upsell Revenue (R12M As Of)]
			RETURN
			IF ( BasePY > 0, DIVIDE ( Numerator, BasePY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs
		lineageTag: 1ff6524f-8e1e-4746-a8fc-e15fdf80fd3d

	/// Gross Revenue Retention (GRR) for service contracts over rolling 12 months ending at the as-of anchor month (excludes upsell).
	measure 'Gross Revenue Retention % (R12M As Of)' =
			VAR BasePY = [Retention Base PY (R12M As Of)]
			VAR Numerator = BasePY - [Churn Revenue (R12M As Of)] - [Contraction Revenue (R12M As Of)]
			RETURN
			IF ( BasePY > 0, DIVIDE ( Numerator, BasePY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs
		lineageTag: 87b699e8-d092-46e2-90e4-ec20b721aed6

	/// Service contract churn rate over rolling 12 months ending at the as-of anchor month.
	measure 'Churn Rate % (R12M As Of)' =
			VAR BasePY = [Retention Base PY (R12M As Of)]
			RETURN
			IF ( BasePY > 0, DIVIDE ( [Churn Revenue (R12M As Of)], BasePY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs
		lineageTag: 019f715d-01c2-4410-9017-b3916d5ac935

	/// Prior-year NRR for service contracts, evaluated at the anchor shifted back 12 months (R12M As Of).
	measure 'Net Revenue Retention % PY (R12M As Of)' =
			VAR CurrentAnchor = [As Of Month End (SC)]
			VAR PriorAnchor = EDATE ( CurrentAnchor, -12 )
			RETURN
			CALCULATE ( [Net Revenue Retention % (R12M As Of)], FYCALENDAR_D[Date] = PriorAnchor )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs\NRR
		lineageTag: 77f84c88-0594-46f4-9535-c8ba52e8d321

	/// Prior-year GRR for service contracts, evaluated at the anchor shifted back 12 months (R12M As Of).
	measure 'Gross Revenue Retention % PY (R12M As Of)' =
			VAR CurrentAnchor = [As Of Month End (SC)]
			VAR PriorAnchor = EDATE ( CurrentAnchor, -12 )
			RETURN
			CALCULATE ( [Gross Revenue Retention % (R12M As Of)], FYCALENDAR_D[Date] = PriorAnchor )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs\GRR
		lineageTag: 6dac9fb7-8d78-450c-acba-51115862b1e9

	/// Text indicator showing NRR (R12M As Of) change vs prior-year anchor (arrow + percent-point delta).
	measure 'Net Revenue Retention Trend vs PY (R12M As Of)' =
			VAR CY = [Net Revenue Retention % (R12M As Of)]
			VAR PY = [Net Revenue Retention % PY (R12M As Of)]
			RETURN
			IF (
			    ISBLANK ( CY ) || CY = 0 || ISBLANK ( PY ) || PY = 0,
			    BLANK (),
			    VAR Diff = CY - PY
			    VAR Icon =
			        SWITCH ( TRUE (), Diff > 0, UNICHAR ( 9650 ), Diff < 0, UNICHAR ( 9660 ), UNICHAR ( 9644 ) )
			    VAR PctText = IF ( Diff >= 0, UNICHAR ( 8199 ) & FORMAT ( Diff, "0.0%" ), FORMAT ( Diff, "0.0%" ) )
			    RETURN
			        Icon & " " & PctText
			)
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs\NRR
		lineageTag: fcf0440a-fe65-4583-80ab-55aa032e107a

	/// Text indicator showing GRR (R12M As Of) change vs prior-year anchor (arrow + percent-point delta).
	measure 'Gross Revenue Retention Trend vs PY (R12M As Of)' =
			VAR CY = [Gross Revenue Retention % (R12M As Of)]
			VAR PY = [Gross Revenue Retention % PY (R12M As Of)]
			RETURN
			IF (
			    ISBLANK ( CY ) || CY = 0 || ISBLANK ( PY ) || PY = 0,
			    BLANK (),
			    VAR Diff = CY - PY
			    VAR Icon =
			        SWITCH ( TRUE (), Diff > 0, UNICHAR ( 9650 ), Diff < 0, UNICHAR ( 9660 ), UNICHAR ( 9644 ) )
			    VAR PctText = IF ( Diff >= 0, UNICHAR ( 8199 ) & FORMAT ( Diff, "0.0%" ), FORMAT ( Diff, "0.0%" ) )
			    RETURN
			        Icon & " " & PctText
			)
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.3 KPIs\GRR
		lineageTag: c69604eb-250a-4861-9757-e1fde99c85e1

	/// Logo retention denominator: count of customers with prior-year rolling service contract revenue > 0 (R12M As Of).
	measure 'Retention Base Count PY (SC) (R12M As Of)' = COUNTROWS ( FILTER ( VALUES ( CUSTOMERS_D[Customer Key] ), [Service Contract Revenue PY (R12M As Of)] > 0 ) )
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 78bbd7d1-d531-477d-bcbc-37f5e4d34139

	/// Logo churn count: customers with PY rolling service contract revenue > 0 and CY rolling revenue = 0/blank (R12M As Of).
	measure 'Logo Churn Count (SC) (R12M As Of)' =
			COUNTROWS (
			    FILTER (
			        VALUES ( CUSTOMERS_D[Customer Key] ),
			        [Service Contract Revenue PY (R12M As Of)] > 0
			            && ( ISBLANK ( [Service Contract Revenue (R12M As Of)] )
			                || [Service Contract Revenue (R12M As Of)] = 0 )
			    )
			)
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 4aec9ea3-444d-44f9-a4c8-4e0cd5ece61b

	/// Logo retention % for service contracts (R12M As Of): 1 - (logo churn / prior-year logos).
	measure 'Logo Retention % (SC) (R12M As Of)' =
			VAR Base = [Retention Base Count PY (SC) (R12M As Of)]
			VAR Churn = [Logo Churn Count (SC) (R12M As Of)]
			RETURN
			IF ( Base > 0, DIVIDE ( Base - Churn, Base ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 28c0c74f-8141-4d5d-97fc-f2770a249ee3

	/// Prior-year logo retention % for service contracts, evaluated at the anchor shifted back 12 months (R12M As Of).
	measure 'Logo Retention % (SC) PY (R12M As Of)' =
			VAR CurrentAnchor = [As Of Month End (SC)]
			VAR PriorAnchor = EDATE ( CurrentAnchor, -12 )
			RETURN
			CALCULATE ( [Logo Retention % (SC) (R12M As Of)], FYCALENDAR_D[Date] = PriorAnchor )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 52ba18c0-1f6d-435b-b3ea-9fcb8924c70a

	/// Text indicator showing service contract logo retention change vs prior-year anchor (arrow + percent-point delta).
	measure 'Logo Retention Trend (SC) vs PY (R12M As Of)' =
			VAR CY = [Logo Retention % (SC) (R12M As Of)]
			VAR PY = [Logo Retention % (SC) PY (R12M As Of)]
			RETURN
			IF (
			    ISBLANK ( CY ) || CY = 0 || ISBLANK ( PY ) || PY = 0,
			    BLANK (),
			    VAR Diff = CY - PY
			    VAR Icon =
			        SWITCH ( TRUE (), Diff > 0, UNICHAR ( 9650 ), Diff < 0, UNICHAR ( 9660 ), UNICHAR ( 9644 ) )
			    VAR PctText = IF ( Diff >= 0, UNICHAR ( 8199 ) & FORMAT ( Diff, "0.0%" ), FORMAT ( Diff, "0.0%" ) )
			    RETURN
			        Icon & " " & PctText
			)
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 75b05ed2-c1d9-4a6b-8c70-4bfabe908d0a

	/// Churn component as a percent of the R12M As Of retention base (service contracts).
	measure 'Churn Revenue % (R12M As Of)' = DIVIDE ( [Churn Revenue (R12M As Of)], [Retention Base PY (R12M As Of)], 0 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: e804003f-f5f4-4a48-8ec2-a37e06d25aa9

	/// Contraction component as a percent of the R12M As Of retention base (service contracts).
	measure 'Contraction Revenue % (R12M As Of)' = DIVIDE ( [Contraction Revenue (R12M As Of)], [Retention Base PY (R12M As Of)], 0 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: 544717a2-71e5-4b58-aeb8-a8d8594fd5d9

	/// Upsell component as a percent of the R12M As Of retention base (service contracts).
	measure 'Upsell Revenue % (R12M As Of)' = DIVIDE ( [Upsell Revenue (R12M As Of)], [Retention Base PY (R12M As Of)], 0 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.2 Components
		lineageTag: 40463556-a3cc-42bb-8d07-e237669caa1d

	/// Service contract logo churn rate (R12M As Of): churned logos divided by prior-year logo base.
	measure 'Logo Churn % (SC) (R12M As Of)' = DIVIDE ( [Logo Churn Count (SC) (R12M As Of)], [Retention Base Count PY (SC) (R12M As Of)], 0 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: c228c82d-05a8-4256-99f0-ffe3c123f20c

	/// Waterfall step value for NRR breakdown (R12M As Of). Use with 'Waterfall - NRR Breakdown'[Category] on axis.
	measure 'NRR Waterfall Value (R12M As Of)' =
			VAR Selection = SELECTEDVALUE ( 'UI_Waterfall - NRR Breakdown'[ID] )
			VAR BasePY = [Retention Base PY (R12M As Of)]
			VAR Churn = [Churn Revenue (R12M As Of)]
			VAR Contraction = [Contraction Revenue (R12M As Of)]
			VAR Upsell = [Upsell Revenue (R12M As Of)]
			VAR Ending = BasePY - Churn - Contraction + Upsell
			RETURN
			SWITCH (
			    Selection,
			    1, BasePY,
			    2, -Churn,
			    3, -Contraction,
			    4, Upsell,
			    5, Ending
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.5 Waterfall
		lineageTag: 889dd863-22fd-4280-87e4-841f9d7f1418

	/// Customer-level retention category for service contracts in the R12M As Of framework (based on RevPY/RevCY). Use with a customer-grain visual or helper queries; not intended for high-cardinality axes.
	measure 'Customer Retention Category (SC) (R12M As Of)' =
			VAR RevCY = [Service Contract Revenue (R12M As Of)]
			VAR RevPY = [Service Contract Revenue PY (R12M As Of)]
			VAR HasCY = NOT ( ISBLANK ( RevCY ) ) && RevCY <> 0
			VAR HasPY = NOT ( ISBLANK ( RevPY ) ) && RevPY <> 0
			RETURN
			SWITCH (
			    TRUE (),
			    HasPY && NOT HasCY, "Churned",
			    HasPY && HasCY && RevCY < RevPY, "Contraction",
			    HasPY && HasCY && RevCY > RevPY, "Upsell",
			    HasPY && HasCY && RevCY = RevPY, "Retained",
			    NOT HasPY && HasCY, "New",
			    BLANK ()
			)
		isHidden
		displayFolder: 7. Helper\7.1 Retention\R12M As Of
		lineageTag: 2c96b912-2ba5-4b6a-a90f-4a34699d3c74

	/// Count of customers with prior-year rolling service contract revenue > 0 (R12M As Of).
	measure 'Customers PY (SC) (R12M As Of)' = COUNTROWS ( FILTER ( VALUES ( CUSTOMERS_D[Customer Key] ), [Service Contract Revenue PY (R12M As Of)] > 0 ) )
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 5cefcee4-c77f-4d64-abba-9101f1833bed

	/// Count of customers with current rolling service contract revenue > 0 (R12M As Of).
	measure 'Customers CY (SC) (R12M As Of)' = COUNTROWS ( FILTER ( VALUES ( CUSTOMERS_D[Customer Key] ), [Service Contract Revenue (R12M As Of)] > 0 ) )
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: f0fdbadc-4e43-47ab-bf66-d6a472ddaab4

	/// Count of churned customers for service contracts (R12M As Of): PY>0 and CY=0/blank.
	measure 'Customers Churned (SC) (R12M As Of)' =
			COUNTROWS (
			    FILTER (
			        VALUES ( CUSTOMERS_D[Customer Key] ),
			        [Service Contract Revenue PY (R12M As Of)] > 0
			            && ( ISBLANK ( [Service Contract Revenue (R12M As Of)] )
			                || [Service Contract Revenue (R12M As Of)] = 0 )
			    )
			)
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 26cd9fd6-e0e4-43ed-9b49-9cb7be263abd

	/// Count of contracting customers for service contracts (R12M As Of): PY>0, CY>0, CY<PY.
	measure 'Customers Contraction (SC) (R12M As Of)' =
			COUNTROWS (
			    FILTER (
			        VALUES ( CUSTOMERS_D[Customer Key] ),
			        [Service Contract Revenue PY (R12M As Of)] > 0
			            && [Service Contract Revenue (R12M As Of)] > 0
			            && [Service Contract Revenue (R12M As Of)] < [Service Contract Revenue PY (R12M As Of)]
			    )
			)
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: 106b9b2a-5a6f-4107-b24f-e4248603aaa6

	/// Count of upsell customers for service contracts (R12M As Of): PY>0 and CY>PY.
	measure 'Customers Upsell (SC) (R12M As Of)' =
			COUNTROWS (
			    FILTER (
			        VALUES ( CUSTOMERS_D[Customer Key] ),
			        [Service Contract Revenue PY (R12M As Of)] > 0
			            && [Service Contract Revenue (R12M As Of)] > [Service Contract Revenue PY (R12M As Of)]
			    )
			)
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: b87e2141-3ff2-454a-ad6c-27990a53ae5d

	/// Count of retained customers for service contracts (R12M As Of): PY>0 and CY>0.
	measure 'Customers Retained (SC) (R12M As Of)' =
			COUNTROWS (
			    FILTER (
			        VALUES ( CUSTOMERS_D[Customer Key] ),
			        [Service Contract Revenue PY (R12M As Of)] > 0
			            && [Service Contract Revenue (R12M As Of)] > 0
			    )
			)
		formatString: 0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.4 Logo (SC)
		lineageTag: d3e68b7a-735b-4d00-80c3-a400d0a1ce2b

	/// Helper (hidden): as-of anchor month end for financial measures (all streams). Clamped to last available FINANCIALS_F month end in current non-customer slice and to the last completed month to avoid partial-month distortion.
	measure 'As Of Month End (Financials)' =
			VAR LastDataMonthEnd =
			    CALCULATE ( MAX ( FINANCIALS_F[Month End] ), REMOVEFILTERS ( CUSTOMERS_D ) )
			VAR LastCompletedMonthEnd =
			    CALCULATE (
			        MAX ( FYCALENDAR_D[Date] ),
			        REMOVEFILTERS ( CUSTOMERS_D ),
			        FYCALENDAR_D[Is Completed Month] = TRUE ()
			    )
			VAR Anchor =
			    IF (
			        ISBLANK ( LastDataMonthEnd ),
			        LastCompletedMonthEnd,
			        IF (
			            ISBLANK ( LastCompletedMonthEnd ),
			            LastDataMonthEnd,
			            MIN ( LastDataMonthEnd, LastCompletedMonthEnd )
			        )
			    )
			RETURN
			    Anchor
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: 7. Helper\7.0 Date
		lineageTag: 6e80bea2-b183-4c5a-ad13-fe20b5ae31df

	/// Debug: exposes the financial as-of anchor date used by R12M/FY As Of financial measures.
	measure 'Debug – Anchor Date' = [As Of Month End (Financials)]
		formatString: yyyy-mm-dd
		displayFolder: 7. Helper\7.0 Date
		lineageTag: d21af0a2-01de-42e0-a3ba-7c8d58b83529

	/// Debug: R12M end date for financial R12M As Of measures (same as [As Of Month End (Financials)]).
	measure 'Debug - R12M End Date' = [As Of Month End (Financials)]
		formatString: yyyy-mm-dd
		displayFolder: 7. Helper\7.0 Date
		lineageTag: 9315fb97-d0b4-44a3-b8a9-01d6b27e040a

	/// Label for the rolling 12-month window used by financial R12M As Of measures.
	measure 'R12M Period Label' =
			VAR EndDate = [As Of Month End (Financials)]
			VAR StartDate = EDATE ( EndDate, -11 )
			RETURN
			    IF (
			        ISBLANK ( EndDate ),
			        "No Data",
			        FORMAT ( StartDate, "MMM yyyy" ) & "  " & FORMAT ( EndDate, "MMM yyyy" )
			    )
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Helpers
		lineageTag: 62e50123-5f2a-4329-92b6-920c50343167

	/// Selected-methods project revenue (completed months only).
	measure 'Project Revenue' =
			CALCULATE (
			    SUM ( FINANCIALS_F[Revenue Amount] ),
			    STREAM_D[Stream] = "Projects",
			    FYCALENDAR_D[Is Completed Month] = TRUE ()
			)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.2 Streams
		lineageTag: 65c3b22c-d06e-42ce-8065-0599b765fddb

	/// Selected-methods T&M revenue (completed months only).
	measure 'T&M Revenue' =
			CALCULATE (
			    SUM ( FINANCIALS_F[Revenue Amount] ),
			    STREAM_D[Stream] = "T&M",
			    FYCALENDAR_D[Is Completed Month] = TRUE ()
			)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.2 Streams
		lineageTag: 99b126eb-d6dd-4b97-bd65-02ad112aa64b

	/// Total selected-methods revenue across Projects, Service Contracts, and T&M (completed months only).
	measure 'Total Revenue' = [Project Revenue] + [Service Contract Revenue] + [T&M Revenue]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.1 Total
		lineageTag: 4f7b0ee8-d762-42f8-83f9-7301f526d7f0

	/// Selected-methods project cost (completed months only).
	measure 'Project Cost' =
			CALCULATE (
			    SUM ( FINANCIALS_F[Cost Amount] ),
			    STREAM_D[Stream] = "Projects",
			    FYCALENDAR_D[Is Completed Month] = TRUE ()
			)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.2 Streams
		lineageTag: aa4f1df6-c622-4916-bd92-dcb9a9f477bf

	/// Selected-methods T&M cost (completed months only).
	measure 'T&M Cost' =
			CALCULATE (
			    SUM ( FINANCIALS_F[Cost Amount] ),
			    STREAM_D[Stream] = "T&M",
			    FYCALENDAR_D[Is Completed Month] = TRUE ()
			)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.2 Streams
		lineageTag: 50dc0e92-17d7-44a1-8e1e-f0391570a5a0

	/// Selected-methods service contract cost (completed months only).
	measure 'Service Contract Cost' =
			CALCULATE (
			    SUM ( FINANCIALS_F[Cost Amount] ),
			    STREAM_D[Stream] = "Service Contracts",
			    FYCALENDAR_D[Is Completed Month] = TRUE ()
			)
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.2 Streams
		lineageTag: 42098795-085e-419a-855a-d964fbc79c09

	/// Total selected-methods cost across Projects, Service Contracts, and T&M (completed months only).
	measure 'Total Cost' = [Project Cost] + [Service Contract Cost] + [T&M Cost]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.1 Total
		lineageTag: 891d1a85-e72d-4c4c-b464-30cb02884c6a

	/// Selected-methods project gross profit (completed months only).
	measure 'Project GP' = [Project Revenue] - [Project Cost]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.2 Streams
		lineageTag: 36c11147-62a1-4de8-b45e-c3aff722109c

	/// Selected-methods service contract gross profit (completed months only).
	measure 'Service Contract Gross Profit' = [Service Contract Revenue] - [Service Contract Cost]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.2 Streams
		lineageTag: bec8b39e-13fe-46a2-84f5-1ff5745a276d

	/// Selected-methods T&M gross profit (completed months only).
	measure 'T&M Gross Profit' = [T&M Revenue] - [T&M Cost]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.2 Streams
		lineageTag: db36ff8a-84e2-4c43-9f51-48fb54b47275

	/// Total selected-methods gross profit (completed months only).
	measure 'Total Gross Profit' = [Total Revenue] - [Total Cost]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.1 Total
		lineageTag: 1d9134eb-b001-4472-9d16-2428df555f14

	/// Total gross profit percentage (completed months only).
	measure 'Total GP %' = DIVIDE ( [Total Gross Profit], [Total Revenue] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3. Gross Profit\3.1 Total
		lineageTag: 9a9c2d08-8241-4cb2-8011-2454af30b435

	/// Revenue selector for visuals that use the disconnected Revenue_Stream_D axis.
	measure 'Revenue (By Stream)' =
			VAR SelStream = SELECTEDVALUE ( STREAM_D[Stream] )
			RETURN
			    IF (
			        ISBLANK ( SelStream ),
			        [Total Revenue],
			        SWITCH (
			            SelStream,
			            "Projects", [Project Revenue],
			            "Service Contracts", [Service Contract Revenue],
			            "T&M", [T&M Revenue]
			        )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.3 By Stream
		lineageTag: 045df2aa-7250-42cc-9c54-5682a803643a

	/// Cost selector for visuals that use the disconnected Revenue_Stream_D axis.
	measure 'Cost (By Stream)' =
			VAR SelStream = SELECTEDVALUE ( STREAM_D[Stream] )
			RETURN
			    IF (
			        ISBLANK ( SelStream ),
			        [Total Cost],
			        SWITCH (
			            SelStream,
			            "Projects", [Project Cost],
			            "Service Contracts", [Service Contract Cost],
			            "T&M", [T&M Cost]
			        )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 2. Cost\2.3 By Stream
		lineageTag: 67b77942-804a-416c-8c16-cbc2955a7a6a

	/// Gross profit selector aligned to Revenue_Stream_D axis.
	measure 'Gross Profit (By Stream)' = [Revenue (By Stream)] - [Cost (By Stream)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.3 By Stream
		lineageTag: efba70a1-7c47-4cd1-b893-f9e77ad42b63

	/// Gross profit percent aligned to Revenue_Stream_D axis.
	measure 'GP % (By Stream)' = DIVIDE ( [Gross Profit (By Stream)], [Revenue (By Stream)] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3. Gross Profit\3.3 By Stream
		lineageTag: 1de7f7d1-6233-4169-9b06-84cf42d40a5f

	/// Total revenue over the rolling 12 months ending at the financial as-of anchor month end.
	measure 'Total Revenue (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (Financials)]
			RETURN
			    IF (
			        ISBLANK ( AnchorDate ),
			        BLANK (),
			        CALCULATE ( [Total Revenue], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue
		lineageTag: 22cdb7ca-8ace-47cb-8a88-75a26b00c776

	/// Prior-year total revenue over the rolling 12 months aligned to the financial as-of anchor month end.
	measure 'Total Revenue PY (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (Financials)]
			VAR AnchorPY = EDATE ( AnchorDate, -12 )
			RETURN
			    IF (
			        ISBLANK ( AnchorDate ),
			        BLANK (),
			        CALCULATE ( [Total Revenue], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorPY, -12, MONTH ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue
		lineageTag: 5972d34c-8ad0-4cd5-93a8-2d21f92e2b58

	/// Project revenue over the rolling 12 months ending at the financial as-of anchor month end.
	measure 'Project Revenue (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (Financials)]
			RETURN
			    IF (
			        ISBLANK ( AnchorDate ),
			        BLANK (),
			        CALCULATE ( [Project Revenue], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue\Streams
		lineageTag: 48b1de13-278e-4ade-8c04-6592942e4625

	/// T&M revenue over the rolling 12 months ending at the financial as-of anchor month end.
	measure 'T&M Revenue (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (Financials)]
			RETURN
			    IF (
			        ISBLANK ( AnchorDate ),
			        BLANK (),
			        CALCULATE ( [T&M Revenue], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue\Streams
		lineageTag: 57390524-639b-4780-a2bd-09ced1d5a7ec

	/// Alias for service contract revenue (R12M As Of) used by CRR visuals. Retention revenue is service contracts only.
	measure 'SC Revenue (R12M As Of)' = [Service Contract Revenue (R12M As Of)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue\Streams
		lineageTag: a6c5b52f-653c-4c92-8d46-ded269a3234a

	/// Total gross profit over the rolling 12 months ending at the financial as-of anchor month end.
	measure 'Total Gross Profit (R12M As Of)' =
			VAR AnchorDate = [As Of Month End (Financials)]
			RETURN
			    IF (
			        ISBLANK ( AnchorDate ),
			        BLANK (),
			        CALCULATE ( [Total Gross Profit], DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Gross Profit
		lineageTag: 06225159-ff90-44aa-b98c-452efdc5100e

	/// Total gross profit percent over the rolling 12 months ending at the financial as-of anchor month end.
	measure 'Total GP % (R12M As Of)' = DIVIDE ( [Total Gross Profit (R12M As Of)], [Total Revenue (R12M As Of)] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Gross Profit
		lineageTag: 0481e564-78dd-40c9-ab55-6df437e81fb4

	/// Share of total rolling-12-month revenue attributable to service contracts (derived as remainder of total after project and T&M).
	measure 'Recurring Mix % (SC) (R12M)' =
			VAR TotalRev = [Total Revenue (R12M As Of)]
			VAR ProjectRev = [Project Revenue (R12M As Of)]
			VAR TMRev = [T&M Revenue (R12M As Of)]
			VAR SCRev = TotalRev - ProjectRev - TMRev
			RETURN
			    DIVIDE ( SCRev, TotalRev )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue\Mix
		lineageTag: 3aeae34c-d528-4b20-908d-8ff8906e4cf5

	/// Percent of total rolling-12-month revenue coming from the largest revenue stream (Projects vs Service Contracts vs T&M).
	measure 'Stream Concentration % (R12M)' =
			VAR TotalRev = [Total Revenue (R12M As Of)]
			VAR ProjectRev = [Project Revenue (R12M As Of)]
			VAR TMRev = [T&M Revenue (R12M As Of)]
			VAR SCRev = TotalRev - ProjectRev - TMRev
			VAR TopStreamRev = MAX ( ProjectRev, MAX ( SCRev, TMRev ) )
			RETURN
			    DIVIDE ( TopStreamRev, TotalRev )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue\Mix
		lineageTag: c4f599b8-86b3-46be-8f92-84821dc8de58

	/// Rolling-12-month revenue growth vs prior-year rolling-12-month revenue at the same as-of anchor.
	measure 'Revenue Momentum % (R12M vs PY)' =
			VAR CY = [Total Revenue (R12M As Of)]
			VAR PY = [Total Revenue PY (R12M As Of)]
			RETURN
			    IF ( ISBLANK ( PY ) || PY = 0, BLANK (), DIVIDE ( CY - PY, PY ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue
		lineageTag: 7f5c6072-36fc-4fea-9ffc-3e685570e2e9

	/// Helper for 100% filled bar visuals: returns stream share vs remainder for a given Revenue_Stream_D and UI_BarFillParts selection (R12M).
	measure 'Revenue Stream Share Fill (R12M)' =
			VAR AxisStreamLabel = SELECTEDVALUE ( STREAM_D[Stream] )
			VAR Part = SELECTEDVALUE ( UI_BarFillParts[Part] )
			VAR TotalRev = [Total Revenue (R12M As Of)]
			VAR ProjectRev = [Project Revenue (R12M As Of)]
			VAR TMRev = [T&M Revenue (R12M As Of)]
			VAR SCRev = TotalRev - ProjectRev - TMRev
			VAR AxisStreamPart =
			    SWITCH (
			        AxisStreamLabel,
			        "Projects", "Project",
			        "Service Contracts", "Service Contract",
			        "T&M", "T&M"
			    )
			VAR StreamRev =
			    SWITCH ( AxisStreamPart, "Project", ProjectRev, "Service Contract", SCRev, "T&M", TMRev )
			RETURN
			    SWITCH (
			        TRUE (),
			        ISBLANK ( AxisStreamPart ) || ISBLANK ( Part ) || ISBLANK ( TotalRev ) || TotalRev = 0,
			            BLANK (),
			        Part = "Remainder",
			            MAX ( 0, TotalRev - StreamRev ),
			        Part = AxisStreamPart,
			            StreamRev,
			        0
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.1 R12M As Of\Revenue\Mix
		lineageTag: 510260ec-a145-4bc2-a071-8aabf8f51c1b

	/// Helper: selected fiscal year when a single fiscal year is selected; blank otherwise.
	measure 'Selected Fiscal Year (Single)' = SELECTEDVALUE ( FYCALENDAR_D[Fiscal Year] )
		isHidden
		displayFolder: 7. Helper\7.0 Date
		lineageTag: 1e5b9cac-872b-4bdf-859c-ea513ad2839b

	/// Helper (hidden): first date of the selected fiscal year.
	measure 'Selected FY Start Date' =
			VAR FY = [Selected Fiscal Year (Single)]
			RETURN
			    IF (
			        ISBLANK ( FY ),
			        BLANK (),
			        CALCULATE ( MIN ( FYCALENDAR_D[Date] ), REMOVEFILTERS ( FYCALENDAR_D ), FYCALENDAR_D[Fiscal Year] = FY )
			    )
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: 7. Helper\7.0 Date
		lineageTag: 721a6773-1292-4eb7-86a9-6a7303e6f28f

	/// Helper (hidden): last date of the selected fiscal year.
	measure 'Selected FY End Date' =
			VAR FY = [Selected Fiscal Year (Single)]
			RETURN
			    IF (
			        ISBLANK ( FY ),
			        BLANK (),
			        CALCULATE ( MAX ( FYCALENDAR_D[Date] ), REMOVEFILTERS ( FYCALENDAR_D ), FYCALENDAR_D[Fiscal Year] = FY )
			    )
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: 7. Helper\7.0 Date
		lineageTag: e6580b5d-b008-4b64-a35b-5cdc0d45f8ba

	/// As-of date for FY As Of measures: clamps the financial as-of anchor to the selected fiscal year end date when a fiscal year is selected.
	measure 'As Of Date (Financials)' =
			VAR FYEnd = [Selected FY End Date]
			VAR Anchor = [As Of Month End (Financials)]
			RETURN
			    IF ( ISBLANK ( FYEnd ), Anchor, IF ( ISBLANK ( Anchor ), FYEnd, MIN ( Anchor, FYEnd ) ) )
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: 7. Helper\7.0 Date
		lineageTag: 50806257-09b7-454d-8421-a588357edf75

	/// Helper (hidden): as-of date used for FY As Of revenue measures.
	measure 'As Of Date (Revenue)' = [As Of Date (Financials)]
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: 7. Helper\7.0 Date
		lineageTag: 947c7766-c211-47a1-9c83-c9be2fb872fe

	/// Annualized fiscal-year-to-date revenue from FY start through the as-of date (clamped to FY end).
	measure 'Total Revenue (FY As Of)' =
			VAR StartDate = [Selected FY Start Date]
			VAR EndDate = [As Of Date (Revenue)]
			RETURN
			    IF (
			        ISBLANK ( StartDate ) || ISBLANK ( EndDate ),
			        BLANK (),
			        CALCULATE ( [Total Revenue], REMOVEFILTERS ( FYCALENDAR_D ), DATESBETWEEN ( FYCALENDAR_D[Date], StartDate, EndDate ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Revenue
		lineageTag: 58dbab61-695c-4792-af59-41a8e26de4bc

	/// Prior-year fiscal-year-to-date revenue aligned to the FY As Of window.
	measure 'Total Revenue PY (FY As Of)' =
			VAR StartDate = [Selected FY Start Date]
			VAR EndDate = [As Of Date (Revenue)]
			VAR StartPY = EDATE ( StartDate, -12 )
			VAR EndPY = EDATE ( EndDate, -12 )
			RETURN
			    IF (
			        ISBLANK ( StartDate ) || ISBLANK ( EndDate ),
			        BLANK (),
			        CALCULATE ( [Total Revenue], REMOVEFILTERS ( FYCALENDAR_D ), DATESBETWEEN ( FYCALENDAR_D[Date], StartPY, EndPY ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Revenue
		lineageTag: 878f68d1-13ef-4a98-ba85-046da45e175e

	/// Year-over-year delta for FY As Of revenue window.
	measure 'Total Revenue YoY Δ (FY As Of)' = [Total Revenue (FY As Of)] - [Total Revenue PY (FY As Of)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Revenue
		lineageTag: cdae05cd-675c-4269-8049-c1ec17bda419

	/// Year-over-year percent change for FY As Of revenue window.
	measure 'Total Revenue YoY % (FY As Of)' = DIVIDE ( [Total Revenue YoY Δ (FY As Of)], [Total Revenue PY (FY As Of)] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Revenue
		lineageTag: 47b90008-b863-47ae-8192-6d838537aea2

	/// Annualized fiscal-year-to-date gross profit from FY start through the as-of date (clamped to FY end).
	measure 'Total Gross Profit (FY As Of)' =
			VAR StartDate = [Selected FY Start Date]
			VAR EndDate = [As Of Date (Financials)]
			RETURN
			    IF (
			        ISBLANK ( StartDate ) || ISBLANK ( EndDate ),
			        BLANK (),
			        CALCULATE ( [Total Gross Profit], REMOVEFILTERS ( FYCALENDAR_D ), DATESBETWEEN ( FYCALENDAR_D[Date], StartDate, EndDate ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Gross Profit
		lineageTag: 8c62cc4f-0328-45f6-8fab-6a7b15773d34

	/// Prior-year fiscal-year-to-date gross profit aligned to the FY As Of window.
	measure 'Total Gross Profit PY (FY As Of)' =
			VAR StartDate = [Selected FY Start Date]
			VAR EndDate = [As Of Date (Financials)]
			VAR StartPY = EDATE ( StartDate, -12 )
			VAR EndPY = EDATE ( EndDate, -12 )
			RETURN
			    IF (
			        ISBLANK ( StartDate ) || ISBLANK ( EndDate ),
			        BLANK (),
			        CALCULATE ( [Total Gross Profit], REMOVEFILTERS ( FYCALENDAR_D ), DATESBETWEEN ( FYCALENDAR_D[Date], StartPY, EndPY ) )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Gross Profit
		lineageTag: 4fd19ce0-07c8-4038-ad2e-00ef07aab561

	/// Year-over-year delta for FY As Of gross profit window.
	measure 'Total Gross Profit YoY Δ (FY As Of)' = [Total Gross Profit (FY As Of)] - [Total Gross Profit PY (FY As Of)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Gross Profit
		lineageTag: 381664e0-a8ba-4720-832e-013f35f39158

	/// Year-over-year percent change for FY As Of gross profit window.
	measure 'Total Gross Profit YoY % (FY As Of)' = DIVIDE ( [Total Gross Profit YoY Δ (FY As Of)], [Total Gross Profit PY (FY As Of)] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Gross Profit
		lineageTag: 741f7734-2743-4815-ad34-108606670ed1

	/// Gross profit percent over the FY As Of window.
	measure 'Total GP % (FY As Of)' = DIVIDE ( [Total Gross Profit (FY As Of)], [Total Revenue (FY As Of)] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Gross Profit
		lineageTag: f1bdeaa9-8539-45a4-b04d-614a1bb4e923

	/// Total revenue for the same selected period one year prior (uses current date filter context).
	measure 'Total Revenue PY' = CALCULATE ( [Total Revenue], DATEADD ( FYCALENDAR_D[Date], -1, YEAR ) )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. Time Intelligence\4.2 Fiscal As Of\Revenue
		lineageTag: 97187602-a5c6-4fc6-b106-ec315c7be1de

	/// Text indicator showing revenue change vs prior year for the current period context; respects Revenue_Stream_D selection via [Revenue (By Stream)].
	measure 'Total Revenue Trend vs PY' =
			VAR CY = [Revenue (By Stream)]
			VAR PY = [Total Revenue PY]
			RETURN
			    IF (
			        ISBLANK ( CY ) || CY = 0,
			        BLANK (),
			        VAR Diff = CY - PY
			        VAR PctChange = DIVIDE ( Diff, PY )
			        VAR Icon =
			            SWITCH (
			                TRUE (),
			                PctChange > 0, UNICHAR ( 9650 ),
			                PctChange < 0, UNICHAR ( 9660 ),
			                UNICHAR ( 9644 )
			            )
			        VAR PctText =
			            IF ( PctChange >= 0, UNICHAR ( 8199 ) & FORMAT ( PctChange, "0.0%" ), FORMAT ( PctChange, "0.0%" ) )
			        RETURN
			            Icon & " " & PctText
			    )
		displayFolder: 1. Revenue\1.1 Total
		lineageTag: c7109e9a-bb67-45db-9168-d8aa677c388a

	/// Gross profit for the same selected period one year prior; respects Revenue_Stream_D selection via [Gross Profit (By Stream)].
	measure 'Total Gross Profit PY' = CALCULATE ( [Gross Profit (By Stream)], SAMEPERIODLASTYEAR ( FYCALENDAR_D[Date] ) )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 3. Gross Profit\3.1 Total
		lineageTag: 22a036a1-8194-4de1-a571-b1ffa371e8d9

	/// Text indicator showing gross profit change vs prior year for the current period context; respects Revenue_Stream_D selection via [Gross Profit (By Stream)].
	measure 'Total Gross Profit Trend vs PY' =
			VAR CY = [Gross Profit (By Stream)]
			VAR PY = [Total Gross Profit PY]
			RETURN
			    IF (
			        ISBLANK ( CY ) || CY = 0,
			        BLANK (),
			        VAR Diff = CY - PY
			        VAR PctChange = DIVIDE ( Diff, PY )
			        VAR Icon =
			            SWITCH (
			                TRUE (),
			                PctChange > 0, UNICHAR ( 9650 ),
			                PctChange < 0, UNICHAR ( 9660 ),
			                UNICHAR ( 9644 )
			            )
			        VAR PctText =
			            IF ( PctChange >= 0, UNICHAR ( 8199 ) & FORMAT ( PctChange, "0.0%" ), FORMAT ( PctChange, "0.0%" ) )
			        RETURN
			            Icon & " " & PctText
			    )
		displayFolder: 3. Gross Profit\3.1 Total
		lineageTag: d708ce1f-38a2-4734-a7ab-f3d77cd7fdf0

	/// UI helper: friendly label for the current customer selection (single, multiple, or all).
	measure 'Selected Customer Name' =
			VAR HasOne = HASONEVALUE ( CUSTOMERS_D[Customer Key] )
			VAR HasAny = ISCROSSFILTERED ( CUSTOMERS_D[Customer Key] )
			RETURN
			    IF (
			        HasAny,
			        IF (
			            HasOne,
			            COALESCE ( SELECTEDVALUE ( CUSTOMERS_D[Customer Name] ), "Selected Customer" ),
			            "Multiple Customers Selected"
			        ),
			        "All Customers (Company Total)"
			    )
		displayFolder: 6. Customer Status\6.0 UI
		lineageTag: 57aede0a-0361-40be-b77d-55543c539cef

	/// Latest month end with non-zero billing/revenue for the current customer selection across all streams (optionally clamped to the financial as-of anchor).
	measure 'Last Billing Date (Any Stream)' =
			VAR Anchor = [As Of Month End (Financials)]
			RETURN
			    CALCULATE (
			        MAX ( FINANCIALS_F[Month End] ),
			        REMOVEFILTERS ( FYCALENDAR_D ),
			        FINANCIALS_F[Revenue Amount] <> 0,
			        IF ( ISBLANK ( Anchor ), TRUE (), FINANCIALS_F[Month End] <= Anchor )
			    )
		formatString: yyyy-mm-dd
		displayFolder: 6. Customer Status\6.1 Helpers
		lineageTag: 24b15676-23f0-4245-b9c9-b011a253cf05

	/// Months between the last billing month and the financial as-of anchor month for the current customer selection.
	measure 'Months Since Last Billing' =
			VAR LastBilling = [Last Billing Date (Any Stream)]
			VAR Anchor = [As Of Month End (Financials)]
			RETURN
			    IF (
			        ISBLANK ( LastBilling ) || ISBLANK ( Anchor ),
			        BLANK (),
			        DATEDIFF ( EOMONTH ( LastBilling, 0 ), EOMONTH ( Anchor, 0 ), MONTH )
			    )
		formatString: #,0
		displayFolder: 6. Customer Status\6.1 Helpers
		lineageTag: 82c8f7aa-2255-4cd0-abf8-120f76637497

	/// Lifecycle status derived from months since last billing (based on the financial as-of anchor month).
	measure 'Customer Lifecycle Status' =
			VAR MonthsInactive = [Months Since Last Billing]
			RETURN
			    SWITCH (
			        TRUE (),
			        ISBLANK ( MonthsInactive ), "No Activity",
			        MonthsInactive < 6, "Active",
			        MonthsInactive < 12, "Dormant (6–11 mo)",
			        "Inactive (12+ mo)"
			    )
		displayFolder: 6. Customer Status\6.1 Helpers
		lineageTag: 0a636fab-7c03-4e61-89e8-393ae1bb657f

	/// Filter helper: returns 1 if the current customer matches the selected lifecycle status in the disconnected Customer Status Selector slicer; else 0.
	measure 'Customer Status' =
			VAR StatusSel = SELECTEDVALUE ( 'UI_Customer Status Selector'[Customer Status], "All" )
			VAR MonthsInactive = [Months Since Last Billing]
			RETURN
			    SWITCH (
			        TRUE (),
			        StatusSel = "All", 1,
			        ISBLANK ( MonthsInactive ), 0,
			        StatusSel = "Active" && MonthsInactive < 6, 1,
			        StatusSel = "Dormant (6–11 mo)" && MonthsInactive >= 6 && MonthsInactive < 12, 1,
			        StatusSel = "Inactive (12+ mo)" && MonthsInactive >= 12, 1,
			        0
			    )
		formatString: #,0
		displayFolder: 6. Customer Status\6.0 UI
		lineageTag: d7e83744-c3ba-4875-a073-d88093a98319

	/// Count of active service contract years for the current filter context.
	measure 'Active Contracts' = CALCULATE ( COUNTROWS ( SERVCONTRACTS_D ), SERVCONTRACTS_D[IsActiveContractYear] = TRUE () )
		formatString: #,0
		displayFolder: 6. Customer Status\6.2 Contract
		lineageTag: 27bfcb39-5306-4fa8-87d0-18bfb1459a19

	/// Count of active projects for the current filter context.
	measure 'Active Projects' = CALCULATE ( COUNTROWS ( PROJECTS_D ), PROJECTS_D[Inactive] = FALSE () )
		formatString: #,0
		displayFolder: 6. Customer Status\6.3 Projects
		lineageTag: 8d740050-a1fc-4596-8d4e-f65a246e5d39

	/// Earliest month end with non-zero service contract revenue in the current filter context.
	measure 'First Contract Billing Date' = CALCULATE ( MIN ( SERVCONTRACTS_Financials_F[Month End] ), SERVCONTRACTS_Financials_F[Revenue Amount] <> 0 )
		formatString: yyyy-mm-dd
		displayFolder: 6. Customer Status\6.2 Contract
		lineageTag: 1ed330eb-ec1c-44fe-98f8-9afee6100413

	/// Latest month end with non-zero service contract revenue in the current filter context.
	measure 'Last Contract Billing Date' = CALCULATE ( MAX ( SERVCONTRACTS_Financials_F[Month End] ), SERVCONTRACTS_Financials_F[Revenue Amount] <> 0 )
		formatString: yyyy-mm-dd
		displayFolder: 6. Customer Status\6.2 Contract
		lineageTag: 1238b32b-b826-43d6-acfa-368e751c0c76

	/// Inclusive count of months between first and last service contract billing months for the current filter context.
	measure 'Contract Billing Period (Months Inclusive)' =
			VAR FirstDt = [First Contract Billing Date]
			VAR LastDt = [Last Contract Billing Date]
			RETURN
			    IF (
			        ISBLANK ( FirstDt ) || ISBLANK ( LastDt ),
			        BLANK (),
			        DATEDIFF ( EOMONTH ( FirstDt, -1 ) + 1, EOMONTH ( LastDt, 0 ) + 1, MONTH )
			    )
		formatString: #,0
		displayFolder: 6. Customer Status\6.2 Contract
		lineageTag: 53b5ecc1-d555-4d6a-ba72-2aa3730edfbc

	/// Customer rank by lifetime total revenue (all customers, ignoring customer filters).
	measure 'Customer Revenue Rank (All Time)' = RANKX ( ALL ( CUSTOMERS_D ), [Total Revenue], , DESC, Dense )
		formatString: #,0
		displayFolder: 6. Customer Status\6.4 Profile
		lineageTag: c7579629-bbd2-42a8-b433-5c4baff36c3c

	/// Formatted rank string for customer profile display (e.g., '#12 of 1,234').
	measure 'Customer Rank Context String' =
			VAR RankVal = [Customer Revenue Rank (All Time)]
			VAR TotalCustomers =
			    CALCULATE ( COUNTROWS ( CUSTOMERS_D ), FILTER ( ALL ( CUSTOMERS_D ), [Total Revenue] > 0 ) )
			RETURN
			    IF ( ISBLANK ( [Total Revenue] ), "No Revenue", "#" & FORMAT ( RankVal, "#,0" ) & " of " & FORMAT ( TotalCustomers, "#,0" ) )
		displayFolder: 6. Customer Status\6.4 Profile
		lineageTag: 2d899a3e-ebd3-4df8-aecc-095508917d5c

	/// Text value for the selected UI_CustomerProfileRows metric, formatted for display in the customer profile visual.
	measure 'Customer Profile Metric Value' =
			VAR Metric = SELECTEDVALUE ( UI_CustomerProfileRows[Metric Name] )
			VAR Result =
			    SWITCH (
			        Metric,
			        "Lifecycle Status", [Customer Lifecycle Status],
			        "Last Billing Date", FORMAT ( [Last Billing Date (Any Stream)], "MMM d, yyyy" ),
			        "Active Contracts", FORMAT ( [Active Contracts], "#,0" ),
			        "Active Projects", FORMAT ( [Active Projects], "#,0" ),
			        "Lifetime Revenue", FORMAT ( [Total Revenue], "$#,0" ),
			        "Lifetime GP", FORMAT ( [Total Gross Profit], "$#,0" ),
			        "Lifetime GP %", FORMAT ( [Total GP %], "0.0%" ),
			        "Revenue Rank", [Customer Rank Context String]
			    )
			RETURN
			    IF ( ISBLANK ( Result ), "--", Result )
		displayFolder: 6. Customer Status\6.4 Profile
		lineageTag: fe777dba-8270-4de9-acdc-ad8db94a8b50

	/// Gross profit percent for service contracts (completed months only).
	measure 'Service Contract Gross Profit %' = DIVIDE ( [Service Contract Gross Profit], [Service Contract Revenue] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3. Gross Profit\3.2 Streams
		lineageTag: 792a65d1-23ec-4679-b008-1beff3093896

	/// Alias for the NRR waterfall step value used by CRR v05 visuals.
	measure 'NRR Waterfall Value' = [NRR Waterfall Value (R12M As Of)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.5 Waterfall
		lineageTag: 05b4cea7-3fa6-4130-8c2e-67e5d2ea8ea4

	/// Alias for the service-contract retention category used in CRR visuals (retention metrics are SC-only in this model).
	measure 'Customer Retention Category (R12M)' = [Customer Retention Category (SC) (R12M As Of)]
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.6 Classification
		lineageTag: aa2da020-5bb3-49cc-b13d-da3ed6e54f40

	/// Simplified prior-year revenue for the current period context; respects Revenue_Stream_D selection via [Revenue (By Stream)].
	measure 'Revenue PY (Dynamic)' = CALCULATE ( [Revenue (By Stream)], DATEADD ( FYCALENDAR_D[Date], -1, YEAR ) )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 1. Revenue\1.3 By Stream
		lineageTag: 93ddbfd1-befb-4a24-9995-32612207d8e7

	/// Markdown explanation used by the report for NRR logic (SC-only retention in this model).
	measure 'NRR Logic Explanation.MD' = "# Net Revenue Retention (NRR) Logic (Service Contracts Only)\n\nNRR uses an **as-of anchor month end** (see [As Of Month End (SC)]).\n\nIt compares two rolling windows:\n1. **CY (R12M)**: 12 months ending at the anchor.\n2. **PY (R12M)**: the prior 12 months.\n\nOnly customers with **PY revenue > 0** are included in the retention base.\n- **Churn**: PY > 0 and CY = 0\n- **Contraction**: PY > 0 and 0 < CY < PY\n- **Upsell**: PY > 0 and CY > PY\n- **New**: PY = 0 and CY > 0 (excluded from base)\n\nThis model clamps anchors to completed months to avoid partial-month distortion."
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.0 Documentation
		lineageTag: dbe430e0-ef2b-4696-9310-ea63b231d176

	/// Count of NPS survey responses in the current filter context.
	measure 'NPS Response Count' = COUNTROWS ( NPS_F )
		formatString: #,0
		displayFolder: 6. Customer Experience\6.1 NPS
		lineageTag: 3fcf8d5a-3dee-4fb0-97b0-58209fad8658

	/// Average NPS 1-10 score in the current filter context.
	measure 'Avg NPS Rating' = AVERAGE ( NPS_F[1-10 Score] )
		formatString: 0.0;-0.0;0.0
		displayFolder: 6. Customer Experience\6.1 NPS
		lineageTag: 1bf7aa37-6585-4710-9aa8-57cecaaa0dc6

	/// Count of NPS promoters (score 9-10) in the current filter context.
	measure 'Promoters Count' = CALCULATE ( COUNTROWS ( NPS_F ), NPS_F[1-10 Score] >= 9 )
		formatString: #,0
		displayFolder: 6. Customer Experience\6.1 NPS
		lineageTag: 13a8fc6f-2ffc-433b-b471-1fc11cba4013

	/// Count of NPS detractors (score 0-6) in the current filter context.
	measure 'Detractors Count' = CALCULATE ( COUNTROWS ( NPS_F ), NPS_F[1-10 Score] <= 6 )
		formatString: #,0
		displayFolder: 6. Customer Experience\6.1 NPS
		lineageTag: 23a8cd0e-c6a0-4557-8e2a-e30d872066e0

	/// Net Promoter Score (0-100 scale) computed as (Promoters - Detractors) / Total * 100.
	measure 'Net Promoter Score' =
			VAR P = [Promoters Count]
			VAR D = [Detractors Count]
			VAR Total = [NPS Response Count]
			RETURN
			    IF ( Total > 0, DIVIDE ( P - D, Total ) * 100 )
		formatString: 0.0;-0.0;0.0
		displayFolder: 6. Customer Experience\6.1 NPS
		lineageTag: 2d89b227-fdb1-46f5-bd09-941916e7b23d

	/// Rolling 12-month Net Promoter Score using an anchor based on visible date context and last NPS data date.
	measure 'Net Promoter Score (R12M)' =
			VAR AxisMax = MAX ( FYCALENDAR_D[Date] )
			VAR LastData = [Last NPS Date]
			VAR AxisMonthEnd = EOMONTH ( AxisMax, 0 )
			VAR LastDataMonthEnd = EOMONTH ( LastData, 0 )
			VAR AnchorDate = IF ( ISBLANK ( AxisMax ), LastData, MIN ( AxisMax, LastData ) )
			RETURN
			    IF (
			        ISBLANK ( LastData ) || ISBLANK ( AnchorDate ),
			        BLANK (),
			        IF (
			            ISINSCOPE ( FYCALENDAR_D[Date] )
			                && NOT ISBLANK ( AxisMax )
			                && AxisMonthEnd > LastDataMonthEnd,
			            BLANK (),
			            CALCULATE (
			                [Net Promoter Score],
			                DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ),
			                REMOVEFILTERS ( FYCALENDAR_D )
			            )
			        )
			    )
		formatString: 0.0;-0.0;0.0
		displayFolder: 6. Customer Experience\6.1 NPS\R12M
		lineageTag: 7406cf94-6984-4c80-ac02-b9ac37df7042

	/// Prior-year rolling 12-month Net Promoter Score aligned to the R12M anchor.
	measure 'Net Promoter Score PY (R12M)' =
			VAR AxisMax = MAX ( FYCALENDAR_D[Date] )
			VAR LastData = [Last NPS Date]
			VAR AxisMonthEnd = EOMONTH ( AxisMax, 0 )
			VAR LastDataMonthEnd = EOMONTH ( LastData, 0 )
			VAR AnchorDate = IF ( ISBLANK ( AxisMax ), LastData, MIN ( AxisMax, LastData ) )
			VAR AnchorPY = EDATE ( AnchorDate, -12 )
			RETURN
			    IF (
			        ISBLANK ( LastData ) || ISBLANK ( AnchorDate ),
			        BLANK (),
			        IF (
			            ISINSCOPE ( FYCALENDAR_D[Date] )
			                && NOT ISBLANK ( AxisMax )
			                && AxisMonthEnd > LastDataMonthEnd,
			            BLANK (),
			            CALCULATE (
			                [Net Promoter Score],
			                DATESINPERIOD ( FYCALENDAR_D[Date], AnchorPY, -12, MONTH ),
			                REMOVEFILTERS ( FYCALENDAR_D )
			            )
			        )
			    )
		formatString: 0.0;-0.0;0.0
		displayFolder: 6. Customer Experience\6.1 NPS\R12M
		lineageTag: a3af3dec-b207-46dc-8caa-aeb87fb4ecb5

	/// Text indicator showing rolling-12-month NPS change vs prior-year rolling-12-month NPS (arrow + delta).
	measure 'Net Promoter Score Trend vs PY' =
			VAR AxisMax = MAX ( FYCALENDAR_D[Date] )
			VAR LastData = [Last NPS Date]
			VAR AxisMonthEnd = EOMONTH ( AxisMax, 0 )
			VAR LastDataMonthEnd = EOMONTH ( LastData, 0 )
			RETURN
			    IF (
			        ISBLANK ( LastData ),
			        BLANK (),
			        IF (
			            ISINSCOPE ( FYCALENDAR_D[Date] )
			                && NOT ISBLANK ( AxisMax )
			                && AxisMonthEnd > LastDataMonthEnd,
			            BLANK (),
			            VAR CY = [Net Promoter Score (R12M)]
			            VAR PY = [Net Promoter Score PY (R12M)]
			            RETURN
			                IF (
			                    ISBLANK ( CY ) || CY = 0 || ISBLANK ( PY ) || PY = 0,
			                    BLANK (),
			                    VAR Diff = CY - PY
			                    VAR Icon =
			                        SWITCH (
			                            TRUE (),
			                            Diff > 0, UNICHAR ( 9650 ),
			                            Diff < 0, UNICHAR ( 9660 ),
			                            UNICHAR ( 9644 )
			                        )
			                    VAR Txt =
			                        IF ( Diff >= 0, UNICHAR ( 8199 ) & FORMAT ( Diff, "0.0" ), FORMAT ( Diff, "0.0" ) )
			                    RETURN
			                        Icon & " " & Txt
			                )
			        )
			    )
		displayFolder: 6. Customer Experience\6.1 NPS\R12M
		lineageTag: 124a4aa5-0446-43ed-a477-25ad43873748

	/// Percent of responses marked First Time Fix = Yes.
	measure 'First Time Fix Rate' =
			VAR YesCt = CALCULATE ( COUNTROWS ( NPS_F ), NPS_F[First Time Fix] = "Yes" )
			VAR NoCt = CALCULATE ( COUNTROWS ( NPS_F ), NPS_F[First Time Fix] = "No" )
			RETURN
			    DIVIDE ( YesCt, YesCt + NoCt )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 6. Customer Experience\6.2 Service Quality
		lineageTag: 64f13f0e-d94a-49b4-bd1e-e15aa86daa46

	/// Percent of responses marked Prompt and On Time = Yes.
	measure 'Prompt and On Time %' =
			VAR YesCt = CALCULATE ( COUNTROWS ( NPS_F ), NPS_F[Prompt and On Time] = "Yes" )
			VAR NoCt = CALCULATE ( COUNTROWS ( NPS_F ), NPS_F[Prompt and On Time] = "No" )
			RETURN
			    DIVIDE ( YesCt, YesCt + NoCt )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 6. Customer Experience\6.2 Service Quality
		lineageTag: d5dbb1ae-bd1e-48ed-854e-e47da5527c82

	/// Placeholder: spend-per-maintenance metric not yet modeled in this semantic model.
	measure 'Project Spend per Maintenance $ (TTM)' = BLANK()
		formatString: 0.00;-0.00;0.00
		displayFolder: 9. Not Implemented\9.2 Operations
		lineageTag: ebd79675-e12a-4dbb-be09-1402aabf2a44

	/// Placeholder: spend-per-maintenance metric not yet modeled in this semantic model.
	measure 'T&M Spend per Maintenance $ (TTM)' = BLANK()
		formatString: 0.00;-0.00;0.00
		displayFolder: 9. Not Implemented\9.2 Operations
		lineageTag: 7a6a6b3e-bd94-4123-bec6-214c6b95c89b

	/// Placeholder: snapshot KPI not yet modeled in this semantic model.
	measure 'Total Project Spend per Total Maintenance $ (Snapshot)' = BLANK()
		formatString: 0.00;-0.00;0.00
		displayFolder: 9. Not Implemented\9.2 Operations
		lineageTag: 22291a47-8401-493b-9b4e-5b7e2fbb5681

	/// Placeholder: snapshot KPI not yet modeled in this semantic model.
	measure 'Total T&M Spend per Total Maintenance $ (Snapshot)' = BLANK()
		formatString: 0.00;-0.00;0.00
		displayFolder: 9. Not Implemented\9.2 Operations
		lineageTag: 4b38c170-317a-42c0-ba84-2182fff28c91

	/// Helper: last available NPS completed date in the model (ignores filters), capped at the current month end (and calendar max) to prevent bad future-dated rows from shifting anchors.
	measure 'Last NPS Date' =
			VAR RawLast =
			    CALCULATE ( MAX ( NPS_F[SERVICE CALL COMPLETED DATE] ), REMOVEFILTERS () )
			VAR TodayMonthEnd = EOMONTH ( TODAY (), 0 )
			VAR CalendarMax = CALCULATE ( MAX ( FYCALENDAR_D[Date] ), REMOVEFILTERS ( FYCALENDAR_D ) )
			VAR Cap = MIN ( TodayMonthEnd, CalendarMax )
			RETURN
			    IF ( ISBLANK ( RawLast ), BLANK (), MIN ( RawLast, Cap ) )
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: 6. Customer Experience\6.0 Helpers
		lineageTag: db38990d-fd2d-4ee7-ada0-790762aaff8f

	/// Debug: start date of the rolling 12-month NPS window based on the visible date context and last NPS data date.
	measure 'Debug - NPS R12M Start Date' =
			VAR MaxVisible = MAX ( FYCALENDAR_D[Date] )
			VAR LastData = [Last NPS Date]
			VAR AnchorDate = MIN ( MaxVisible, LastData )
			RETURN
			    CALCULATE ( MIN ( FYCALENDAR_D[Date] ), DATESINPERIOD ( FYCALENDAR_D[Date], AnchorDate, -12, MONTH ) )
		formatString: yyyy-mm-dd
		displayFolder: 6. Customer Experience\6.0 Helpers
		lineageTag: 48d93173-a159-4d4f-b9aa-71d9f2c5ab1d

	/// SVG sparkline for Net Revenue Retention % (R12M As Of), anchored to [As Of Month End (SC)] over the last 12 month-ends.
	measure 'NRR Sparkline (SVG)' =
			VAR W = 340
			VAR H = 70
			VAR Pad = 6
			VAR Stroke = "white"
			VAR Fill = "none"
			VAR Anchor = [As Of Month End (SC)]
			VAR Dates0 =
			    CALCULATETABLE (
			        VALUES ( FYCALENDAR_D[Date] ),
			        REMOVEFILTERS ( FYCALENDAR_D ),
			        FYCALENDAR_D[Date] <= Anchor,
			        FYCALENDAR_D[Date] > EDATE ( Anchor, -12 ),
			        FYCALENDAR_D[Date] = EOMONTH ( FYCALENDAR_D[Date], 0 )
			    )
			VAR Dates = TOPN ( 12, Dates0, FYCALENDAR_D[Date], ASC )
			VAR Series =
			    ADDCOLUMNS (
			        Dates,
			        "__i", RANKX ( Dates, FYCALENDAR_D[Date],, ASC, Dense ),
			        "__y", CALCULATE ( [Net Revenue Retention % (R12M As Of)] )
			    )
			VAR N = COUNTROWS ( Series )
			VAR YMin = MINX ( Series, [__y] )
			VAR YMax = MAXX ( Series, [__y] )
			VAR Den = IF ( YMax - YMin = 0, 1, YMax - YMin )
			VAR Points =
			    CONCATENATEX (
			        Series,
			        VAR i = [__i]
			        VAR xRaw = IF ( N <= 1, W / 2, Pad + ( i - 1 ) * ( ( W - 2 * Pad ) / ( N - 1 ) ) )
			        VAR yRaw = Pad + ( H - 2 * Pad ) * ( 1 - DIVIDE ( [__y] - YMin, Den, 0.5 ) )
			        VAR x = SUBSTITUTE ( FORMAT ( xRaw, "0.0" ), ",", "." )
			        VAR y = SUBSTITUTE ( FORMAT ( yRaw, "0.0" ), ",", "." )
			        RETURN x & "," & y,
			        " "
			    )
			VAR LastRow = TOPN ( 1, Series, FYCALENDAR_D[Date], DESC )
			VAR LastXRaw =
			    MAXX (
			        LastRow,
			        VAR i = [__i]
			        RETURN IF ( N <= 1, W / 2, Pad + ( i - 1 ) * ( ( W - 2 * Pad ) / ( N - 1 ) ) )
			    )
			VAR LastYRaw =
			    MAXX (
			        LastRow,
			        Pad + ( H - 2 * Pad ) * ( 1 - DIVIDE ( [__y] - YMin, Den, 0.5 ) )
			    )
			VAR LastX = SUBSTITUTE ( FORMAT ( LastXRaw, "0.0" ), ",", "." )
			VAR LastY = SUBSTITUTE ( FORMAT ( LastYRaw, "0.0" ), ",", "." )
			VAR Svg =
			    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 "
			        & W
			        & " "
			        & H
			        & "'>"
			        & "<polyline fill='"
			        & Fill
			        & "' stroke='"
			        & Stroke
			        & "' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' points='"
			        & Points
			        & "'/>"
			        & "<circle cx='"
			        & LastX
			        & "' cy='"
			        & LastY
			        & "' r='2.5' fill='"
			        & Stroke
			        & "'/>"
			        & "</svg>"
			VAR Enc0 = SUBSTITUTE ( Svg, "%", "%25" )
			VAR Enc1 = SUBSTITUTE ( Enc0, "<", "%3C" )
			VAR Enc2 = SUBSTITUTE ( Enc1, ">", "%3E" )
			VAR Enc3 = SUBSTITUTE ( Enc2, " ", "%20" )
			VAR Enc4 = SUBSTITUTE ( Enc3, "'", "%27" )
			RETURN
			    IF ( ISBLANK ( Anchor ) || N = 0, BLANK (), "data:image/svg+xml;utf8," & Enc4 )
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.7 Sparklines
		lineageTag: 8c1b8858-38c2-4a5b-a61d-8a9e768b6084
		dataCategory: Image URL

	/// SVG sparkline for Gross Revenue Retention % (R12M As Of), anchored to [As Of Month End (SC)] over the last 12 month-ends.
	measure 'GRR Sparkline (SVG)' =
			VAR W = 340
			VAR H = 70
			VAR Pad = 6
			VAR Stroke = "white"
			VAR Fill = "none"
			VAR Anchor = [As Of Month End (SC)]
			VAR Dates0 =
			    CALCULATETABLE (
			        VALUES ( FYCALENDAR_D[Date] ),
			        REMOVEFILTERS ( FYCALENDAR_D ),
			        FYCALENDAR_D[Date] <= Anchor,
			        FYCALENDAR_D[Date] > EDATE ( Anchor, -12 ),
			        FYCALENDAR_D[Date] = EOMONTH ( FYCALENDAR_D[Date], 0 )
			    )
			VAR Dates = TOPN ( 12, Dates0, FYCALENDAR_D[Date], ASC )
			VAR Series =
			    ADDCOLUMNS (
			        Dates,
			        "__i", RANKX ( Dates, FYCALENDAR_D[Date],, ASC, Dense ),
			        "__y", CALCULATE ( [Gross Revenue Retention % (R12M As Of)] )
			    )
			VAR N = COUNTROWS ( Series )
			VAR YMin = MINX ( Series, [__y] )
			VAR YMax = MAXX ( Series, [__y] )
			VAR Den = IF ( YMax - YMin = 0, 1, YMax - YMin )
			VAR Points =
			    CONCATENATEX (
			        Series,
			        VAR i = [__i]
			        VAR xRaw = IF ( N <= 1, W / 2, Pad + ( i - 1 ) * ( ( W - 2 * Pad ) / ( N - 1 ) ) )
			        VAR yRaw = Pad + ( H - 2 * Pad ) * ( 1 - DIVIDE ( [__y] - YMin, Den, 0.5 ) )
			        VAR x = SUBSTITUTE ( FORMAT ( xRaw, "0.0" ), ",", "." )
			        VAR y = SUBSTITUTE ( FORMAT ( yRaw, "0.0" ), ",", "." )
			        RETURN x & "," & y,
			        " "
			    )
			VAR LastRow = TOPN ( 1, Series, FYCALENDAR_D[Date], DESC )
			VAR LastXRaw =
			    MAXX (
			        LastRow,
			        VAR i = [__i]
			        RETURN IF ( N <= 1, W / 2, Pad + ( i - 1 ) * ( ( W - 2 * Pad ) / ( N - 1 ) ) )
			    )
			VAR LastYRaw =
			    MAXX (
			        LastRow,
			        Pad + ( H - 2 * Pad ) * ( 1 - DIVIDE ( [__y] - YMin, Den, 0.5 ) )
			    )
			VAR LastX = SUBSTITUTE ( FORMAT ( LastXRaw, "0.0" ), ",", "." )
			VAR LastY = SUBSTITUTE ( FORMAT ( LastYRaw, "0.0" ), ",", "." )
			VAR Svg =
			    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 "
			        & W
			        & " "
			        & H
			        & "'>"
			        & "<polyline fill='"
			        & Fill
			        & "' stroke='"
			        & Stroke
			        & "' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' points='"
			        & Points
			        & "'/>"
			        & "<circle cx='"
			        & LastX
			        & "' cy='"
			        & LastY
			        & "' r='2.5' fill='"
			        & Stroke
			        & "'/>"
			        & "</svg>"
			VAR Enc0 = SUBSTITUTE ( Svg, "%", "%25" )
			VAR Enc1 = SUBSTITUTE ( Enc0, "<", "%3C" )
			VAR Enc2 = SUBSTITUTE ( Enc1, ">", "%3E" )
			VAR Enc3 = SUBSTITUTE ( Enc2, " ", "%20" )
			VAR Enc4 = SUBSTITUTE ( Enc3, "'", "%27" )
			RETURN
			    IF ( ISBLANK ( Anchor ) || N = 0, BLANK (), "data:image/svg+xml;utf8," & Enc4 )
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.7 Sparklines
		lineageTag: 8f02d1ce-3758-4c0e-a5b7-c8858e9ca14a
		dataCategory: Image URL

	/// SVG sparkline for Logo Retention % (SC) (R12M As Of), anchored to [As Of Month End (SC)] over the last 12 month-ends.
	measure 'Logo Sparkline (SVG)' =
			VAR W = 340
			VAR H = 70
			VAR Pad = 6
			VAR Stroke = "white"
			VAR Fill = "none"
			VAR Anchor = [As Of Month End (SC)]
			VAR Dates0 =
			    CALCULATETABLE (
			        VALUES ( FYCALENDAR_D[Date] ),
			        REMOVEFILTERS ( FYCALENDAR_D ),
			        FYCALENDAR_D[Date] <= Anchor,
			        FYCALENDAR_D[Date] > EDATE ( Anchor, -12 ),
			        FYCALENDAR_D[Date] = EOMONTH ( FYCALENDAR_D[Date], 0 )
			    )
			VAR Dates = TOPN ( 12, Dates0, FYCALENDAR_D[Date], ASC )
			VAR Series =
			    ADDCOLUMNS (
			        Dates,
			        "__i", RANKX ( Dates, FYCALENDAR_D[Date],, ASC, Dense ),
			        "__y", CALCULATE ( [Logo Retention % (SC) (R12M As Of)] )
			    )
			VAR N = COUNTROWS ( Series )
			VAR YMin = MINX ( Series, [__y] )
			VAR YMax = MAXX ( Series, [__y] )
			VAR Den = IF ( YMax - YMin = 0, 1, YMax - YMin )
			VAR Points =
			    CONCATENATEX (
			        Series,
			        VAR i = [__i]
			        VAR xRaw = IF ( N <= 1, W / 2, Pad + ( i - 1 ) * ( ( W - 2 * Pad ) / ( N - 1 ) ) )
			        VAR yRaw = Pad + ( H - 2 * Pad ) * ( 1 - DIVIDE ( [__y] - YMin, Den, 0.5 ) )
			        VAR x = SUBSTITUTE ( FORMAT ( xRaw, "0.0" ), ",", "." )
			        VAR y = SUBSTITUTE ( FORMAT ( yRaw, "0.0" ), ",", "." )
			        RETURN x & "," & y,
			        " "
			    )
			VAR LastRow = TOPN ( 1, Series, FYCALENDAR_D[Date], DESC )
			VAR LastXRaw =
			    MAXX (
			        LastRow,
			        VAR i = [__i]
			        RETURN IF ( N <= 1, W / 2, Pad + ( i - 1 ) * ( ( W - 2 * Pad ) / ( N - 1 ) ) )
			    )
			VAR LastYRaw =
			    MAXX (
			        LastRow,
			        Pad + ( H - 2 * Pad ) * ( 1 - DIVIDE ( [__y] - YMin, Den, 0.5 ) )
			    )
			VAR LastX = SUBSTITUTE ( FORMAT ( LastXRaw, "0.0" ), ",", "." )
			VAR LastY = SUBSTITUTE ( FORMAT ( LastYRaw, "0.0" ), ",", "." )
			VAR Svg =
			    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 "
			        & W
			        & " "
			        & H
			        & "'>"
			        & "<polyline fill='"
			        & Fill
			        & "' stroke='"
			        & Stroke
			        & "' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' points='"
			        & Points
			        & "'/>"
			        & "<circle cx='"
			        & LastX
			        & "' cy='"
			        & LastY
			        & "' r='2.5' fill='"
			        & Stroke
			        & "'/>"
			        & "</svg>"
			VAR Enc0 = SUBSTITUTE ( Svg, "%", "%25" )
			VAR Enc1 = SUBSTITUTE ( Enc0, "<", "%3C" )
			VAR Enc2 = SUBSTITUTE ( Enc1, ">", "%3E" )
			VAR Enc3 = SUBSTITUTE ( Enc2, " ", "%20" )
			VAR Enc4 = SUBSTITUTE ( Enc3, "'", "%27" )
			RETURN
			    IF ( ISBLANK ( Anchor ) || N = 0, BLANK (), "data:image/svg+xml;utf8," & Enc4 )
		displayFolder: 5. Retention\5.4 R12M As Of\5.4.7 Sparklines
		lineageTag: 1db4a1f4-53ab-41d4-b9b8-85addb952be8
		dataCategory: Image URL

	/// GL revenue budget from BUDGET_F (sign-flipped), filtered to revenue accounts and completed months.
	measure 'GL Budget Revenue' =
			CALCULATE(
			    -SUM(BUDGET_F[BUDGETAMT]),
			    GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			    FYCALENDAR_D[Is Completed Month] = TRUE
			)
		formatString: $#,0.00;($#,0.00);$#,0.00
		displayFolder: 1. Revenue\1.1 GL
		lineageTag: 8fcff759-6807-43f4-b410-63468b6aeedd

	/// P&L actual amount for the current UI_P&L Structure row, Year-to-Date through the selected month-end (clamped to last completed month). Returns section totals when matrix is collapsed to Section.
	measure 'P&L Amount (YTD)' =
			VAR SelectedMaxDate = MAX ( FYCALENDAR_D[Date] )
			VAR LastCompletedMonthEnd =
			    CALCULATE(
			        MAX ( FYCALENDAR_D[Date] ),
			        FILTER ( ALL ( FYCALENDAR_D ), FYCALENDAR_D[Is Completed Month] = TRUE && FYCALENDAR_D[Date] = EOMONTH ( FYCALENDAR_D[Date], 0 ) )
			    )
			VAR SelectedMonthEnd = IF ( ISBLANK ( SelectedMaxDate ), LastCompletedMonthEnd, EOMONTH ( SelectedMaxDate, 0 ) )
			VAR AnchorMonthEnd = IF ( SelectedMonthEnd > LastCompletedMonthEnd, LastCompletedMonthEnd, SelectedMonthEnd )
			VAR StartFY =
			    CALCULATE (
			        MAX ( FYCALENDAR_D[Fiscal Start Of Year] ),
			        FILTER ( ALL ( FYCALENDAR_D ), FYCALENDAR_D[Date] = AnchorMonthEnd )
			    )
			VAR dYTD = DATESBETWEEN ( FYCALENDAR_D[Date], StartFY, AnchorMonthEnd )
			VAR HasLine = ISINSCOPE ( 'UI_P&L Structure'[Line Item] )
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			RETURN
			    IF (
			        HasLine,
			        CALCULATE ( [P&L Amount (YTD) (Line)], dYTD ),
			        IF (
			            ISBLANK ( Section ),
			            BLANK (),
			            SUMX (
			                FILTER (
			                    ALL ( 'UI_P&L Structure' ),
			                    'UI_P&L Structure'[Section] = Section
			                        && 'UI_P&L Structure'[IsSubtotal] = FALSE
			                ),
			                CALCULATE ( [P&L Amount (YTD) (Line)], dYTD )
			            )
			        )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 11dc118d-828e-4425-8034-45e93ec2574d

	/// P&L prior-year amount for the current UI_P&L Structure row, aligned to the YTD window through the selected month-end (clamped to last completed month). Returns section totals when matrix is collapsed to Section.
	measure 'P&L Amount PY (YTD)' =
			VAR SelectedMaxDate = MAX ( FYCALENDAR_D[Date] )
			VAR LastCompletedMonthEnd =
			    CALCULATE(
			        MAX ( FYCALENDAR_D[Date] ),
			        FILTER ( ALL ( FYCALENDAR_D ), FYCALENDAR_D[Is Completed Month] = TRUE && FYCALENDAR_D[Date] = EOMONTH ( FYCALENDAR_D[Date], 0 ) )
			    )
			VAR SelectedMonthEnd = IF ( ISBLANK ( SelectedMaxDate ), LastCompletedMonthEnd, EOMONTH ( SelectedMaxDate, 0 ) )
			VAR AnchorMonthEnd = IF ( SelectedMonthEnd > LastCompletedMonthEnd, LastCompletedMonthEnd, SelectedMonthEnd )
			VAR AnchorMonthEndPY = EDATE ( AnchorMonthEnd, -12 )
			VAR StartFY_PY =
			    CALCULATE (
			        MAX ( FYCALENDAR_D[Fiscal Start Of Year] ),
			        FILTER ( ALL ( FYCALENDAR_D ), FYCALENDAR_D[Date] = AnchorMonthEndPY )
			    )
			VAR dPY = DATESBETWEEN ( FYCALENDAR_D[Date], StartFY_PY, AnchorMonthEndPY )
			VAR HasLine = ISINSCOPE ( 'UI_P&L Structure'[Line Item] )
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			RETURN
			    IF (
			        HasLine,
			        CALCULATE ( [P&L Amount PY (YTD) (Line)], dPY ),
			        IF (
			            ISBLANK ( Section ),
			            BLANK (),
			            SUMX (
			                FILTER (
			                    ALL ( 'UI_P&L Structure' ),
			                    'UI_P&L Structure'[Section] = Section
			                        && 'UI_P&L Structure'[IsSubtotal] = FALSE
			                ),
			                CALCULATE ( [P&L Amount PY (YTD) (Line)], dPY )
			            )
			        )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 994d28a2-2f83-4e69-8b51-f3dee6c3660e

	/// P&L budget amount for the current UI_P&L Structure row, Year-to-Date through the selected month-end (clamped to last completed month). Returns section totals when matrix is collapsed to Section.
	measure 'P&L Budget Amount (YTD)' =
			VAR SelectedMaxDate = MAX ( FYCALENDAR_D[Date] )
			VAR LastCompletedMonthEnd =
			    CALCULATE(
			        MAX ( FYCALENDAR_D[Date] ),
			        FILTER ( ALL ( FYCALENDAR_D ), FYCALENDAR_D[Is Completed Month] = TRUE && FYCALENDAR_D[Date] = EOMONTH ( FYCALENDAR_D[Date], 0 ) )
			    )
			VAR SelectedMonthEnd = IF ( ISBLANK ( SelectedMaxDate ), LastCompletedMonthEnd, EOMONTH ( SelectedMaxDate, 0 ) )
			VAR AnchorMonthEnd = IF ( SelectedMonthEnd > LastCompletedMonthEnd, LastCompletedMonthEnd, SelectedMonthEnd )
			VAR StartFY =
			    CALCULATE (
			        MAX ( FYCALENDAR_D[Fiscal Start Of Year] ),
			        FILTER ( ALL ( FYCALENDAR_D ), FYCALENDAR_D[Date] = AnchorMonthEnd )
			    )
			VAR dYTD = DATESBETWEEN ( FYCALENDAR_D[Date], StartFY, AnchorMonthEnd )
			VAR HasLine = ISINSCOPE ( 'UI_P&L Structure'[Line Item] )
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			RETURN
			    IF (
			        HasLine,
			        CALCULATE ( [P&L Budget Amount (YTD) (Line)], dYTD ),
			        IF (
			            ISBLANK ( Section ),
			            BLANK (),
			            SUMX (
			                FILTER (
			                    ALL ( 'UI_P&L Structure' ),
			                    'UI_P&L Structure'[Section] = Section
			                        && 'UI_P&L Structure'[IsSubtotal] = FALSE
			                ),
			                CALCULATE ( [P&L Budget Amount (YTD) (Line)], dYTD )
			            )
			        )
			    )
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 5204b83b-4038-408a-815c-97c52429b27f

	/// P&L actual percent of Total Revenue for the current UI_P&L Structure row, Year-to-Date through the selected month-end (clamped to last completed month).
	measure 'P&L % of Revenue (YTD)' =
			VAR TotalRevenueYTD =
			    CALCULATE (
			        [P&L Amount (YTD)],
			        REMOVEFILTERS ( 'UI_P&L Structure' ),
			        KEEPFILTERS ( 'UI_P&L Structure'[Section] = "REVENUE" )
			    )
			RETURN
			    DIVIDE ( [P&L Amount (YTD)], TotalRevenueYTD )
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 87725954-0669-4e60-818b-9fa110239f1d

	/// P&L prior-year percent of Total Revenue for the current UI_P&L Structure row, aligned to the YTD window through the selected month-end (clamped to last completed month).
	measure 'P&L % of Revenue PY (YTD)' =
			VAR TotalRevenueYTD =
			    CALCULATE (
			        [P&L Amount PY (YTD)],
			        REMOVEFILTERS ( 'UI_P&L Structure' ),
			        KEEPFILTERS ( 'UI_P&L Structure'[Section] = "REVENUE" )
			    )
			RETURN
			    DIVIDE ( [P&L Amount PY (YTD)], TotalRevenueYTD )
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 0aaf9280-ecdf-48e1-98a9-645eeca6ae69

	/// P&L budget percent of Total Revenue for the current UI_P&L Structure row, Year-to-Date through the selected month-end (clamped to last completed month).
	measure 'P&L % of Revenue Budget (YTD)' =
			VAR TotalRevenueYTD =
			    CALCULATE (
			        [P&L Budget Amount (YTD)],
			        REMOVEFILTERS ( 'UI_P&L Structure' ),
			        KEEPFILTERS ( 'UI_P&L Structure'[Section] = "REVENUE" )
			    )
			RETURN
			    DIVIDE ( [P&L Budget Amount (YTD)], TotalRevenueYTD )
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 4c40f858-15a0-4224-80df-a45fd5443c09

	/// P&L actual variance vs prior-year for the current UI_P&L Structure row (Actual YTD - Prior YTD).
	measure 'P&L Var vs PY $ (YTD)' = [P&L Amount (YTD)] - [P&L Amount PY (YTD)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 9e52e4d7-c4f0-46bc-9779-2fc7f19e0386

	/// P&L percent variance vs prior-year for the current UI_P&L Structure row: (Actual YTD - Prior YTD) / Prior YTD.
	measure 'P&L Var vs PY % (YTD)' =
			DIVIDE(
			    [P&L Amount (YTD)] - [P&L Amount PY (YTD)],
			    [P&L Amount PY (YTD)]
			)
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 451be94f-24cb-4700-84b8-635dd56be49d

	/// P&L actual variance vs budget for the current UI_P&L Structure row (Actual YTD - Budget YTD).
	measure 'P&L Var vs Budget $ (YTD)' = [P&L Amount (YTD)] - [P&L Budget Amount (YTD)]
		formatString: $#,0;($#,0);$#,0
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: fb924c0d-e503-4d31-af48-ee6889c4dcbc

	/// P&L percent variance vs budget for the current UI_P&L Structure row: (Actual YTD - Budget YTD) / Budget YTD. Returns BLANK when the absolute budget base is below $1,000 to avoid meaningless extreme percentages.
	measure 'P&L Var vs Budget % (YTD)' =
			VAR BudgetAmt = [P&L Budget Amount (YTD)]
			VAR VarAmt = [P&L Amount (YTD)] - BudgetAmt
			VAR MinDenom = 1000
			RETURN
			    IF ( ABS ( BudgetAmt ) < MinDenom, BLANK (), DIVIDE ( VarAmt, BudgetAmt ) )
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 341e9ecc-3d87-4032-bb5c-297a74e1d443

	/// Helper: line-level P&L actual amount (no section-total behavior). YTD date window is applied by the calling measure.
	measure 'P&L Amount (YTD) (Line)' =
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			VAR LineItem = SELECTEDVALUE ( 'UI_P&L Structure'[Line Item] )
			
			VAR MarketsProjects =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "Projects"
			    )
			VAR MarketsServiceContracts =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "Service Contracts"
			    )
			VAR MarketsTM =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "T&M"
			    )
			
			VAR RevenueProjectsAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsProjects, GL_ACCT_D[MARKET] )
			    )
			VAR RevenueServiceContractsAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsServiceContracts, GL_ACCT_D[MARKET] )
			    )
			VAR RevenueTMAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsTM, GL_ACCT_D[MARKET] )
			    )
			
			VAR RevenueAmt = RevenueProjectsAmt + RevenueServiceContractsAmt + RevenueTMAmt
			
			VAR CosAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES" )
			VAR CosLaborBurdenAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] IN { "LABOR", "BURDEN" }
			    )
			VAR CosEquipMatAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "EQUIPMENT & MATERIAL"
			    )
			VAR CosSubcontractAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "SUBCONTRACT"
			    )
			VAR CosDiscountsAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "DISCOUNTS"
			    )
			VAR CosTaxExpenseAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "TAX EXPENSE"
			    )
			
			VAR GrossProfitAmt = RevenueAmt - CosAmt
			
			VAR OpsExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "OPERATIONS EXPENSE" )
			VAR ActualGrossProfitAmt = GrossProfitAmt - OpsExpenseAmt
			
			VAR SalesExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "SALES EXPENSE" )
			VAR GAExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "G&A EXPENSE" )
			VAR TotalSGAAmt = SalesExpenseAmt + GAExpenseAmt
			
			VAR OtherIncomeExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "OTHER INCOME & EXPENSE" )
			
			VAR NetProfitAmt = ActualGrossProfitAmt - TotalSGAAmt + OtherIncomeExpenseAmt
			
			RETURN
			    SWITCH (
			        TRUE (),
			        Section = "REVENUE" && LineItem = "Projects", RevenueProjectsAmt,
			        Section = "REVENUE" && LineItem = "Service Contracts", RevenueServiceContractsAmt,
			        Section = "REVENUE" && LineItem = "T&M", RevenueTMAmt,
			        LineItem = "Labor & Burden", CosLaborBurdenAmt,
			        LineItem = "Equipment & Material", CosEquipMatAmt,
			        LineItem = "Subcontract", CosSubcontractAmt,
			        LineItem = "Discounts", CosDiscountsAmt,
			        LineItem = "Tax Expense", CosTaxExpenseAmt,
			        LineItem = "Gross Profit", GrossProfitAmt,
			        LineItem = "Operations Expense", OpsExpenseAmt,
			        LineItem = "Actual Gross Profit", ActualGrossProfitAmt,
			        LineItem = "Sales Expense", SalesExpenseAmt,
			        LineItem = "G & A Expense", GAExpenseAmt,
			        LineItem = "Other Income & Expense", OtherIncomeExpenseAmt,
			        LineItem = "Net Profit", NetProfitAmt,
			        BLANK ()
			    )
		formatString: $#,0;($#,0);$#,0
		isHidden
		displayFolder: 7. Helper\7.3 P&L\YTD
		lineageTag: c78930f8-393f-49d1-847f-56664c8da6ed

	/// Helper: line-level P&L PY amount (no section-total behavior). YTD date window is applied by the calling measure.
	measure 'P&L Amount PY (YTD) (Line)' =
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			VAR LineItem = SELECTEDVALUE ( 'UI_P&L Structure'[Line Item] )
			
			VAR MarketsProjects =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "Projects"
			    )
			VAR MarketsServiceContracts =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "Service Contracts"
			    )
			VAR MarketsTM =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "T&M"
			    )
			
			VAR RevenueProjectsAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsProjects, GL_ACCT_D[MARKET] )
			    )
			VAR RevenueServiceContractsAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsServiceContracts, GL_ACCT_D[MARKET] )
			    )
			VAR RevenueTMAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsTM, GL_ACCT_D[MARKET] )
			    )
			
			VAR RevenueAmt = RevenueProjectsAmt + RevenueServiceContractsAmt + RevenueTMAmt
			
			VAR CosAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES" )
			VAR CosLaborBurdenAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] IN { "LABOR", "BURDEN" }
			    )
			VAR CosEquipMatAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "EQUIPMENT & MATERIAL"
			    )
			VAR CosSubcontractAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "SUBCONTRACT"
			    )
			VAR CosDiscountsAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "DISCOUNTS"
			    )
			VAR CosTaxExpenseAmt =
			    CALCULATE (
			        SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "TAX EXPENSE"
			    )
			
			VAR GrossProfitAmt = RevenueAmt - CosAmt
			
			VAR OpsExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "OPERATIONS EXPENSE" )
			VAR ActualGrossProfitAmt = GrossProfitAmt - OpsExpenseAmt
			
			VAR SalesExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "SALES EXPENSE" )
			VAR GAExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[DEBITAMT] ) - SUM ( POSTING_DATA_F[CRDTAMNT] ), GL_ACCT_D[ACCOUNT_TYPE] = "G&A EXPENSE" )
			VAR TotalSGAAmt = SalesExpenseAmt + GAExpenseAmt
			
			VAR OtherIncomeExpenseAmt =
			    CALCULATE ( SUM ( POSTING_DATA_F[CRDTAMNT] ) - SUM ( POSTING_DATA_F[DEBITAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "OTHER INCOME & EXPENSE" )
			
			VAR NetProfitAmt = ActualGrossProfitAmt - TotalSGAAmt + OtherIncomeExpenseAmt
			
			RETURN
			    SWITCH (
			        TRUE (),
			        Section = "REVENUE" && LineItem = "Projects", RevenueProjectsAmt,
			        Section = "REVENUE" && LineItem = "Service Contracts", RevenueServiceContractsAmt,
			        Section = "REVENUE" && LineItem = "T&M", RevenueTMAmt,
			        LineItem = "Labor & Burden", CosLaborBurdenAmt,
			        LineItem = "Equipment & Material", CosEquipMatAmt,
			        LineItem = "Subcontract", CosSubcontractAmt,
			        LineItem = "Discounts", CosDiscountsAmt,
			        LineItem = "Tax Expense", CosTaxExpenseAmt,
			        LineItem = "Gross Profit", GrossProfitAmt,
			        LineItem = "Operations Expense", OpsExpenseAmt,
			        LineItem = "Actual Gross Profit", ActualGrossProfitAmt,
			        LineItem = "Sales Expense", SalesExpenseAmt,
			        LineItem = "G & A Expense", GAExpenseAmt,
			        LineItem = "Other Income & Expense", OtherIncomeExpenseAmt,
			        LineItem = "Net Profit", NetProfitAmt,
			        BLANK ()
			    )
		formatString: $#,0;($#,0);$#,0
		isHidden
		displayFolder: 7. Helper\7.3 P&L\YTD
		lineageTag: f53e292d-358f-4c91-aa85-d3229b726b16

	/// Helper: line-level P&L budget amount (no section-total behavior). YTD date window is applied by the calling measure.
	measure 'P&L Budget Amount (YTD) (Line)' =
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			VAR LineItem = SELECTEDVALUE ( 'UI_P&L Structure'[Line Item] )
			
			VAR MarketsProjects =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "Projects"
			    )
			VAR MarketsServiceContracts =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "Service Contracts"
			    )
			VAR MarketsTM =
			    CALCULATETABLE (
			        VALUES ( GL_MARKET_STREAM_D[Market] ),
			        ALL ( GL_MARKET_STREAM_D ),
			        GL_MARKET_STREAM_D[Stream] = "T&M"
			    )
			
			VAR RevenueProjectsAmt =
			    CALCULATE (
			        -SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsProjects, GL_ACCT_D[MARKET] )
			    )
			VAR RevenueServiceContractsAmt =
			    CALCULATE (
			        -SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsServiceContracts, GL_ACCT_D[MARKET] )
			    )
			VAR RevenueTMAmt =
			    CALCULATE (
			        -SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "REVENUE",
			        TREATAS ( MarketsTM, GL_ACCT_D[MARKET] )
			    )
			
			VAR RevenueAmt = RevenueProjectsAmt + RevenueServiceContractsAmt + RevenueTMAmt
			
			VAR CosAmt =
			    CALCULATE ( SUM ( BUDGET_F[BUDGETAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES" )
			VAR CosLaborBurdenAmt =
			    CALCULATE (
			        SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] IN { "LABOR", "BURDEN" }
			    )
			VAR CosEquipMatAmt =
			    CALCULATE (
			        SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "EQUIPMENT & MATERIAL"
			    )
			VAR CosSubcontractAmt =
			    CALCULATE (
			        SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "SUBCONTRACT"
			    )
			VAR CosDiscountsAmt =
			    CALCULATE (
			        SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "DISCOUNTS"
			    )
			VAR CosTaxExpenseAmt =
			    CALCULATE (
			        SUM ( BUDGET_F[BUDGETAMT] ),
			        GL_ACCT_D[ACCOUNT_TYPE] = "COST OF SALES",
			        GL_ACCT_D[COSTOFSALES_SUBCATEGORY] = "TAX EXPENSE"
			    )
			
			VAR GrossProfitAmt = RevenueAmt - CosAmt
			
			VAR OpsExpenseAmt =
			    CALCULATE ( SUM ( BUDGET_F[BUDGETAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "OPERATIONS EXPENSE" )
			VAR ActualGrossProfitAmt = GrossProfitAmt - OpsExpenseAmt
			
			VAR SalesExpenseAmt =
			    CALCULATE ( SUM ( BUDGET_F[BUDGETAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "SALES EXPENSE" )
			VAR GAExpenseAmt =
			    CALCULATE ( SUM ( BUDGET_F[BUDGETAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "G&A EXPENSE" )
			VAR TotalSGAAmt = SalesExpenseAmt + GAExpenseAmt
			
			VAR OtherIncomeExpenseAmt =
			    CALCULATE ( -SUM ( BUDGET_F[BUDGETAMT] ), GL_ACCT_D[ACCOUNT_TYPE] = "OTHER INCOME & EXPENSE" )
			
			VAR NetProfitAmt = ActualGrossProfitAmt - TotalSGAAmt + OtherIncomeExpenseAmt
			
			RETURN
			    SWITCH (
			        TRUE (),
			        Section = "REVENUE" && LineItem = "Projects", RevenueProjectsAmt,
			        Section = "REVENUE" && LineItem = "Service Contracts", RevenueServiceContractsAmt,
			        Section = "REVENUE" && LineItem = "T&M", RevenueTMAmt,
			        LineItem = "Labor & Burden", CosLaborBurdenAmt,
			        LineItem = "Equipment & Material", CosEquipMatAmt,
			        LineItem = "Subcontract", CosSubcontractAmt,
			        LineItem = "Discounts", CosDiscountsAmt,
			        LineItem = "Tax Expense", CosTaxExpenseAmt,
			        LineItem = "Gross Profit", GrossProfitAmt,
			        LineItem = "Operations Expense", OpsExpenseAmt,
			        LineItem = "Actual Gross Profit", ActualGrossProfitAmt,
			        LineItem = "Sales Expense", SalesExpenseAmt,
			        LineItem = "G & A Expense", GAExpenseAmt,
			        LineItem = "Other Income & Expense", OtherIncomeExpenseAmt,
			        LineItem = "Net Profit", NetProfitAmt,
			        BLANK ()
			    )
		formatString: $#,0;($#,0);$#,0
		isHidden
		displayFolder: 7. Helper\7.3 P&L\YTD
		lineageTag: 5483baec-8776-4073-ae54-0eab23491a10

	/// Text operator for the current P&L row (+ / - / = / +/-). Returns an operator on both section header rows and line item rows when any of the main P&L values are present.
	measure 'P&L Operator' =
			VAR HasAnyValue =
			    NOT ISBLANK ( [P&L Amount (YTD)] )
			        || NOT ISBLANK ( [P&L Budget Amount (YTD)] )
			        || NOT ISBLANK ( [P&L Amount PY (YTD)] )
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			VAR LineItem = SELECTEDVALUE ( 'UI_P&L Structure'[Line Item] )
			VAR IsLine = ISINSCOPE ( 'UI_P&L Structure'[Line Item] )
			RETURN
			    IF (
			        NOT HasAnyValue || ISBLANK ( Section ),
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            IsLine && Section = "REVENUE", "+",
			            NOT IsLine && Section = "REVENUE", "+",
			
			            IsLine && Section = "COST OF SALES", "-",
			            NOT IsLine && Section = "COST OF SALES", "-",
			
			            Section = "GROSS PROFIT", "=",
			            Section = "OPERATIONS EXPENSE", "-",
			            Section = "ACTUAL GROSS PROFIT", "=",
			            Section = "SG&A EXPENSE", "-",
			            Section = "OTHER INCOME & EXPENSE", "+/-",
			            Section = "NET PROFIT", "=",
			            BLANK ()
			        )
			    )
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: 2710a298-0b7e-499a-8cd1-7602eb060697

	/// Helper numeric sign (+1/-1/0) corresponding to the P&L math direction for the current line item. Useful for conditional formatting or derived signed metrics.
	measure 'P&L Row Sign' =
			VAR Section = SELECTEDVALUE ( 'UI_P&L Structure'[Section] )
			VAR LineItem = SELECTEDVALUE ( 'UI_P&L Structure'[Line Item] )
			RETURN
			    IF (
			        ISBLANK ( LineItem ),
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            Section = "REVENUE", 1,
			            LineItem IN { "Labor & Burden", "Equipment & Material", "Subcontract", "Discounts", "Tax Expense" }, -1,
			            LineItem IN { "Operations Expense", "Sales Expense", "G & A Expense" }, -1,
			            LineItem = "Other Income & Expense", 1,
			            LineItem IN { "Gross Profit", "Actual Gross Profit", "Net Profit" }, 0,
			            BLANK ()
			        )
			    )
		formatString: 0;-0;0
		isHidden
		displayFolder: 7. Helper\7.3 P&L\YTD
		lineageTag: 3996aa79-c68e-4355-9b0d-75a09708e58b

	measure 'P&L Divider' = " "
		displayFolder: 4. P&L\4.1 YTD
		lineageTag: c8c62224-2419-4306-82e8-62db4947b4c3

	column _
		isHidden
		lineageTag: 51e1d78c-186d-4eac-8cc2-14bfc214dd1c
		isNameInferred
		sourceColumn: [_]

	partition '_Key Measures' = calculated
		mode: import
		source = DATATABLE("_", INTEGER, {{1}})

