table SERVCONTRACTS_D_STAGING
	lineageTag: 328b225c-82a1-47ad-8487-e884095f9c3a

	column AgreementKey
		dataType: string
		lineageTag: 217c6477-59d8-4e8f-bcb5-841315bb3d03
		summarizeBy: none
		sourceColumn: AgreementKey

		annotation SummarizationSetBy = Automatic

	column 'Custnmbr Key'
		dataType: string
		lineageTag: f0dca236-18ac-4596-91c3-7bdd7c677637
		summarizeBy: none
		sourceColumn: Custnmbr Key

		annotation SummarizationSetBy = Automatic

	column 'Contract Number'
		dataType: string
		lineageTag: b10368d5-205f-42ea-a71d-94cba1d7c305
		summarizeBy: none
		sourceColumn: Contract Number

		annotation SummarizationSetBy = Automatic

	column 'Customer Number'
		dataType: string
		lineageTag: 81177669-28c4-42a1-a97c-aafd76f600c4
		summarizeBy: none
		sourceColumn: Customer Number

		annotation SummarizationSetBy = Automatic

	column YearIndex
		dataType: double
		lineageTag: d24ecc70-6c2d-4bde-8c72-2cb625e06613
		summarizeBy: sum
		sourceColumn: YearIndex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Contract Description'
		dataType: string
		lineageTag: 62e68a32-9723-4783-8d59-ecd00a071604
		summarizeBy: none
		sourceColumn: Contract Description

		annotation SummarizationSetBy = Automatic

	column 'Contract Type'
		dataType: string
		lineageTag: 1096ab9e-2022-4d3a-b441-675374296637
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column Divisions
		dataType: string
		lineageTag: cf56be2e-9c9e-4d10-8975-6f7c95ac664d
		summarizeBy: none
		sourceColumn: Divisions

		annotation SummarizationSetBy = Automatic

	column 'Contract Status'
		dataType: string
		lineageTag: 8f082ff3-9a36-4167-9d14-7f8f168f8900
		summarizeBy: none
		sourceColumn: Contract Status

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 756a36f7-6ae0-48b3-8b56-660d997713f3
		summarizeBy: none
		sourceColumn: Start Date

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 10be2f50-d9f3-4db9-8386-7c5900cb8474
		summarizeBy: none
		sourceColumn: End Date

		annotation SummarizationSetBy = Automatic

	column 'Contract Amount'
		dataType: double
		lineageTag: 3f1ae9f1-1913-4912-bc21-b69c5f524dd9
		summarizeBy: sum
		sourceColumn: Contract Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Annual Contract Value'
		dataType: double
		lineageTag: 082b0fdf-5311-4a9d-940e-134c112d0455
		summarizeBy: sum
		sourceColumn: Annual Contract Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cancel Box'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 50005dab-1bae-4095-bba6-9e7c4dbb3ba4
		summarizeBy: none
		sourceColumn: Cancel Box

		annotation SummarizationSetBy = Automatic

	partition SERVCONTRACTS_D_STAGING = m
		mode: import
		queryGroup: Staging
		source = ```
				let
				    // 1. Get Source Data
				    Source = CONTRACTS_D, 
				    
				    // 2. Identify Service Projects to Exclude
				    Projects_Source = PROJECTS_D,
				    Service_Projects = Table.SelectRows(Projects_Source, each [Project Type] = "Service Contract"),
				    Service_Project_Numbers = Table.Distinct(Table.SelectColumns(Service_Projects, {"Project Number"})),
				    
				    // 3. Filter Contracts to Exclude Service Projects
				    Merged_For_Filter = Table.NestedJoin(Source, {"Contract Number"}, Service_Project_Numbers, {"Project Number"}, "ServiceProjects", JoinKind.LeftAnti),
				    Filtered_Agreements = Table.RemoveColumns(Merged_For_Filter, {"ServiceProjects"}),
				
				    // 4. Explode Years based on Wscontsq
				    Add_Year_List = Table.AddColumn(Filtered_Agreements, "YearIndex", each List.Numbers(1, if [Wscontsq] = null or [Wscontsq] < 1 then 1 else [Wscontsq])),
				    Expanded_Years = Table.ExpandListColumn(Add_Year_List, "YearIndex"),
				
				    // 5. Create Keys
				    Add_Customer_Key = Table.AddColumn(Expanded_Years, "Customer Key Full", each [Custnmbr] & [Source], type text),
				    Add_Agreement_Key = Table.AddColumn(Add_Customer_Key, "AgreementKey", each [Customer Key Full] & "_" & [Contract Number] & "_" & Text.From([YearIndex]), type text),
				
				    // 6. Set Types
				    Typed_Final = Table.TransformColumnTypes(Add_Agreement_Key, {{"AgreementKey", type text}, {"YearIndex", Int64.Type}}),
				
				    // 7. Group by AgreementKey to Deduplicate (Master/Servant Aggregation)
				    Grouped_Agreements = Table.Group(Typed_Final, {"AgreementKey", "Custnmbr Key"}, {{"Contract Number", each List.Max([Contract Number]), type nullable text}, {"Customer Number", each List.Max([Custnmbr]), type nullable text}, {"YearIndex", each List.Max([YearIndex]), type nullable number}, {"Contract Description", each List.Max([Contract Description]), type nullable text}, {"Contract Type", each List.Max([Contract Type]), type nullable text}, {"Divisions", each List.Max([Divisions]), type nullable text}, {"Contract Status", each List.Max([Contract Status]), type nullable text}, {"Start Date", each List.Min([Contract Start Date]), type nullable datetime}, {"End Date", each List.Max([Contract Expiration Date]), type nullable datetime}, {"Contract Amount", each List.Sum([Contract Amount]), type nullable number}, {"Annual Contract Value", each List.Sum([Annual Contract Value]), type nullable number}, {"Cancel Box", each List.Max([Cancel Box]), type nullable logical}})
				in
				    Grouped_Agreements
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

