// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
VAR SummaryTable =
    SUMMARIZE(
        PROJECTS_D,
        PROJECTS_D[SurrogateProjectID],
        "CountRows", COUNTROWS(PROJECTS_D)
    )
RETURN
    FILTER(SummaryTable, [CountRows] > 1)
