  -- Non-orphan divisions missing from DIVISIONS_D
  EVALUATE
  VAR FactDivs =
      EXCEPT(
          VALUES(SERVCONTRACTS_D[Divisions]),
          VALUES(DIVISIONS_D[DivisionCode])
      )
  RETURN
  FILTER (
      ADDCOLUMNS(
          FactDivs,
          "Service Contract Revenue (non-orphans)",
              VAR div = SELECTEDVALUE(SERVCONTRACTS_D[Divisions])
              RETURN CALCULATE(
                  [Service Contract Revenue],
                  SERVCONTRACTS_D[Divisions] = div,
                  ISBLANK(SERVCONTRACTS_D[OrphanSource])
              )
      ),
      [Service Contract Revenue (non-orphans)] <> 0
  )

  -- Orphan revenue by division value (to keep separate in visuals)
  EVALUATE
  SUMMARIZECOLUMNS(
      SERVCONTRACTS_D[Divisions],
      SERVCONTRACTS_D[OrphanSource],
      "Orphan Service Contract Revenue",
          CALCULATE([Service Contract Revenue], NOT ISBLANK(SERVCONTRACTS_D[OrphanSource]))
  )