table CUSTOMERS_D
	lineageTag: 76a5d38b-6f2e-4506-b3d2-d63992540541

	column 'Customer Number'
		dataType: string
		lineageTag: 2310d2bf-4f69-4dfb-b24b-315a48542cf6
		summarizeBy: none
		sourceColumn: Customer Number

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: c2cfce0c-25ec-4dfa-a7e2-9a1aa9ef271c
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Customer Class'
		dataType: string
		lineageTag: ffb44745-53d0-46fc-b9a0-92160375f271
		summarizeBy: none
		sourceColumn: Customer Class

		annotation SummarizationSetBy = Automatic

	column Address1
		dataType: string
		lineageTag: 61cf3346-4866-4b8a-9481-ddd0256b1405
		summarizeBy: none
		sourceColumn: Address1

		annotation SummarizationSetBy = Automatic

	column Address2
		dataType: string
		lineageTag: 67bc395c-497c-4be1-a1d0-5d9cc4af8884
		summarizeBy: none
		sourceColumn: Address2

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 90590fdb-c891-4008-aa8c-88bfbde41097
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 36e7081f-9397-4f06-a693-2ea2b10eecb7
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b18583ff-60ec-4562-b401-6fd9cd4627f8
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Zip
		dataType: string
		lineageTag: 04a4deef-0cfe-42db-8a40-e3315364d6f8
		summarizeBy: none
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column Phone1
		dataType: string
		lineageTag: 88be6f98-5f36-486e-b208-3800cb9d4d45
		summarizeBy: none
		sourceColumn: Phone1

		annotation SummarizationSetBy = Automatic

	column 'Payment Term'
		dataType: string
		lineageTag: 6dc451d7-b992-4ebf-a54c-c9b19788cf69
		summarizeBy: none
		sourceColumn: Payment Term

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 041929c4-3635-4e21-b9d7-f39f4c1aa2c0
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 5c190b06-8998-42cd-b09a-af2d3e48ff1b
			defaultHierarchy: LocalDateTable_07991bce-1a23-4b3d-aba2-87112141d51c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Updated
		dataType: dateTime
		formatString: General Date
		lineageTag: b148e41f-7e55-4972-a8e4-cbabece10ee5
		summarizeBy: none
		sourceColumn: Updated

		variation Variation
			isDefault
			relationship: 7d43d642-b77d-4ae0-a82d-c5d685f0d89d
			defaultHierarchy: LocalDateTable_13b9d61b-849e-41bf-a06c-3449feaae67e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: f2a72cb8-817a-427a-b912-d43d0933bda4
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'Quadra Source'
		dataType: string
		lineageTag: 4c16fdfc-76a9-4df4-b700-db833c6aeee4
		summarizeBy: none
		sourceColumn: Quadra Source

		annotation SummarizationSetBy = Automatic

	column 'Customer Key'
		dataType: string
		lineageTag: fb4b5803-0c73-435d-95e6-2a52af56c1ca
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

	column 'Quadra Customer Key'
		dataType: string
		lineageTag: 76dda07f-c982-4895-86ec-ae6778204854
		summarizeBy: none
		sourceColumn: Quadra Customer Key

		annotation SummarizationSetBy = Automatic

	partition CUSTOMERS_D = m
		mode: import
		source = ```
				let
				    Source = Snowflake.Databases("ufwarhx-qo50284.snowflakecomputing.com", "COMPUTE_WH", []),
				    DATA_WAREHOUSE_Database = Source{[Name="DATA_WAREHOUSE",Kind="Database"]}[Data],
				    DW_FINAL_Schema = DATA_WAREHOUSE_Database{[Name="DW_FINAL",Kind="Schema"]}[Data],
				    CUSTOMERS_D_Table = DW_FINAL_Schema{[Name="CUSTOMERS_D",Kind="Table"]}[Data], 
				    ProperCase = Table.RenameColumns(CUSTOMERS_D_Table, List.Transform(Table.ColumnNames(CUSTOMERS_D_Table), each {_, Text.Proper(Text.Replace(_, "_", " "))})),
				    #"Capitalized Each Word" = Table.TransformColumns(ProperCase,{{"Customer Name", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

