table SPOT_FINANCIALS_F
	lineageTag: d57d3445-2b0a-4430-8a92-d747348f7bb9

	column ServiceCallKey
		dataType: string
		lineageTag: ffb59dcd-647b-49af-af22-3af95c4b0301
		summarizeBy: none
		sourceColumn: ServiceCallKey

		annotation SummarizationSetBy = Automatic

	column Custnmbr
		dataType: string
		lineageTag: 62b8df57-02a7-477d-900d-f03a9aa60ce0
		summarizeBy: none
		sourceColumn: Custnmbr

		annotation SummarizationSetBy = Automatic

	column 'Contract Number'
		dataType: string
		lineageTag: 33754c93-c0df-4e24-a8ca-529ef426f211
		summarizeBy: none
		sourceColumn: Contract Number

		annotation SummarizationSetBy = Automatic

	column 'Type Of Call'
		dataType: string
		lineageTag: 715174bb-7cdb-4b9a-8368-855532093c9b
		summarizeBy: none
		sourceColumn: Type Of Call

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6be674e-ed32-4c68-a33e-1c581fe0799a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Revenue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c080a029-22dd-45b7-84c8-c67d63138380
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Cost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 54a72fc3-790a-4cb4-96c4-d74cbb61735c
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Customer Key'
		dataType: string
		lineageTag: 78e6d30d-d583-423b-8d6c-bae1825e126a
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

	column 'Source Type'
		dataType: string
		lineageTag: 516f4197-c90d-431c-a22c-8ea053261503
		summarizeBy: none
		sourceColumn: Source Type

		annotation SummarizationSetBy = Automatic

	column Divisions
		dataType: string
		lineageTag: b56e6f20-f85c-492d-8577-519d670a46cb
		summarizeBy: none
		sourceColumn: Divisions

		annotation SummarizationSetBy = Automatic

	partition SPOT_FINANCIALS_F = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				    Source = CALLS_F,
				    // Filter for calls where Contract Number is NULL (Spot/T&M)
				    Filtered_Spot_Calls = Table.SelectRows(Source, each [Contract Number] = null or [Contract Number] = ""),
				
				    // Select and rename columns
				    Selected_Columns = Table.SelectColumns(Filtered_Spot_Calls,{"Service Call Id", "Custnmbr", "Contract Number", "Type Of Call", "Date Of Service Call", "Divisions", "Billable All", "Cost All", "Customernbr Key"}),
				    Renamed_Columns = Table.RenameColumns(Selected_Columns, {
				        {"Date Of Service Call", "Date"},
				        {"Customernbr Key", "Customer Key"},
				        {"Billable All", "Revenue"},
				        {"Cost All", "Cost"},
				        {"Service Call Id", "ServiceCallKey"}
				    }),
				    
				    // Set data types
				    Typed_Columns = Table.TransformColumnTypes(Renamed_Columns, {
				        {"Date", type date},
				        {"Customer Key", type text},
				        {"Revenue", Currency.Type},
				        {"Cost", Currency.Type},
				        {"ServiceCallKey", type text}
				    }),
				    
				    // Add Source Type for categorization in reports
				    SPOT_FINANCIALS_F = Table.AddColumn(Typed_Columns, "Source Type", each "Spot T&M", type text),
				    #"Trimmed Text" = Table.TransformColumns(SPOT_FINANCIALS_F,{{"Divisions", Text.Trim, type text}}),
				    AddDateGuard = Table.SelectRows(#"Trimmed Text", each [Date] <= Date.AddYears(Date.From(DateTime.LocalNow()), 0))
				in
				    AddDateGuard
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

