table PROJECT_COSTS_F
	lineageTag: a075b8e0-2de5-42d0-8197-172ce2591b30

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0624dfc2-e189-4b92-a054-fbda955c7383
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SurrogateProjectID
		dataType: string
		lineageTag: 87d1032d-56e3-40e0-bed6-08fdc2576e0c
		summarizeBy: none
		sourceColumn: SurrogateProjectID

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 00ae1409-9dce-47b5-b0a3-1ed6b80ef1e3
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Source Type'
		dataType: string
		lineageTag: aa603deb-f3f4-496f-b635-6d77fd7b493a
		summarizeBy: none
		sourceColumn: Source Type

		annotation SummarizationSetBy = Automatic

	column 'Service Call Id'
		dataType: string
		lineageTag: c37f0b73-0249-471a-8165-0bd4072e6d3a
		summarizeBy: none
		sourceColumn: Service Call Id

		annotation SummarizationSetBy = Automatic

	partition PROJECT_COSTS_F = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				    //
				    // ==========================================
				    //     JOB COST STREAM (From JOB_FINANCIALS_F)
				    // ==========================================
				    //
				    Job_Cost_Source =
				        JOB_FINANCIALS_F,   // Table containing Monthly Cost + Job Earned Revenue
				
				    Job_Cost_Slim =
				        Table.SelectColumns(
				            Job_Cost_Source,
				            {"Period Date", "SurrogateProjectID", "Monthly Cost"}
				        ),
				
				    Job_Cost_Renamed =
				        Table.RenameColumns(
				            Job_Cost_Slim,
				            {
				                {"Period Date", "Date"},
				                {"Monthly Cost", "Amount"}
				            }
				        ),
				
				    Job_Cost_Typed =
				        Table.TransformColumnTypes(
				            Job_Cost_Renamed,
				            {
				                {"Date", type date},
				                {"SurrogateProjectID", type text},
				                {"Amount", Currency.Type}
				            }
				        ),
				
				    Job_Cost_Label =
				        Table.AddColumn(
				            Job_Cost_Typed,
				            "Source Type",
				            each "Job Cost",
				            type text
				        ),
				
				    // Add NULL Service Call Id to match schema
				    Job_Cost_Final = 
				        Table.AddColumn(
				            Job_Cost_Label,
				            "Service Call Id",
				            each null,
				            type text
				        ),
				
				
				    //
				    // ==========================================
				    //     SERVICE PROJECT COST STREAM
				    // ==========================================
				    //
				
				    // Filter PROJECTS_D for service contracts
				    Service_Projects =
				        Table.SelectRows(
				            PROJECTS_D,
				            each [Project Type] = "Service Contract"
				        ),
				
				    // Keep the surrogate key + project number for joining
				    Service_Project_Keys =
				        Table.SelectColumns(
				            Service_Projects,
				            {"Project Number", "SurrogateProjectID"}
				        ),
				
				    // DEDUPLICATE KEYS to prevent Fan Out (Double Counting)
				    // This picks one "Winner" SurrogateID per Project Number
				    Service_Project_Unique =
				        Table.Distinct(
				            Service_Project_Keys,
				            {"Project Number"}
				        ),
				
				    // Slim CALLS_F table
				    Calls_Slim =
				        Table.SelectColumns(
				            CALLS_F,
				            {
				                "Date Of Service Call",
				                "Contract Number",
				                "Cost All",
				                "Service Call Id" // Added ID
				            }
				        ),
				
				    // Fast JOIN on Project Number ONLY (Deduplicated)
				    Joined =
				        Table.NestedJoin(
				            Calls_Slim,
				            {"Contract Number"},
				            Service_Project_Unique, // Use Deduplicated Table
				            {"Project Number"},
				            "Matched",
				            JoinKind.Inner
				        ),
				
				    // Expand key fields from PROJECTS_D
				    Expanded =
				        Table.ExpandTableColumn(
				            Joined,
				            "Matched",
				            {"SurrogateProjectID"},
				            {"SurrogateProjectID"}
				        ),
				
				    // Cleanup and type transform
				    Cleaned =
				        Table.TransformColumnTypes(
				            Table.RenameColumns(
				                Expanded,
				                {
				                    {"Date Of Service Call", "Date"},
				                    {"Cost All", "Amount"}
				                }
				            ),
				            {
				                {"Date", type date},
				                {"SurrogateProjectID", type text},
				                {"Amount", Currency.Type},
				                {"Service Call Id", type text}
				            }
				        ),
				
				    // Add source label
				    Service_Cost_Final =
				        Table.AddColumn(
				            Cleaned,
				            "Source Type",
				            each "Service Call Cost",
				            type text
				        ),
				
				    // Final column selection
				    Service_Cost_Formatted =
				        Table.SelectColumns(
				            Service_Cost_Final,
				            {
				                "Date",
				                "SurrogateProjectID",
				                "Amount",
				                "Source Type",
				                "Service Call Id" // Keep ID
				            }
				        ),
				
				
				    //
				    // ==========================================
				    //          COMBINE BOTH STREAMS
				    // ==========================================
				    //
				    FACT_UNIFIED_COSTS =
				        Table.Combine({
				            Job_Cost_Final,
				            Service_Cost_Formatted
				        }),
				    AddDateGuard = Table.SelectRows(#"FACT_UNIFIED_COSTS", each [Date] <= Date.AddYears(Date.From(DateTime.LocalNow()), 0))
				in
				    AddDateGuard
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

