// Write your formula below, select 'Run' to try it out. When ready, select 'Update model' to add the measure to your model.
DEFINE
	MEASURE '_KeyMeasures'[New Measure] = COUNTROWS('_KeyMeasures')

EVALUATE
	SUMMARIZECOLUMNS(
		"New Measure", [New Measure]
	)