EVALUATE
// ---------------------------------------------------------
// STEP 1: GET THE BASE TABLE
// ---------------------------------------------------------
VAR _BaseTable = 
    FILTER (
        SERVCONTRACTS_D,
        NOT ISBLANK ( SERVCONTRACTS_D[OrphanSource] )
    )

// ---------------------------------------------------------
// STEP 2: CALCULATE TOKENS ONLY
// ---------------------------------------------------------
VAR _Step2_Tokens = 
    ADDCOLUMNS (
        _BaseTable,
        "Token1",
            VAR AK = [AgreementKey]
            VAR p1 = FIND("_", AK, 1, BLANK())
            RETURN IF(ISBLANK(p1), AK, LEFT(AK, p1 - 1)),
        "Token2",
            VAR AK = [AgreementKey]
            VAR p1 = FIND("_", AK, 1, BLANK())
            VAR rest = IF(ISBLANK(p1), BLANK(), MID(AK, p1 + 1, LEN(AK)))
            VAR p2 = FIND("_", rest, 1, BLANK())
            RETURN IF(ISBLANK(p2), rest, LEFT(rest, p2 - 1)),
        "Token3",
            VAR AK = [AgreementKey]
            VAR p1 = FIND("_", AK, 1, BLANK())
            VAR rest1 = IF(ISBLANK(p1), BLANK(), MID(AK, p1 + 1, LEN(AK)))
            VAR p2 = FIND("_", rest1, 1, BLANK())
            VAR rest2 = IF(ISBLANK(p2), BLANK(), MID(rest1, p2 + 1, LEN(rest1)))
            VAR p3 = FIND("_", rest2, 1, BLANK())
            RETURN IF(ISBLANK(p3), rest2, LEFT(rest2, p3 - 1)),
        "Token4",
            VAR AK = [AgreementKey]
            VAR p1 = FIND("_", AK, 1, BLANK())
            VAR r1 = IF(ISBLANK(p1), BLANK(), MID(AK, p1 + 1, LEN(AK)))
            VAR p2 = FIND("_", r1, 1, BLANK())
            VAR r2 = IF(ISBLANK(p2), BLANK(), MID(r1, p2 + 1, LEN(r1)))
            VAR p3 = FIND("_", r2, 1, BLANK())
            RETURN IF(ISBLANK(p3), BLANK(), MID(r2, p3 + 1, LEN(r2)))
    )

// ---------------------------------------------------------
// STEP 3: CALCULATE METRICS & LOOKUPS
// FIX: We use variables (CurrentT1, CurrentT2) to pass values into CALCULATE
// ---------------------------------------------------------
VAR _Step3_Metrics = 
    ADDCOLUMNS (
        _Step2_Tokens,
        "Token1_Len", LEN([Token1]),
        "Token2_Len", LEN([Token2]),
        "Token3_Len", LEN([Token3]),
        "Token4_Len", LEN([Token4]),
        
        "Token1_In_CustomerKey", 
            VAR CurrentT1 = [Token1]
            RETURN CALCULATE(COUNTROWS(CUSTOMERS_D), CUSTOMERS_D[Customer Key] = CurrentT1),
            
        "Token12_In_CustomerKey", 
            VAR CurrentT1 = [Token1]
            VAR CurrentT2 = [Token2]
            VAR Combined = CurrentT1 & "_" & CurrentT2
            RETURN CALCULATE(COUNTROWS(CUSTOMERS_D), CUSTOMERS_D[Customer Key] = Combined),
            
        "Token2_In_Contracts", 
            VAR CurrentT2 = [Token2]
            RETURN CALCULATE(COUNTROWS(SERVCONTRACTS_D), SERVCONTRACTS_D[Contract Number] = CurrentT2),
            
        "Token3_Is_Number", 
            IF(ISBLANK(IFERROR(VALUE([Token3]), BLANK())), 0, 1),
            
        "Has_3_Tokens", IF(NOT ISBLANK([Token3]), 1, 0),
        "Has_4_Tokens", IF(NOT ISBLANK([Token4]), 1, 0),
        "Contains_Space", IF(CONTAINSSTRING([AgreementKey], " "), 1, 0)
    )

// ---------------------------------------------------------
// STEP 4: ROOT CAUSE
// ---------------------------------------------------------
VAR _Step4_Final = 
    ADDCOLUMNS (
        _Step3_Metrics,
        "NonNumeric_Token3", IF([Token3_Is_Number] = 0, 1, 0),
        "LikelyRootCause",
            SWITCH(
                TRUE(),
                [Has_3_Tokens] = 0, "Missing Tokens",
                [Has_4_Tokens] = 1, "Extra Token",
                [Token1_In_CustomerKey] = 0 && [Token12_In_CustomerKey] = 0, "Bad Customer Prefix",
                [Token2_In_Contracts] = 0, "Unknown Contract Number",
                [Token3_Is_Number] = 0, "Malformed Wscontsq Token",
                [Contains_Space] = 1, "Contains Spaces",
                "Unclassified"
            )
    )

RETURN
    _Step4_Final