 EVALUATE                                                                                                         
ROW(                                                                                                             
     "Total Revenue Rows\", COUNTROWS('PROJECT_REVENUE_F'),                                                      
     "Orphaned Revenue Rows\", COUNTROWS(                                                                        
         FILTER(                                                                                                  
             'PROJECT_REVENUE_F',                                                                                 
             NOT( 'PROJECT_REVENUE_F'[SurrogateProjectID] IN VALUES('PROJECTS_D'[SurrogateProjectID]) )           
         )                                                                                                        
     )                                                                                                            
 )