table 'Refresh Date'
	lineageTag: 5723d2cf-9f5d-4921-9627-79b2a8f9232a

	measure 'Refresh Date' = ```
			
			var tim2 = max('Refresh Date'[Time]) - TIME(4, 0, 0)
			 var tim = max('Refresh Date'[Time]) 
			return
			"Last Refresh: " & max('Refresh Date'[Date]) & " " & tim2
			```
		lineageTag: 9f8b6ac1-4e78-4715-82f3-885e0e87f920

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff3bf557-12f7-4ccc-b9a0-b4ace02b24d5
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 749868ce-94d8-4e75-931c-d658d90ff837
			defaultHierarchy: LocalDateTable_8931b809-08ab-4252-8179-ca3c21383cd6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 79df6295-5d31-468f-97a2-555d8676deb1
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Refresh Date' = m
		mode: import
		source =
				let
				    Source = DateTimeZone.SwitchZone(DateTimeZone.UtcNow(), -5, 0),
				    #"Converted to Table1" = #table(1, {{Source}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table1",{{"Column1", type datetime}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Column1", "Column1 - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"Column1", type date}, {"Column1 - Copy", type time}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Column1", "Date"}, {"Column1 - Copy", "Time"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

