table DIVISIONS_D
	lineageTag: fb9acfc4-5c41-4c13-864a-edbaa992ccc6

	column DivisionCode
		dataType: string
		lineageTag: dc7f7987-b4d9-414f-bee1-9bc302f1d9ea
		summarizeBy: none
		sourceColumn: DivisionCode

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 7579a13a-6c7c-40e1-959b-bcab9a85beac
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 70d2fe73-79b9-4ab9-b02e-02436e88e0c7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: a027e4a9-1369-4524-82ba-2cff8d5de7e8
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	partition DIVISIONS_D = m
		mode: import
		source =
				let
				    Source = AzureStorage.Blobs("https://stgreen.blob.core.windows.net"),
				    #"Navigation 1" = Source{[Name = "datasets"]}[Data],
				    #"https://stgreen blob core windows net/datasets/_DIVISIONS_D csv" = #"Navigation 1"{[#"Folder Path"="https://stgreen.blob.core.windows.net/datasets/",Name="DIVISIONS_D.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"https://stgreen blob core windows net/datasets/_DIVISIONS_D csv",[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Imported CSV",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"DivisionCode", type text}, {"Division", type text}, {"Region", type text}, {"Company", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"Company", Text.Trim, type text}})
				    in #"Trimmed Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

