table CONTRACTS_D
	lineageTag: 7446fe80-6891-4924-963f-ae98480d0081

	column 'Cleaned Divisions'
		dataType: string
		lineageTag: bcf7c242-f950-4e8a-b663-c06a7131cf44
		summarizeBy: none
		sourceColumn: Cleaned Divisions

		annotation SummarizationSetBy = Automatic

	column 'Contract Type'
		dataType: string
		lineageTag: 66675775-b23f-4b51-9115-8724f3b405b3
		summarizeBy: none
		sourceColumn: Contract Type

		annotation SummarizationSetBy = Automatic

	column Custnmbr
		dataType: string
		lineageTag: 71255abf-7eeb-4fff-aa58-e8ef04f73ce1
		summarizeBy: none
		sourceColumn: Custnmbr

		annotation SummarizationSetBy = Automatic

	column 'Contract Number'
		dataType: string
		lineageTag: 25fbb30c-c06a-441e-8c20-4b4fc7f27560
		summarizeBy: none
		sourceColumn: Contract Number

		annotation SummarizationSetBy = Automatic

	column 'Contract Description'
		dataType: string
		lineageTag: d6a901e2-9cc5-4465-8da6-c87017b7645a
		summarizeBy: none
		sourceColumn: Contract Description

		annotation SummarizationSetBy = Automatic

	column 'Contract Status'
		dataType: string
		lineageTag: 7177f2c9-05ee-402e-abbf-825f8ca5b113
		summarizeBy: none
		sourceColumn: Contract Status

		annotation SummarizationSetBy = Automatic

	column 'Contract Internal Name'
		dataType: string
		lineageTag: b4eacfe5-f517-486a-92a0-405eeb2afbf1
		summarizeBy: none
		sourceColumn: Contract Internal Name

		annotation SummarizationSetBy = Automatic

	column 'Cancel Box'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0227cd7f-c7a5-44cf-acc1-38a744a7e199
		summarizeBy: none
		sourceColumn: Cancel Box

		annotation SummarizationSetBy = Automatic

	column Divisions
		dataType: string
		lineageTag: 0c72afa4-185e-4bbc-bd87-e4b33a35f3ed
		summarizeBy: none
		sourceColumn: Divisions

		annotation SummarizationSetBy = Automatic

	column 'Contract Amount'
		dataType: double
		lineageTag: bad857ba-b922-4453-8ea6-44f919708bc4
		summarizeBy: sum
		sourceColumn: Contract Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wscontractrenewalvalue
		dataType: double
		lineageTag: 35e4bc55-f5e2-4c9a-a1e7-26a63199bafc
		summarizeBy: sum
		sourceColumn: Wscontractrenewalvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wscontsq
		dataType: double
		lineageTag: b696e7a6-ff92-421b-b165-531dd9f719c8
		summarizeBy: sum
		sourceColumn: Wscontsq

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bill Freq'
		dataType: double
		lineageTag: ca55b7ff-8b64-4828-9e93-44e7189d1cf8
		summarizeBy: sum
		sourceColumn: Bill Freq

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Wennsoft Close Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: e6a9bc92-4bd2-46d9-a351-a477088d6741
		summarizeBy: none
		sourceColumn: Wennsoft Close Date

		annotation SummarizationSetBy = Automatic

	column 'Amount Billed'
		dataType: double
		lineageTag: e207f770-b891-4d5f-892f-275c234b5dbd
		summarizeBy: sum
		sourceColumn: Amount Billed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Slprsnid
		dataType: string
		lineageTag: 818ca387-a786-4199-a25c-ddb10add8b06
		summarizeBy: none
		sourceColumn: Slprsnid

		annotation SummarizationSetBy = Automatic

	column Taxschid
		dataType: string
		lineageTag: 5d383a0c-b971-47ca-a858-f5c420a3f921
		summarizeBy: none
		sourceColumn: Taxschid

		annotation SummarizationSetBy = Automatic

	column 'Annual Contract Value'
		dataType: double
		lineageTag: e54c7366-a460-4569-8769-a5f4e4f81d15
		summarizeBy: sum
		sourceColumn: Annual Contract Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Revenue Rec Method Id'
		dataType: double
		lineageTag: 68dcfe99-74aa-4a72-9a3a-7eb26f51a068
		summarizeBy: count
		sourceColumn: Revenue Rec Method Id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Invoice Style'
		dataType: double
		lineageTag: 8d4ba23d-6dfb-499f-b5f0-8db0ae545a4f
		summarizeBy: sum
		sourceColumn: Invoice Style

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Multiyear Contract Flag'
		dataType: double
		lineageTag: ae50387d-3d7e-4bb5-81db-7958e83f7c02
		summarizeBy: sum
		sourceColumn: Multiyear Contract Flag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Contract Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b38806b0-2759-4150-93fb-2e21d32dfe7d
		summarizeBy: none
		sourceColumn: Contract Start Date

		annotation SummarizationSetBy = Automatic

	column 'Contract Expiration Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 80066f45-51cd-441e-9f56-dc87a47b1a71
		summarizeBy: none
		sourceColumn: Contract Expiration Date

		annotation SummarizationSetBy = Automatic

	column 'Forecast Original Equip'
		dataType: double
		lineageTag: 135d1e86-9a39-40cc-bdee-9dd1404df519
		summarizeBy: sum
		sourceColumn: Forecast Original Equip

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Original Labor'
		dataType: double
		lineageTag: 0be5e6ac-cd56-4429-b8b6-e77684784e93
		summarizeBy: sum
		sourceColumn: Forecast Original Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fore Orig Material'
		dataType: double
		lineageTag: cd1769e3-a722-4cab-a37f-31f3f4710d04
		summarizeBy: sum
		sourceColumn: Fore Orig Material

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Original Other'
		dataType: double
		lineageTag: bb47e56f-cee3-4722-87fe-626174487ca6
		summarizeBy: sum
		sourceColumn: Forecast Original Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Original Subs'
		dataType: double
		lineageTag: 14f8dbf3-c54b-4251-9967-fc6d2aaa2bfa
		summarizeBy: sum
		sourceColumn: Forecast Original Subs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor 1'
		dataType: double
		lineageTag: a655c243-38e2-4be7-9826-b80bcd8ce8a4
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor1 Hrs Repair'
		dataType: double
		lineageTag: 3649c6ad-2b15-46ed-a914-fe8aa9084156
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor1 Hrs Repair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor 2'
		dataType: double
		lineageTag: 6292abcc-8b26-445a-9aac-c38af8125778
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fore Orig Labor 2 Hrs Pm'
		dataType: double
		lineageTag: d0f14446-1bfc-44b3-bc10-a75b254361cf
		summarizeBy: sum
		sourceColumn: Fore Orig Labor 2 Hrs Pm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor 3'
		dataType: double
		lineageTag: 65277bbb-814d-41a6-9217-a3117d4e7839
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor3 Hrs Travel'
		dataType: double
		lineageTag: a31d7d00-24ae-4cd2-b459-ecbba5db919c
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor3 Hrs Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor 4'
		dataType: double
		lineageTag: 750f02f4-65ff-4915-b086-44dfcb1e5f08
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor4 Hrs'
		dataType: double
		lineageTag: 64dae011-2bc8-4300-b22c-8ddc187d3467
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor4 Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor 5'
		dataType: double
		lineageTag: b53d5601-738e-4b1c-a11e-3a2be0e0ffc2
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Labor5 Hrs'
		dataType: double
		lineageTag: ef23c03c-ad25-4222-b81e-f8ce7c11c839
		summarizeBy: sum
		sourceColumn: Forecast Orig Labor5 Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Orig Tot Labor'
		dataType: double
		lineageTag: b5478455-f850-4e04-9365-f7e88528a637
		summarizeBy: sum
		sourceColumn: Forecast Orig Tot Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fore Orig Tot Lbr Hrs'
		dataType: double
		lineageTag: 55afdec7-b1f3-44f3-bc26-c5d75633db6d
		summarizeBy: sum
		sourceColumn: Fore Orig Tot Lbr Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Equipment'
		dataType: double
		lineageTag: 76275f47-6af2-4c66-8b20-e2385ae88e36
		summarizeBy: sum
		sourceColumn: Actual Equipment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor'
		dataType: double
		lineageTag: e375cb4e-12d2-4cb6-90a2-c20afe0b1765
		summarizeBy: sum
		sourceColumn: Actual Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Material'
		dataType: double
		lineageTag: b7c45d2e-9cb8-42e7-9d27-271614dafc85
		summarizeBy: sum
		sourceColumn: Actual Material

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Subs'
		dataType: double
		lineageTag: 6fcc9762-25df-4022-8961-8ecc852057c7
		summarizeBy: sum
		sourceColumn: Actual Subs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Other'
		dataType: double
		lineageTag: 15a8df9e-5f5c-4054-a5fc-2300264453cc
		summarizeBy: sum
		sourceColumn: Actual Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Cost Tax'
		dataType: double
		lineageTag: 238dcf3e-b08b-4604-b2fc-5aaebf4bf8b9
		summarizeBy: sum
		sourceColumn: Total Cost Tax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Total Cost'
		dataType: double
		lineageTag: adc86cee-8b5b-4af0-bbc4-e0c3e32dcc29
		summarizeBy: sum
		sourceColumn: Actual Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Hours'
		dataType: double
		lineageTag: 97cb0273-e84d-4107-bb25-8cd63810507c
		summarizeBy: sum
		sourceColumn: Actual Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 1'
		dataType: double
		lineageTag: e2fce2cf-f3c4-454c-99c8-3c6e33206b41
		summarizeBy: sum
		sourceColumn: Actual Labor 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 1 Hours Repair'
		dataType: double
		lineageTag: e71ffc1b-4e7c-4cbf-9f5d-49a7da19e1a9
		summarizeBy: sum
		sourceColumn: Actual Labor 1 Hours Repair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 2'
		dataType: double
		lineageTag: ccce72c5-2ab6-439e-a27f-42f90a0f9c6c
		summarizeBy: sum
		sourceColumn: Actual Labor 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 2 Hours Pm'
		dataType: double
		lineageTag: bd9b1ba5-2473-4c8c-b6c8-31931e9013fc
		summarizeBy: sum
		sourceColumn: Actual Labor 2 Hours Pm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 3'
		dataType: double
		lineageTag: d20fece8-edbf-42ce-8e24-18ea61a5ed35
		summarizeBy: sum
		sourceColumn: Actual Labor 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 3 Hours Travel'
		dataType: double
		lineageTag: 24c89442-5ed8-409a-a603-0e0f41838b1a
		summarizeBy: sum
		sourceColumn: Actual Labor 3 Hours Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 4'
		dataType: double
		lineageTag: e9b88e1f-0c62-4292-a129-1fb94da1ec65
		summarizeBy: sum
		sourceColumn: Actual Labor 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 4 Hours'
		dataType: double
		lineageTag: c4499ccf-680d-45a3-b9d2-26a857ad14fe
		summarizeBy: sum
		sourceColumn: Actual Labor 4 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 5'
		dataType: double
		lineageTag: d86e98d4-4238-4377-9dca-a897b60262c0
		summarizeBy: sum
		sourceColumn: Actual Labor 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Labor 5 Hours'
		dataType: double
		lineageTag: 07bb92d6-12e0-44e1-aef1-a9305e29f2e4
		summarizeBy: sum
		sourceColumn: Actual Labor 5 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Total Labor'
		dataType: double
		lineageTag: 2331af97-47af-4100-b369-d129538a4a0f
		summarizeBy: sum
		sourceColumn: Actual Total Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Total Labor Hrs'
		dataType: double
		lineageTag: 5c513b88-3d83-4666-b848-073624c85709
		summarizeBy: sum
		sourceColumn: Actual Total Labor Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Contract Earned'
		dataType: double
		lineageTag: edb5d47b-1c1d-49eb-a467-3c09c76aab37
		summarizeBy: sum
		sourceColumn: Actual Contract Earned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Gross Profit'
		dataType: double
		lineageTag: 52cf133f-39a8-434e-a2c1-795b8dacee2d
		summarizeBy: sum
		sourceColumn: Actual Gross Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actua Revenue Recognized'
		dataType: double
		lineageTag: 9401d67a-6fcf-4c82-b466-68bd7ae015cd
		summarizeBy: sum
		sourceColumn: Actua Revenue Recognized

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Billed'
		dataType: double
		lineageTag: 2f8e3f05-0f6a-490b-b9b7-f10b42e71d9f
		summarizeBy: sum
		sourceColumn: Actual Billed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Equipment'
		dataType: double
		lineageTag: 84936d51-4608-49d7-b844-788aa604edd2
		summarizeBy: sum
		sourceColumn: Estimate Equipment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor'
		dataType: double
		lineageTag: 273f6003-82d5-46fc-a3a6-7c3e78c344bc
		summarizeBy: sum
		sourceColumn: Estimate Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Material'
		dataType: double
		lineageTag: 3efd86a6-5c76-40ba-b214-fa32e8ee3c31
		summarizeBy: sum
		sourceColumn: Estimate Material

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Subs'
		dataType: double
		lineageTag: 4be47094-38de-4396-bd8c-7504fbc6756b
		summarizeBy: sum
		sourceColumn: Estimate Subs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Other'
		dataType: double
		lineageTag: d92fc63b-3d4e-40a6-a0fe-0b48fb52bede
		summarizeBy: sum
		sourceColumn: Estimate Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Total Cost'
		dataType: double
		lineageTag: 0d0b2bc2-ac00-495b-94c3-27cf79fc3c89
		summarizeBy: sum
		sourceColumn: Estimate Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Hours'
		dataType: double
		lineageTag: b869ba35-d4d1-4f61-9b83-d47f46471fdb
		summarizeBy: sum
		sourceColumn: Estimate Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 1'
		dataType: double
		lineageTag: 46ebf1e7-f5a2-4f83-887e-cfb64b095c1b
		summarizeBy: sum
		sourceColumn: Estimate Labor 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 1 Hours Repair'
		dataType: double
		lineageTag: d0c8d276-0d5a-444b-8ff1-e75b6af493b0
		summarizeBy: sum
		sourceColumn: Estimate Labor 1 Hours Repair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 2'
		dataType: double
		lineageTag: 9622246b-b658-404b-bcbf-48ae39422aa6
		summarizeBy: sum
		sourceColumn: Estimate Labor 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 2 Hours Pm'
		dataType: double
		lineageTag: c06f00d6-417e-4a53-a591-3ab1a4670ccf
		summarizeBy: sum
		sourceColumn: Estimate Labor 2 Hours Pm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 3'
		dataType: double
		lineageTag: 54bc4c25-58a6-45cb-b639-f7b516e2df32
		summarizeBy: sum
		sourceColumn: Estimate Labor 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 3 Hours Travel'
		dataType: double
		lineageTag: 0cce800f-2d91-4374-b092-188bfb381571
		summarizeBy: sum
		sourceColumn: Estimate Labor 3 Hours Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 4'
		dataType: double
		lineageTag: 11591dab-4ad6-48d8-8c14-5ef5143e72e5
		summarizeBy: sum
		sourceColumn: Estimate Labor 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 4 Hours'
		dataType: double
		lineageTag: 6b264e8e-b56c-452c-bb39-14bdd7e8572e
		summarizeBy: sum
		sourceColumn: Estimate Labor 4 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 5'
		dataType: double
		lineageTag: 3bdc9f78-6522-415a-9ffb-b3a7c544f301
		summarizeBy: sum
		sourceColumn: Estimate Labor 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Labor 5 Hours'
		dataType: double
		lineageTag: f3aaa4ab-3d9b-4058-bed8-7dc5b346572a
		summarizeBy: sum
		sourceColumn: Estimate Labor 5 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Total Labor'
		dataType: double
		lineageTag: 8765cd96-3b4b-42f9-b44d-bbb818aa2a36
		summarizeBy: sum
		sourceColumn: Estimate Total Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimate Total Labor Hrs'
		dataType: double
		lineageTag: f4d633f1-7523-45f3-bd3f-0b6771a70f18
		summarizeBy: sum
		sourceColumn: Estimate Total Labor Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor'
		dataType: double
		lineageTag: 7e7c4455-9e71-40ef-9ffb-27c2fe85900d
		summarizeBy: sum
		sourceColumn: Forecast Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Equipment'
		dataType: double
		lineageTag: 5789f5b1-fab9-4095-9326-9c0d1c54bed0
		summarizeBy: sum
		sourceColumn: Forecast Equipment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Material'
		dataType: double
		lineageTag: 110df821-0442-4e31-8ebf-dc45c3999d77
		summarizeBy: sum
		sourceColumn: Forecast Material

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Subs'
		dataType: double
		lineageTag: 1c085f0d-102d-4c31-a1aa-3426ecb1e1c5
		summarizeBy: sum
		sourceColumn: Forecast Subs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Other'
		dataType: double
		lineageTag: ccc27f52-79d4-41f2-b4ea-794d32935f11
		summarizeBy: sum
		sourceColumn: Forecast Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Total Cost'
		dataType: double
		lineageTag: 28759f51-c1f4-4139-9e9e-66e3d22c4ba7
		summarizeBy: sum
		sourceColumn: Forecast Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Hours'
		dataType: double
		lineageTag: 88e03ac3-9c7b-40d6-a100-8d5ca0a0302a
		summarizeBy: sum
		sourceColumn: Forecast Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 1'
		dataType: double
		lineageTag: 42cee325-e353-48fe-855a-31b570ffcec5
		summarizeBy: sum
		sourceColumn: Forecast Labor 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 1 Hours Repair'
		dataType: double
		lineageTag: a1812aba-e893-4ab1-891d-8deb5940df81
		summarizeBy: sum
		sourceColumn: Forecast Labor 1 Hours Repair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 2'
		dataType: double
		lineageTag: abced836-3cfc-49b1-bcef-0ced5c844800
		summarizeBy: sum
		sourceColumn: Forecast Labor 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 2 Hours Pm'
		dataType: double
		lineageTag: d244b284-6782-4610-9ba1-c3d7f5c2a156
		summarizeBy: sum
		sourceColumn: Forecast Labor 2 Hours Pm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 3'
		dataType: double
		lineageTag: 9687cf1d-dc9c-4d3d-a8e7-8f8fc1ac43d9
		summarizeBy: sum
		sourceColumn: Forecast Labor 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 3 Hours Travel'
		dataType: double
		lineageTag: 04fb744d-0988-442d-94a9-56f6285e66e2
		summarizeBy: sum
		sourceColumn: Forecast Labor 3 Hours Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 4'
		dataType: double
		lineageTag: c7fabb69-cf3a-439d-ad98-edd77a720448
		summarizeBy: sum
		sourceColumn: Forecast Labor 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 4 Hours'
		dataType: double
		lineageTag: d81fd371-bdf7-4051-914d-1adf2b2dda9b
		summarizeBy: sum
		sourceColumn: Forecast Labor 4 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 5'
		dataType: double
		lineageTag: bc28f602-af3b-4d39-b8a7-423438287eec
		summarizeBy: sum
		sourceColumn: Forecast Labor 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Labor 5 Hours'
		dataType: double
		lineageTag: b1622b70-792e-41c4-bfc8-20b64ec15919
		summarizeBy: sum
		sourceColumn: Forecast Labor 5 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Total Labor'
		dataType: double
		lineageTag: d39b798e-3fd1-45c1-8b1a-8b61944dac4a
		summarizeBy: sum
		sourceColumn: Forecast Total Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Total Labor Hrs'
		dataType: double
		lineageTag: cab96abc-77b8-44bf-9af3-11f18cc5ce49
		summarizeBy: sum
		sourceColumn: Forecast Total Labor Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor'
		dataType: double
		lineageTag: 10bce7da-2e5c-4d71-a8cd-0a5863169032
		summarizeBy: sum
		sourceColumn: Py Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Material'
		dataType: double
		lineageTag: 5a7f923a-5bc3-44c0-aa71-29ef6bf60611
		summarizeBy: sum
		sourceColumn: Py Material

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Equipment'
		dataType: double
		lineageTag: 9d4ea815-acfa-4569-b09b-6b2e69f8cd7a
		summarizeBy: sum
		sourceColumn: Py Equipment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Subcontractor'
		dataType: double
		lineageTag: e8eee952-d8da-48c7-82ac-0cbc3356590d
		summarizeBy: sum
		sourceColumn: Py Subcontractor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Other'
		dataType: double
		lineageTag: 9b0e4eaa-8cae-4bdf-a879-36e62c36a9f8
		summarizeBy: sum
		sourceColumn: Py Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Total Cost'
		dataType: double
		lineageTag: bd03b121-7fc5-47c8-8914-6c9fbb3da724
		summarizeBy: sum
		sourceColumn: Py Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Billed'
		dataType: double
		lineageTag: 0996b4ab-dc7a-4b85-87ae-c223a5913194
		summarizeBy: sum
		sourceColumn: Py Billed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Contract Earned'
		dataType: double
		lineageTag: 8b73ee40-3bd4-43aa-be05-e41342daa203
		summarizeBy: sum
		sourceColumn: Py Contract Earned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Gross Profit'
		dataType: double
		lineageTag: 7b5f67e3-3159-4e01-a6ff-f24b7fba0831
		summarizeBy: sum
		sourceColumn: Py Gross Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Revenue Recognized'
		dataType: double
		lineageTag: 17a51029-18d5-4c75-9391-bad24e3ab444
		summarizeBy: sum
		sourceColumn: Py Revenue Recognized

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Hours'
		dataType: double
		lineageTag: 58c3bce7-ed01-47fe-b1df-d09a5edff243
		summarizeBy: sum
		sourceColumn: Py Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 1'
		dataType: double
		lineageTag: 838c8649-5f93-4847-a352-21e331f137f1
		summarizeBy: sum
		sourceColumn: Py Labor 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 1 Hours Repair'
		dataType: double
		lineageTag: e75fa692-5585-48d2-978c-b995ef635b01
		summarizeBy: sum
		sourceColumn: Py Labor 1 Hours Repair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 2'
		dataType: double
		lineageTag: 382b8fac-2dbd-4381-870b-ea6f4cd5d540
		summarizeBy: sum
		sourceColumn: Py Labor 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 2 Hours Pm'
		dataType: double
		lineageTag: 6e99a17b-cffd-47ed-b24b-15b3a076c4a1
		summarizeBy: sum
		sourceColumn: Py Labor 2 Hours Pm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 3'
		dataType: double
		lineageTag: cf370973-9129-4001-93cf-ee35f0c7a62a
		summarizeBy: sum
		sourceColumn: Py Labor 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 3 Hours Travel'
		dataType: double
		lineageTag: c92a9bb2-df51-4bfe-939f-83dd90e20021
		summarizeBy: sum
		sourceColumn: Py Labor 3 Hours Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 4'
		dataType: double
		lineageTag: d61718dc-a963-4d61-8512-deb1c4529a6d
		summarizeBy: sum
		sourceColumn: Py Labor 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 4 Hours'
		dataType: double
		lineageTag: 8d2ba4c0-bf82-40a5-9818-238175f67ba1
		summarizeBy: sum
		sourceColumn: Py Labor 4 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 5'
		dataType: double
		lineageTag: 714b59d2-2b4c-4283-ba60-5bdf2db8f866
		summarizeBy: sum
		sourceColumn: Py Labor 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Labor 5 Hours'
		dataType: double
		lineageTag: 6b8cb418-a672-4c49-aaca-d782beacc302
		summarizeBy: sum
		sourceColumn: Py Labor 5 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Total Labor'
		dataType: double
		lineageTag: 0398db62-ccca-475b-afaa-576a83b3d15b
		summarizeBy: sum
		sourceColumn: Py Total Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Py Total Labor Hrs'
		dataType: double
		lineageTag: 7ae28ab3-a194-4310-9fdd-24bcbd94ba0d
		summarizeBy: sum
		sourceColumn: Py Total Labor Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor'
		dataType: double
		lineageTag: 884b33cd-0fc1-4684-8954-1bf4135b614a
		summarizeBy: sum
		sourceColumn: Ytd Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Material'
		dataType: double
		lineageTag: 719bc731-6c34-40af-b64b-ca218b2baa44
		summarizeBy: sum
		sourceColumn: Ytd Material

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Equipment'
		dataType: double
		lineageTag: a8cccf35-1edc-4863-aeb7-4af638644437
		summarizeBy: sum
		sourceColumn: Ytd Equipment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Subcontractor'
		dataType: double
		lineageTag: c3762ec8-d9b8-4f96-8a6a-53934a3df7f9
		summarizeBy: sum
		sourceColumn: Ytd Subcontractor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Other'
		dataType: double
		lineageTag: 9546f311-474e-4108-a94b-cf6363d92550
		summarizeBy: sum
		sourceColumn: Ytd Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Total Cost'
		dataType: double
		lineageTag: 395f697a-bc10-475f-908c-a9593299562c
		summarizeBy: sum
		sourceColumn: Ytd Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Billed'
		dataType: double
		lineageTag: b783e2f5-af47-4914-bbb6-c1b5f7aaa372
		summarizeBy: sum
		sourceColumn: Ytd Billed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Contract Earned'
		dataType: double
		lineageTag: 0772f914-10a6-4f35-a6b9-becf3af7e40e
		summarizeBy: sum
		sourceColumn: Ytd Contract Earned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Gross Profit'
		dataType: double
		lineageTag: 21294bd3-a25c-405d-b0e6-b715ad75c7ae
		summarizeBy: sum
		sourceColumn: Ytd Gross Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Revenue Recognized'
		dataType: double
		lineageTag: c9ea3eb3-131d-4174-89fe-9f93010b39bd
		summarizeBy: sum
		sourceColumn: Ytd Revenue Recognized

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ytdhours
		dataType: double
		lineageTag: fe871aa7-e0c6-416f-9d1e-b5bd99ab00dd
		summarizeBy: sum
		sourceColumn: Ytdhours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 1'
		dataType: double
		lineageTag: ba40daae-9eed-4142-943b-3e4766a743ea
		summarizeBy: sum
		sourceColumn: Ytd Labor 1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 1 Hours Repair'
		dataType: double
		lineageTag: 511f1c7e-9975-4ce0-befa-32ed7d1e2e3d
		summarizeBy: sum
		sourceColumn: Ytd Labor 1 Hours Repair

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 2'
		dataType: double
		lineageTag: 784ec77d-387f-443f-83b8-65476631a260
		summarizeBy: sum
		sourceColumn: Ytd Labor 2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 2 Hours Pm'
		dataType: double
		lineageTag: 01114335-528d-43a1-ae46-c0140c7b4d19
		summarizeBy: sum
		sourceColumn: Ytd Labor 2 Hours Pm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 3'
		dataType: double
		lineageTag: 304976c1-f65a-4e78-8e05-f40e99e32463
		summarizeBy: sum
		sourceColumn: Ytd Labor 3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 3 Hours Travel'
		dataType: double
		lineageTag: 17cc84be-9fe9-45c9-878e-3c9d422b7a8a
		summarizeBy: sum
		sourceColumn: Ytd Labor 3 Hours Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 4'
		dataType: double
		lineageTag: bca68282-dcc5-4e79-8e7c-08d93054c852
		summarizeBy: sum
		sourceColumn: Ytd Labor 4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 4 Hours'
		dataType: double
		lineageTag: 503b2ea8-d54b-4563-a82c-48d8d3aa0d5c
		summarizeBy: sum
		sourceColumn: Ytd Labor 4 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 5'
		dataType: double
		lineageTag: c350f38b-00e5-47a8-998b-dc8b9d4ba4ef
		summarizeBy: sum
		sourceColumn: Ytd Labor 5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Labor 5 Hours'
		dataType: double
		lineageTag: 963eac2c-2d23-4cbb-810a-46b3f05d8709
		summarizeBy: sum
		sourceColumn: Ytd Labor 5 Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Total Labor'
		dataType: double
		lineageTag: 22b77ac5-0815-4750-82ba-6ea5130c5ba9
		summarizeBy: sum
		sourceColumn: Ytd Total Labor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ytd Total Labor Hrs'
		dataType: double
		lineageTag: daf7b9c0-b8bb-4e85-98bd-87c687f4f768
		summarizeBy: sum
		sourceColumn: Ytd Total Labor Hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'User Define 1A Person'
		dataType: string
		lineageTag: 6d29b159-e5b6-4125-8855-9c485ab50a43
		summarizeBy: none
		sourceColumn: User Define 1A Person

		annotation SummarizationSetBy = Automatic

	column 'User Define 2A Completed'
		dataType: string
		lineageTag: 1b8d5f08-d3c7-4cb7-9c06-10d1ff9fa1fe
		summarizeBy: none
		sourceColumn: User Define 2A Completed

		annotation SummarizationSetBy = Automatic

	column 'User Define 3A Status'
		dataType: string
		lineageTag: 6c36f073-0e64-4522-b58d-121b49160965
		summarizeBy: none
		sourceColumn: User Define 3A Status

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 88b03851-a8d2-4e9b-a0df-18141433130a
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'Contract Number Key'
		dataType: string
		lineageTag: 75671108-3bee-4a8a-ac35-a74c6d802da3
		summarizeBy: none
		sourceColumn: Contract Number Key

		annotation SummarizationSetBy = Automatic

	column 'Custnmbr Key'
		dataType: string
		lineageTag: 93ed7bc3-17a1-4b28-a990-82ca370e916f
		summarizeBy: none
		sourceColumn: Custnmbr Key

		annotation SummarizationSetBy = Automatic

	partition CONTRACTS_D = m
		mode: import
		queryGroup: Staging
		source = ```
				let
				    Source = Snowflake.Databases("ufwarhx-qo50284.snowflakecomputing.com", "COMPUTE_WH", []),
				    DATA_WAREHOUSE_Database = Source{[Name="DATA_WAREHOUSE",Kind="Database"]}[Data],
				    DW_FINAL_Schema = DATA_WAREHOUSE_Database{[Name="DW_FINAL",Kind="Schema"]}[Data],
				    CUSTOMERS_D_Table = DW_FINAL_Schema{[Name="CONTRACTS_D",Kind="Table"]}[Data], 
				    ProperCase = Table.RenameColumns(CUSTOMERS_D_Table, List.Transform(Table.ColumnNames(CUSTOMERS_D_Table), each {_, Text.Proper(Text.Replace(_, "_", " "))})),
				    #"Trimmed Text" = Table.TransformColumns(ProperCase,{{"Divisions", Text.Trim, type text}})
				in
				    #"Trimmed Text"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

