DEFINE
    MEASURE '_Key Measures'[Service Contract Gross Profit] = [Service Contract Revenue] - [Service Contract Cost]
    MEASURE '_Key Measures'[Service Contract Gross Profit %] = DIVIDE(
			[Service Contract Gross Profit],
			[Service Contract Revenue]
		)
    MEASURE '_Key Measures'[Project Revenue] = SUM(PROJECT_REVENUE_F[Amount])
    MEASURE '_Key Measures'[Project Cost] = SUM(PROJECT_COSTS_F[Amount])
    MEASURE '_Key Measures'[Project GP] = [Project Revenue] - [Project Cost]
    MEASURE '_Key Measures'[Project GP %] = DIVIDE(
			[Project GP],
			[Project Revenue]
		)
    MEASURE '_Key Measures'[Project GP % (Formatted)] = FORMAT(
			[Project GP %],
			"0.0%"
		)
    MEASURE '_Key Measures'[Service Contract Cost] = SUM(SERVCONTRACTS_COSTS_F[Amount])
    MEASURE '_Key Measures'[Service Contract Revenue] = SUM(SERVCONTRACTS_REVENUE_F[Amount])
    MEASURE '_Key Measures'[Check_Source_Calls] = SUM('CALLS_F'[Cost All])
    MEASURE '_Key Measures'[Check_Dest_Total] = CALCULATE(SUM('PROJECT_COSTS_F'[Amount]), 'PROJECT_COSTS_F'[Source Type] = "Service Call Cost") + SUM('SERVCONTRACTS_COSTS_F'[Amount]) + SUM('SPOT_FINANCIALS_F'[Cost])
    MEASURE '_Key Measures'[Check_Variance] = [Check_Source_Calls] - [Check_Dest_Total]
    MEASURE '_Key Measures'[Spot Revenue] = SUM(SPOT_FINANCIALS_F[Revenue])
    MEASURE '_Key Measures'[Spot Gross Profit] = [Spot Revenue] - [Spot Cost]
    MEASURE '_Key Measures'[Spot GP %] = DIVIDE(
			[Spot Gross Profit],
			[Spot Revenue]
		)
    MEASURE '_Key Measures'[Check_Source_Revenue_Total] = VAR JobRevenue = SUM('JOB_MONTHLY_SUMMARY_F'[Contract Earned Curr Mo])
VAR ContractBillingRevenue = SUM('CONTRACT_BILLABLE_F'[BILLABLE_ALL])
VAR SpotCallsRevenue = CALCULATE(SUM('CALLS_F'[Billable All]), 'CALLS_F'[Contract Number] = BLANK() || 'CALLS_F'[Contract Number] = "")

RETURN
    JobRevenue + ContractBillingRevenue + SpotCallsRevenue
    MEASURE '_Key Measures'[Check_Dest_Revenue_Total] = VAR ProjectRev = SUM('PROJECT_REVENUE_F'[Amount])
VAR ContractRev = SUM('SERVCONTRACTS_REVENUE_F'[Amount])
VAR SpotRev = SUM('SPOT_FINANCIALS_F'[Revenue])

RETURN
    ProjectRev + ContractRev + SpotRev
    MEASURE '_Key Measures'[Check_Revenue_Variance] = [Check_Source_Revenue_Total] - [Check_Dest_Revenue_Total]
    MEASURE '_Key Measures'[Spot Cost] = SUM( SPOT_FINANCIALS_F[Cost])
    MEASURE '_Key Measures'[Total Revenue] = [Project Revenue] + [Service Contract Revenue] + [Spot Revenue]
    MEASURE '_Key Measures'[Total Cost] = [Project Cost] + [Service Contract Cost] + [Spot Cost]
    MEASURE '_Key Measures'[Total Gross Profit] = [Total Revenue] - [Total Cost]
    MEASURE '_Key Measures'[Total GP %] = DIVIDE(
	[Total Gross Profit],
	[Total Revenue]
)

EVALUATE
    SUMMARIZECOLUMNS(
        "Service Contract Gross Profit", [Service Contract Gross Profit],
        "Service Contract Gross Profit %", [Service Contract Gross Profit %],
        "Project Revenue", [Project Revenue],
        "Project Cost", [Project Cost],
        "Project GP", [Project GP],
        "Project GP %", [Project GP %],
        "Project GP % (Formatted)", [Project GP % (Formatted)],
        "Service Contract Cost", [Service Contract Cost],
        "Service Contract Revenue", [Service Contract Revenue],
        "Check_Source_Calls", [Check_Source_Calls],
        "Check_Dest_Total", [Check_Dest_Total],
        "Check_Variance", [Check_Variance],
        "Spot Revenue", [Spot Revenue],
        "Spot Gross Profit", [Spot Gross Profit],
        "Spot GP %", [Spot GP %],
        "Check_Source_Revenue_Total", [Check_Source_Revenue_Total],
        "Check_Dest_Revenue_Total", [Check_Dest_Revenue_Total],
        "Check_Revenue_Variance", [Check_Revenue_Variance],
        "Spot Cost", [Spot Cost],
        "Total Revenue", [Total Revenue],
        "Total Cost", [Total Cost],
        "Total Gross Profit", [Total Gross Profit],
        "Total GP %", [Total GP %]
    )