DEFINE
	MEASURE '_Key Measures'[Service Contract Gross Profit] = [Service Contract Revenue] - [Service Contract Cost]
	MEASURE '_Key Measures'[Service Contract Gross Profit %] = DIVIDE(
			[Service Contract Gross Profit],
			[Service Contract Revenue]
		)
	MEASURE '_Key Measures'[Project Revenue] = SUM(PROJECT_REVENUE_F[Amount])
	MEASURE '_Key Measures'[Project Cost] = SUM(PROJECT_COSTS_F[Amount])
	MEASURE '_Key Measures'[Project GP] = [Project Revenue] - [Project Cost]
	MEASURE '_Key Measures'[Project GP %] = DIVIDE(
			[Project GP],
			[Project Revenue]
		)
	MEASURE '_Key Measures'[Project GP % (Formatted)] = FORMAT(
			[Project GP %],
			"0.0%"
		)
	MEASURE '_Key Measures'[Service Contract Cost] = SUM(SERVCONTRACTS_COSTS_F[Amount])
	MEASURE '_Key Measures'[Service Contract Revenue] = SUM(SERVCONTRACTS_REVENUE_F[Amount])
	MEASURE '_Key Measures'[Check_Source_Calls] = SUM('CALLS_F'[Cost All])
	MEASURE '_Key Measures'[Check_Dest_Total] = CALCULATE(
			SUM('PROJECT_COSTS_F'[Amount]),
			'PROJECT_COSTS_F'[Source Type] = "Service Call Cost"
		) + SUM('SERVCONTRACTS_COSTS_F'[Amount]) + SUM('SPOT_FINANCIALS_F'[Cost])
	MEASURE '_Key Measures'[Check_Variance] = [Check_Source_Calls] - [Check_Dest_Total]
	MEASURE '_Key Measures'[T&M Revenue] = SUM(SPOT_FINANCIALS_F[Revenue])
	MEASURE '_Key Measures'[T&M Gross Profit] = [T&M Revenue] - [T&M Cost]
	MEASURE '_Key Measures'[T&M GP %] = DIVIDE(
			[T&M Gross Profit],
			[T&M Revenue]
		)
	MEASURE '_Key Measures'[Check_Source_Revenue_Total] = VAR JobRevenue = SUM('JOB_MONTHLY_SUMMARY_F'[Contract Earned Curr Mo])
		VAR ContractBillingRevenue = SUM('CONTRACT_BILLABLE_F'[BILLABLE_ALL])
		VAR SpotCallsRevenue = CALCULATE(
			SUM('CALLS_F'[Billable All]),
			'CALLS_F'[Contract Number] = BLANK() || 'CALLS_F'[Contract Number] = ""
		)

		RETURN
			JobRevenue + ContractBillingRevenue + SpotCallsRevenue
	MEASURE '_Key Measures'[Check_Dest_Revenue_Total] = VAR ProjectRev = SUM('PROJECT_REVENUE_F'[Amount])
		VAR ContractRev = SUM('SERVCONTRACTS_REVENUE_F'[Amount])
		VAR SpotRev = SUM('SPOT_FINANCIALS_F'[Revenue])

		RETURN
			ProjectRev + ContractRev + SpotRev
	MEASURE '_Key Measures'[Check_Revenue_Variance] = [Check_Source_Revenue_Total] - [Check_Dest_Revenue_Total]
	MEASURE '_Key Measures'[T&M Cost] = SUM(SPOT_FINANCIALS_F[Cost])
	MEASURE '_Key Measures'[Total Revenue] = [Project Revenue] + [Service Contract Revenue] + [T&M Revenue]
	MEASURE '_Key Measures'[Total Cost] = [Project Cost] + [Service Contract Cost] + [T&M Cost]
	MEASURE '_Key Measures'[Total Gross Profit] = [Total Revenue] - [Total Cost]
	MEASURE '_Key Measures'[Total GP %] = DIVIDE(
			[Total Gross Profit],
			[Total Revenue]
		)
	MEASURE '_Key Measures'[Has Revenue or Cost] = VAR Rev = [Total Revenue]
		VAR Cost = [Total Cost]
		RETURN
			IF(
				COALESCE(
					Rev,
					0
				) <> 0
				|| COALESCE(
					Cost,
					0
				) <> 0,
				1,
				0
			)
    //============================================================
    // STREAM-BASED REVENUE
    //============================================================
    MEASURE '_Key Measures'[Revenue (By Stream)] =
        VAR Stream =
            SELECTEDVALUE ( Revenue_Stream_D[Revenue Stream] )
        RETURN
            SWITCH (
                Stream,
                "Project", [Project Revenue],
                "Service Contract", [Service Contract Revenue],
                "T&M", [T&M Revenue],
                BLANK()
            )

    //============================================================
    // STREAM-BASED COST
    //============================================================
    MEASURE '_Key Measures'[Cost (By Stream)] =
        VAR Stream =
            SELECTEDVALUE ( Revenue_Stream_D[Revenue Stream] )
        RETURN
            SWITCH (
                Stream,
                "Project", [Project Cost],
                "Service Contract", [Service Contract Cost],
                "T&M", [T&M Cost],
                BLANK()
            )

    //============================================================
    // STREAM-BASED GROSS PROFIT
    //============================================================
    MEASURE '_Key Measures'[Gross Profit (By Stream)] =
        [Revenue (By Stream)] - [Cost (By Stream)]

    //============================================================
    // GP % WITHIN STREAM
    //============================================================
    MEASURE '_Key Measures'[GP % (By Stream)] =
        DIVIDE (
            [Gross Profit (By Stream)],
            [Revenue (By Stream)]
        )

    //============================================================
    // PERCENT OF TOTALS
    //============================================================
    MEASURE '_Key Measures'[Revenue % of Total] =
        DIVIDE (
            [Revenue (By Stream)],
            [Total Revenue]
        )

    MEASURE '_Key Measures'[Cost % of Total] =
        DIVIDE (
            [Cost (By Stream)],
            [Total Cost]
        )

    MEASURE '_Key Measures'[GP % of Total Revenue] =
        DIVIDE (
            [Gross Profit (By Stream)],
            [Total Revenue]
        )

EVALUATE
	SUMMARIZECOLUMNS(
		"Service Contract Gross Profit", [Service Contract Gross Profit],
		"Service Contract Gross Profit %", [Service Contract Gross Profit %],
		"Project Revenue", [Project Revenue],
		"Project Cost", [Project Cost],
		"Project GP", [Project GP],
		"Project GP %", [Project GP %],
		"Project GP % (Formatted)", [Project GP % (Formatted)],
		"Service Contract Cost", [Service Contract Cost],
		"Service Contract Revenue", [Service Contract Revenue],
		"Check_Source_Calls", [Check_Source_Calls],
		"Check_Dest_Total", [Check_Dest_Total],
		"Check_Variance", [Check_Variance],
		"T&M Revenue", [T&M Revenue],
		"T&M Gross Profit", [T&M Gross Profit],
		"T&M GP %", [T&M GP %],
		"Check_Source_Revenue_Total", [Check_Source_Revenue_Total],
		"Check_Dest_Revenue_Total", [Check_Dest_Revenue_Total],
		"Check_Revenue_Variance", [Check_Revenue_Variance],
		"T&M Cost", [T&M Cost],
		"Total Revenue", [Total Revenue],
		"Total Cost", [Total Cost],
		"Total Gross Profit", [Total Gross Profit],
		"Total GP %", [Total GP %],
		"Has Revenue or Cost", [Has Revenue or Cost]
	)