table FYCALENDAR_D
	lineageTag: 32c90cf9-821d-4366-9844-e94253d86364
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: d242d646-e192-4ee2-8650-d94906787914
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 40ffffd7-2e0e-4f6b-969a-509d0cee3995
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = User

	column 'Fiscal Year Label'
		dataType: string
		lineageTag: 6be33bf3-3e6d-4b32-9355-5884cd28cf30
		summarizeBy: none
		sourceColumn: Fiscal Year Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Default'
		dataType: string
		lineageTag: 3d897ac4-0d78-4e3b-aaaa-7897c7df4c01
		summarizeBy: none
		sourceColumn: Fiscal Year Default

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Start Of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ab14d91-1364-49e6-bc2c-cab3b5b67715
		summarizeBy: none
		sourceColumn: Fiscal Start Of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal End Of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 877df2ca-f514-495e-a4df-dff01a17cb83
		summarizeBy: none
		sourceColumn: Fiscal End Of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Day Of Year'
		dataType: int64
		formatString: 0
		lineageTag: 41305c0b-ba13-47e0-901e-b6ba623a35cb
		summarizeBy: sum
		sourceColumn: Fiscal Day Of Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Of Year'
		dataType: int64
		formatString: 0
		lineageTag: c10213a1-5346-4b34-ad50-1a42ab86cf62
		summarizeBy: sum
		sourceColumn: Fiscal Week Of Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Label'
		dataType: string
		lineageTag: 8927e235-d885-4ebc-ac0b-ee9386d9c990
		summarizeBy: none
		sourceColumn: Fiscal Week Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 4f496a5b-fe3f-4397-ac80-f6fd9c51e71c
		summarizeBy: sum
		sourceColumn: Fiscal Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: int64
		formatString: 0
		lineageTag: a867dcf4-bcd4-4810-9237-5ec10b90b6eb
		summarizeBy: sum
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Default'
		dataType: string
		lineageTag: 9d71155d-0af7-4f70-944e-b66aca47e457
		summarizeBy: none
		sourceColumn: Fiscal Month Default

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: ec732611-27f9-4889-8336-b339081fdf67
		summarizeBy: sum
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Label'
		dataType: string
		lineageTag: ded79d46-2c53-4e05-b0b6-889bf6b6efab
		summarizeBy: none
		sourceColumn: Fiscal Quarter Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Of Quarter'
		dataType: int64
		formatString: 0
		lineageTag: bee01632-693a-478f-81ff-92442cf2422f
		summarizeBy: sum
		sourceColumn: Fiscal Month Of Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Quarter Label'
		dataType: string
		lineageTag: 0a86122f-09cb-4a50-8948-dc8d202224a8
		summarizeBy: none
		sourceColumn: Fiscal Year Quarter Label
		sortByColumn: FiscalQuarterSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Start Of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f4c30abc-1d12-4e16-bb66-ea8ffb7d8f02
		summarizeBy: none
		sourceColumn: Fiscal Start Of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal End Of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c3b0861-4575-4be7-9c33-fc446c7d71fa
		summarizeBy: none
		sourceColumn: Fiscal End Of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: 55e218b6-20cc-4338-af4d-3bd732f76a6b
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Offset

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Month Label'
		dataType: string
		lineageTag: bf21e117-1eb0-4ae5-bfe9-dc05b16ff9ca
		summarizeBy: none
		sourceColumn: Fiscal Quarter Month Label
		sortByColumn: FiscalQuarterSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Day Of Quarter'
		dataType: int64
		formatString: 0
		lineageTag: f31b0090-28e0-4765-84a5-4c9f801cc5c1
		summarizeBy: sum
		sourceColumn: Fiscal Day Of Quarter

		annotation SummarizationSetBy = Automatic

	column 'Is Current Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 367490aa-68c2-4e3e-98cd-f006b6d7dab6
		summarizeBy: none
		sourceColumn: Is Current Month

		annotation SummarizationSetBy = Automatic

	column 'Is Current Calendar Year'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 837cf5c8-03a9-4339-a88f-0d8d6c308b3d
		summarizeBy: none
		sourceColumn: Is Current Calendar Year

		annotation SummarizationSetBy = Automatic

	column 'Is Current Fiscal Year'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 02791b0e-cd3e-4e7a-bd2d-b0824240356e
		summarizeBy: none
		sourceColumn: Is Current Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Week Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e2394512-bad3-4cdf-9a09-ad6542c5154d
		summarizeBy: none
		sourceColumn: Week Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Is Current Week'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e1e1f8b2-9c23-4ce2-bd7c-4f8aa75a2119
		summarizeBy: none
		sourceColumn: Is Current Week

		annotation SummarizationSetBy = Automatic

	column 'Is Previous Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26d072a2-1d1a-4387-9ff7-a3efa522bdfc
		summarizeBy: none
		sourceColumn: Is Previous Month

		annotation SummarizationSetBy = Automatic

	column 'Is Previous Fiscal Year'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 96b79469-f2b4-4bfd-935f-6592d3ed8b09
		summarizeBy: none
		sourceColumn: Is Previous Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Is Previous Week'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 89d0f343-981e-4ccd-b9e2-88a0c99010a5
		summarizeBy: none
		sourceColumn: Is Previous Week

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: f36c7c1f-bd9c-4324-bff6-12f07996a670
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Fiscal Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterSort = [Fiscal Year] * 10 + [Fiscal Quarter]
		formatString: 0
		lineageTag: e10acfe1-4ee6-4640-9d3c-776ce11d1fe0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Name'
		dataType: string
		lineageTag: a5afc927-ec40-4ea4-ad28-b3e72d611357
		summarizeBy: none
		sourceColumn: Fiscal Month Name

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Name Long'
		dataType: string
		lineageTag: 9fdea40f-8c3c-4209-9019-0f52a31212fe
		summarizeBy: none
		sourceColumn: Fiscal Month Name Long

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Name'
		dataType: string
		lineageTag: 3eba4cc8-a378-409a-8ca4-b3335679686f
		summarizeBy: none
		sourceColumn: Fiscal Week Name

		annotation SummarizationSetBy = Automatic

	column 'MMM Label'
		dataType: string
		lineageTag: 25868dd8-899a-4245-abd6-8dec654edac3
		summarizeBy: none
		sourceColumn: MMM Label
		sortByColumn: 'Fiscal Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Is Completed Month'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d062b90d-2bb7-47f9-8650-c086e34e3faf
		summarizeBy: none
		sourceColumn: Is Completed Month

		annotation SummarizationSetBy = Automatic

	column 'Is Completed Quarter'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 46b111a5-14eb-424e-98eb-e3c85c94d963
		summarizeBy: none
		sourceColumn: Is Completed Quarter

		annotation SummarizationSetBy = Automatic

	column 'Month Letter' =
			
			SWITCH(
			    MONTH('FYCALENDAR_D'[Date]),
			     1, "J",
			     2, "F",
			     3, "M",
			     4, "A",
			     5, "M" & UNICHAR(8201), //Second Occurence
			     6, "J" & UNICHAR(8202), //Second Occurence
			     7, "J" & UNICHAR(8201), //Third Occurence
			     8, "A" & UNICHAR(8201), //Second Occurence
			     9, "S",
			     10, "O",
			     11, "N",
			     12, "D"
			)
		lineageTag: 3115838b-8598-40a8-b08b-933d54fdd86d
		summarizeBy: none
		sortByColumn: 'Fiscal Month'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition FYCALENDAR_D = m
		mode: import
		queryGroup: Dim
		source = ```
				let
				    // The FiscalYearEnd determines in which month the fiscal year ends. If necessary you can adjust it. 
				    FiscalYearEnd = 9,
				
				    // Today is used throughout the fiscal logic and for determining current period flags
				    Today = Date.From(DateTime.LocalNow()),
				
				    // Sets the start date for your calendar
				    StartDate = #date(2000, 1, 1),
				
				    // The calendar runs until the end of the current year. Change this if you need your calendar to run to another date. 
				    EndDate = Date.AddYears(Date.EndOfYear(Today),1),
				
				    // The current Fiscal Year value is a helper value for other calculations
				    CurrentFiscalYear = Date.Year( Date.AddMonths( Today, 12 - FiscalYearEnd ) ),
				
				    ListOfDates =
				        List.Dates(
				            StartDate,
				            Duration.Days(EndDate - StartDate) + 1,
				            #duration(1, 0, 0, 0)
				        ),
				
				    MyDateTable =
				        Table.FromList(
				            ListOfDates,
				            Splitter.SplitByNothing(),
				            type table[Date = date],
				            null,
				            ExtraValues.Error
				        ),
				
				    Add_FiscalYearNumber =
				        Table.AddColumn(
				            MyDateTable,
				            "FiscalYear",
				            each Date.Year(Date.AddMonths([Date], 12 - FiscalYearEnd)),
				            Int64.Type
				        ),
				
				    Add_FiscalYearLabel =
				        Table.AddColumn(
				            Add_FiscalYearNumber,
				            "FiscalYearLabel",
				            each "FY" & Text.From([FiscalYear]),
				            Text.Type
				        ),
				
				    // Allows you to select the 'Current' or 'Previous' year dynamically. 
				    Add_FiscalYearDefault =
				        Table.AddColumn(
				            Add_FiscalYearLabel,
				            "FiscalYearDefault",
				            each
				                if [FiscalYear] = CurrentFiscalYear then "Current"
				                else if [FiscalYear] = (CurrentFiscalYear - 1) then "Previous"
				                else "FY" & Text.From([FiscalYear]),
				            Text.Type
				        ),
				
				    Add_FiscalStartOfYear =
				        Table.AddColumn(
				            Add_FiscalYearDefault,
				            "FiscalStartOfYear",
				            each [
				                Offset = if FiscalYearEnd = 12 then 0 else FiscalYearEnd - 12,
				                FiscalStartOfYear = Date.AddMonths(Date.StartOfYear([Date]), Offset)
				            ][FiscalStartOfYear],
				            Date.Type
				        ),
				
				    Add_FiscalEndOfYear =
				        Table.AddColumn(
				            Add_FiscalStartOfYear,
				            "FiscalEndOfYear",
				            each Date.AddMonths(Date.EndOfYear([Date]), FiscalYearEnd - 12),
				            Date.Type
				        ),
				
				    // -----------------------------------------------------
				    // Fiscal Day & Week of Fiscal Year
				    // -----------------------------------------------------
				
				    Add_FiscalDayOfYear =
				        Table.AddColumn(
				            Add_FiscalEndOfYear,
				            "FiscalDayOfYear",
				            each Number.From([Date] - [FiscalStartOfYear]) + 1,
				            Int64.Type
				        ),
				
				    Add_FiscalWeekOfYear =
				        Table.AddColumn(
				            Add_FiscalDayOfYear,
				            "FiscalWeekOfYear",
				            each Number.RoundUp([FiscalDayOfYear] / 7),
				            Int64.Type
				        ),
				
				    Add_FiscalWeekLabel =
				        Table.AddColumn(
				            Add_FiscalWeekOfYear,
				            "FiscalWeekLabel",
				            each
				                "FY" &
				                Text.From([FiscalYear]) &
				                " W" &
				                Text.PadStart(Text.From([FiscalWeekOfYear]), 2, "0"),
				            Text.Type
				        ),
				
				    // -----------------------------------------------------
				    // Continue existing logic
				    // -----------------------------------------------------
				
				    // A year Offset value indicates the relative position of the current year (based on today's date)
				    Add_FiscalYearOffset =
				        Table.AddColumn(
				            Add_FiscalWeekLabel,
				            "FiscalYearOffset",
				            each ([FiscalYear] - CurrentFiscalYear),
				            Int64.Type
				        ),
				
				    Add_FiscalMonthNumber =
				        Table.AddColumn(
				            Add_FiscalYearOffset,
				            "FiscalMonth",
				            each Date.Month(Date.AddMonths([Date], -FiscalYearEnd)),
				            Int64.Type
				        ),
				
				    // Allows you to select the 'Current' or 'Previous' month dynamically.
				    Add_FiscalMonthDefault =
				        Table.AddColumn(
				            Add_FiscalMonthNumber,
				            "FiscalMonthDefault",
				            each
				                if Date.IsInCurrentMonth([Date]) then "Current"
				                else if Date.IsInPreviousMonth([Date]) then "Previous"
				                else Text.From([FiscalMonth]),
				            Text.Type
				        ),
				
				    Add_FiscalQuarterNumber =
				        Table.AddColumn(
				            Add_FiscalMonthDefault,
				            "FiscalQuarter",
				            each Number.RoundUp([FiscalMonth] / 3),
				            Int64.Type
				        ),
				
				    Add_FiscalQuarterLabel =
				        Table.AddColumn(
				            Add_FiscalQuarterNumber,
				            "FiscalQuarterLabel",
				            each "FQ" & Text.From([FiscalQuarter]),
				            Text.Type
				        ),
				
				    Add_FiscalMonthOfQuarter =
				        Table.AddColumn(
				            Add_FiscalQuarterLabel,
				            "FiscalMonthOfQuarter",
				            each [FiscalMonth] - 3 * ([FiscalQuarter] - 1),
				            Int64.Type
				        ),
				
				    Add_FiscalYearQuarterLabel =
				        Table.AddColumn(
				            Add_FiscalMonthOfQuarter,
				            "FiscalYearQuarterLabel",
				            each "FY" & Text.From([FiscalYear]) & " Q" & Text.From([FiscalQuarter]),
				            Text.Type
				        ),
				
				    Add_FiscalStartOfQuarter =
				        Table.AddColumn(
				            Add_FiscalYearQuarterLabel,
				            "FiscalStartOfQuarter",
				            each Date.StartOfMonth(Date.AddMonths([Date], 1 - [FiscalMonthOfQuarter])),
				            Date.Type
				        ),
				
				    Add_FiscalEndOfQuarter =
				        Table.AddColumn(
				            Add_FiscalStartOfQuarter,
				            "FiscalEndOfQuarter",
				            each Date.EndOfMonth(Date.AddMonths([Date], 3 - [FiscalMonthOfQuarter])),
				            Date.Type
				        ),
				
				    // Quarter offset logic
				    Add_FiscalQuarterOffset =
				        Table.AddColumn(
				            Add_FiscalEndOfQuarter,
				            "FiscalQuarterOffset",
				            each [
				                CurrentFiscalMonth = Date.Month(Date.AddMonths(Today, -FiscalYearEnd)),
				                CurrentFiscalQuarter = Number.RoundUp(CurrentFiscalMonth / 3),
				                FiscalQuarterOffset =
				                    (([FiscalYear] - CurrentFiscalYear) * 4)
				                        + ([FiscalQuarter] - CurrentFiscalQuarter)
				            ][FiscalQuarterOffset],
				            Int64.Type
				        ),
				
				    Add_FiscalQuarterMonthLabel =
				        Table.AddColumn(
				            Add_FiscalQuarterOffset,
				            "FiscalQuarterMonthLabel",
				            each
				                "FQ"
				                    & Text.From([FiscalQuarter])
				                    & ": "
				                    & Date.ToText([FiscalStartOfQuarter], "MMM yyyy")
				                    & " - "
				                    & Date.ToText([FiscalEndOfQuarter], "MMM yyyy"),
				            Text.Type
				        ),
				
				    Add_FiscalDayOfQuarter =
				        Table.AddColumn(
				            Add_FiscalQuarterMonthLabel,
				            "FiscalDayOfQuarter",
				            each Number.From([Date] - [FiscalStartOfQuarter]) + 1,
				            Int64.Type
				        ),
				
				    // -----------------------------------------------------
				    // Current-period indicators
				    // -----------------------------------------------------
				
				    Add_IsCurrentMonth =
				        Table.AddColumn(
				            Add_FiscalDayOfQuarter,
				            "IsCurrentMonth",
				            each Date.Year([Date]) = Date.Year(Today)
				                and Date.Month([Date]) = Date.Month(Today),
				            type logical
				        ),
				
				    Add_IsCurrentCalendarYear =
				        Table.AddColumn(
				            Add_IsCurrentMonth,
				            "IsCurrentCalendarYear",
				            each Date.Year([Date]) = Date.Year(Today),
				            type logical
				        ),
				
				    Add_IsCurrentFiscalYear =
				        Table.AddColumn(
				            Add_IsCurrentCalendarYear,
				            "IsCurrentFiscalYear",
				            each [FiscalYear] = CurrentFiscalYear,
				            type logical
				        ),
				
				    CurrentWeekStart =
				        Date.AddDays(Today, 1 - Date.DayOfWeek(Today, Day.Monday)),
				
				    Add_WeekStart =
				        Table.AddColumn(
				            Add_IsCurrentFiscalYear,
				            "WeekStart",
				            each Date.AddDays([Date], 1 - Date.DayOfWeek([Date], Day.Monday)),
				            type date
				        ),
				
				    Add_IsCurrentWeek =
				        Table.AddColumn(
				            Add_WeekStart,
				            "IsCurrentWeek",
				            each [WeekStart] = CurrentWeekStart,
				            type logical
				        ),
				
				    // -----------------------------------------------------
				    // Previous-period indicators
				    // -----------------------------------------------------
				
				    Add_IsPreviousMonth =
				        Table.AddColumn(
				            Add_IsCurrentWeek,
				            "IsPreviousMonth",
				            each Date.IsInPreviousMonth([Date]),
				            type logical
				        ),
				
				    Add_IsPreviousFiscalYear =
				        Table.AddColumn(
				            Add_IsPreviousMonth,
				            "IsPreviousFiscalYear",
				            each [FiscalYear] = (CurrentFiscalYear - 1),
				            type logical
				        ),
				
				    PreviousWeekStart =
				        Date.AddDays(Today, 1 - Date.DayOfWeek(Today, Day.Monday) - 7),
				
				    Add_IsPreviousWeek =
				        Table.AddColumn(
				            Add_IsPreviousFiscalYear,
				            "IsPreviousWeek",
				            each [WeekStart] = PreviousWeekStart,
				            type logical
				        ),
				
				    // -----------------------------------------------------
				    // Column cleanup
				    // -----------------------------------------------------
				// -----------------------------------------------------
				// Additional fiscal month & week labels for CB-TI
				// -----------------------------------------------------
				
				Add_FiscalMonthName =
				    Table.AddColumn(
				        Add_IsPreviousWeek,
				        "FiscalMonthName",
				        each "FM" & Text.PadStart(Text.From([FiscalMonth]), 2, "0"),
				        Text.Type
				    ),
				
				Add_FiscalMonthNameLong =
				    Table.AddColumn(
				        Add_FiscalMonthName,
				        "FiscalMonthNameLong",
				        each "FM" & Text.PadStart(Text.From([FiscalMonth]), 2, "0") 
				            & " - " & Date.MonthName([Date]),
				        Text.Type
				    ),
				
				Add_FiscalWeekName =
				    Table.AddColumn(
				        Add_FiscalMonthNameLong,
				        "FiscalWeekName",
				        each "FW" & Text.PadStart(Text.From([FiscalWeekOfYear]), 2, "0"),
				        Text.Type
				    ),
				
				    #"Rename Columns" =
				        Table.TransformColumnNames(
				            Add_FiscalWeekName,
				            each [
				                SplitTextByTransition =
				                    Splitter.SplitTextByCharacterTransition({"a" .. "z"}, {"A" .. "Z"})(_),
				                CombineValues = Text.Combine(SplitTextByTransition, " "),
				                RemoveUnderscores = Text.Replace(CombineValues, "_", " ")
				            ][RemoveUnderscores]
				        ),
				
				    #"Inserted Month Name" =
				        Table.AddColumn(#"Rename Columns", "Month Name", each Date.MonthName([Date]), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Month Name", "MMM Label", each Text.Start([Month Name], 3)),
				    Add_IsCompletedMonth = Table.AddColumn(#"Added Custom", "Is Completed Month", each Date.EndOfMonth([Date])< Date.StartOfMonth(Date.From(DateTime.LocalNow())), type logical),
				    #"Added Custom1" = Table.AddColumn(Add_IsCompletedMonth, "Is Completed Quarter", each [Fiscal End Of Quarter] < Date.From(DateTime.LocalNow()), type logical)
				in
				    #"Added Custom1"
				```

	calendar 'FY Calendar'
		lineageTag: 0eaf2bc4-e1f2-43ec-b2d2-cf31e10df9f2

		calendarColumnGroup = year
			primaryColumn: 'Fiscal Year'
			associatedColumn: 'Fiscal Year Label'

		calendarColumnGroup = quarterOfYear
			primaryColumn: 'Fiscal Quarter'
			associatedColumn: 'Fiscal Quarter Label'

		calendarColumnGroup = monthOfYear
			primaryColumn: 'Fiscal Month'
			associatedColumn: 'Fiscal Month Name'
			associatedColumn: 'Fiscal Month Name Long'

		calendarColumnGroup = weekOfYear
			primaryColumn: 'Fiscal Week Of Year'
			associatedColumn: 'Fiscal Week Name'

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

