/// Service contract revenue aggregated by AgreementKey and Month End for cohort-based retention KPIs (sliceable by contract attributes).
table SC_AgreementMonth_Revenue
	lineageTag: d2d0505b-155c-407f-96f0-a9d9343f6539

	column AgreementKey
		dataType: string
		lineageTag: 3dd5c7af-f64e-4f8e-b22f-b2883d97d4d2
		summarizeBy: none
		sourceColumn: AgreementKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Key'
		dataType: string
		lineageTag: 4f6e68fd-8020-41dc-8c93-67a12cbb9fdf
		summarizeBy: none
		sourceColumn: Customer Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month End'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a82a8bc-a1c9-4f86-9f15-65ecde6d8315
		summarizeBy: none
		sourceColumn: Month End

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SC Revenue'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6ef42731-a6a5-4f4a-9077-3d90102a9f65
		summarizeBy: sum
		sourceColumn: SC Revenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition SC_AgreementMonth_Revenue = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = SERVCONTRACTS_REVENUE_F,
				
				    Typed =
				        Table.TransformColumnTypes(
				            Source,
				            {{"Date", type date}, {"AgreementKey", type text}, {"Amount", Currency.Type}}
				        ),
				
				    AddMonthEnd =
				        Table.AddColumn(
				            Typed,
				            "Month End",
				            each Date.EndOfMonth([Date]),
				            type date
				        ),
				
				    Grouped =
				        Table.Group(
				            AddMonthEnd,
				            {"AgreementKey", "Month End"},
				            {{"SC Revenue", each List.Sum([Amount]), Currency.Type}}
				        ),
				
				    // AgreementKey -> Customer Key lookup from the service contracts dimension
				    KeyMap =
				        Table.Buffer(
				            Table.Distinct(
				                Table.SelectColumns(
				                    SERVCONTRACTS_D,
				                    {"AgreementKey", "Custnmbr Key"}
				                ),
				                {"AgreementKey"}
				            )
				        ),
				
				    Joined =
				        Table.NestedJoin(
				            Grouped,
				            {"AgreementKey"},
				            KeyMap,
				            {"AgreementKey"},
				            "Dim",
				            JoinKind.LeftOuter
				        ),
				
				    Expanded =
				        Table.ExpandTableColumn(
				            Joined,
				            "Dim",
				            {"Custnmbr Key"},
				            {"Customer Key"}
				        ),
				
				    FilterValid =
				        Table.SelectRows(
				            Expanded,
				            each
				                [AgreementKey] <> null
				                    and [AgreementKey] <> ""
				                    and [Customer Key] <> null
				                    and [Customer Key] <> ""
				        ),
				
				    Result =
				        Table.SelectColumns(
				            FilterValid,
				            {"AgreementKey", "Customer Key", "Month End", "SC Revenue"}
				        )
				in
				    Result

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

