table ALL_BILLINGS_F
	lineageTag: d4e72451-5094-4aaa-959f-e95156a8f645

	measure 'Active Customers' = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( CUSTOMERS_D[Customer Key] ),
			    FILTER (
			        VALUES ( CUSTOMERS_D[Customer Key] ),
			        [Is Active Customer] = 1
			    )
			)
			
			```
		lineageTag: 9c8911ef-f874-48a7-9de6-40f87d4afa29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Status – Slicer Filter' = ```
			
			VAR SelectedStatus =
			    SELECTEDVALUE ( 'UI_Customer Status Selector'[Customer Status], "All" )
			
			VAR MonthsInactive =
			    [Months Since Last Billing]
			
			RETURN
			SWITCH (
			    SelectedStatus,
			
			    "Active",
			        IF ( NOT ISBLANK ( MonthsInactive ) && MonthsInactive < 6, 1, 0 ),
			
			    "Dormant (6–11 mo)",
			        IF (
			            NOT ISBLANK ( MonthsInactive )
			                && MonthsInactive >= 6
			                && MonthsInactive < 12,
			            1,
			            0
			        ),
			
			    "Inactive (12+ mo)",
			        IF ( NOT ISBLANK ( MonthsInactive ) && MonthsInactive >= 12, 1, 0 ),
			
			    1
			)
			
			```
		lineageTag: e766eb69-8bd9-4831-8d91-dffd7c3f36a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BillingDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9054ac1-f951-4497-8aa6-c3cf3c52e26c
		summarizeBy: none
		sourceColumn: BillingDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Key'
		dataType: string
		lineageTag: 832452c4-af0d-44eb-a403-10729eefcae4
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

	column 'Billing Stream'
		dataType: string
		lineageTag: 34aee15d-1c20-4617-8c68-bd99e82589f9
		summarizeBy: none
		sourceColumn: Billing Stream

		annotation SummarizationSetBy = Automatic

	column AgreementKey
		dataType: string
		lineageTag: e87e5810-5a99-4837-99f0-1aef9be6b336
		summarizeBy: none
		sourceColumn: AgreementKey

		annotation SummarizationSetBy = Automatic

	column 'Project Key'
		dataType: string
		lineageTag: 95178260-71c3-477e-8f0e-a68453c718b7
		summarizeBy: none
		sourceColumn: Project Key

		annotation SummarizationSetBy = Automatic

	column 'Billing Amount'
		dataType: double
		lineageTag: 5a8d526b-bab0-4747-8101-b7055dd38979
		summarizeBy: sum
		sourceColumn: Billing Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ALL_BILLINGS_F = m
		mode: import
		queryGroup: Staging
		source =
				let
				    //=====================================================================
				    // 0) SOURCE TABLES
				    //=====================================================================
				    ServiceContractRevenue = SERVCONTRACTS_REVENUE_F,
				    ServiceContractsDim    = SERVCONTRACTS_D,
				    ProjectRevenue         = PROJECT_REVENUE_F,
				    SpotRevenue            = SPOT_FINANCIALS_F,
				
				    //=====================================================================
				    // 1) SERVICE CONTRACT BILLINGS
				    //    Enrich revenue rows with Customer Key via SERVCONTRACTS_D
				    //=====================================================================
				
				    // Build a thin AgreementKey → Customer Key lookup
				    SC_KeyMap =
				        Table.Buffer(
				            Table.Distinct(
				                Table.SelectColumns(
				                    ServiceContractsDim,
				                    {"AgreementKey", "Custnmbr Key"}
				                ),
				                {"AgreementKey"}
				            )
				        ),
				
				    // Join revenue to dimension to materialize Customer Key
				    SC_Merged =
				        Table.NestedJoin(
				            ServiceContractRevenue,
				            {"AgreementKey"},
				            SC_KeyMap,
				            {"AgreementKey"},
				            "Dim",
				            JoinKind.LeftOuter
				        ),
				
				    SC_Expanded =
				        Table.ExpandTableColumn(
				            SC_Merged,
				            "Dim",
				            {"Custnmbr Key"},
				            {"Customer Key"}
				        ),
				
				    // Shape to ALL_BILLINGS_F schema
				    SC_Final =
				        Table.SelectColumns(
				            Table.TransformColumnTypes(
				                Table.RenameColumns(
				                    Table.AddColumn(
				                        SC_Expanded,
				                        "Billing Stream",
				                        each "Service Contract",
				                        type text
				                    ),
				                    {{"Date", "BillingDate"}}
				                ),
				                {
				                    {"BillingDate", type date},
				                    {"Customer Key", type text},
				                    {"AgreementKey", type text},
				                    {"Amount", type number},
				                    {"Billing Stream", type text}
				                }
				            ),
				            {"BillingDate", "Customer Key", "Billing Stream", "AgreementKey", "Amount"}
				        ),
				
				    SC_Final_Shaped =
				        Table.RenameColumns(
				            Table.AddColumn(
				                SC_Final,
				                "Project Key",
				                each null,
				                type nullable text
				            ),
				            {{"Amount", "Billing Amount"}}
				        ),
				
				    //=====================================================================
				    // 2) PROJECT BILLINGS
				    //=====================================================================
				
				    Project_Final =
				        Table.SelectColumns(
				            Table.TransformColumnTypes(
				                Table.RenameColumns(
				                    Table.AddColumn(
				                        ProjectRevenue,
				                        "Billing Stream",
				                        each "Project",
				                        type text
				                    ),
				                    {
				                        {"Date", "BillingDate"},
				                        {"SurrogateProjectID", "Project Key"}
				                    }
				                ),
				                {
				                    {"BillingDate", type date},
				                    {"Customer Key", type text},
				                    {"Project Key", type text},
				                    {"Amount", type number},
				                    {"Billing Stream", type text}
				                }
				            ),
				            {"BillingDate", "Customer Key", "Billing Stream", "Project Key", "Amount"}
				        ),
				
				    Project_Final_Shaped =
				        Table.RenameColumns(
				            Table.AddColumn(
				                Project_Final,
				                "AgreementKey",
				                each null,
				                type nullable text
				            ),
				            {{"Amount", "Billing Amount"}}
				        ),
				
				    //=====================================================================
				    // 3) T&M / SPOT BILLINGS
				    //=====================================================================
				
				    TM_Final =
				        Table.SelectColumns(
				            Table.TransformColumnTypes(
				                Table.RenameColumns(
				                    Table.AddColumn(
				                        SpotRevenue,
				                        "Billing Stream",
				                        each "T&M",
				                        type text
				                    ),
				                    {{"Date", "BillingDate"}}
				                ),
				                {
				                    {"BillingDate", type date},
				                    {"Customer Key", type text},
				                    {"Revenue", type number},
				                    {"Billing Stream", type text}
				                }
				            ),
				            {"BillingDate", "Customer Key", "Billing Stream", "Revenue"}
				        ),
				
				    TM_Final_Shaped =
				        Table.RenameColumns(
				            Table.AddColumn(
				                Table.AddColumn(
				                    TM_Final,
				                    "AgreementKey",
				                    each null,
				                    type nullable text
				                ),
				                "Project Key",
				                each null,
				                type nullable text
				            ),
				            {{"Revenue", "Billing Amount"}}
				        ),
				
				    //=====================================================================
				    // 4) APPEND ALL STREAMS
				    //=====================================================================
				
				    Combined =
				        Table.Combine({
				            SC_Final_Shaped,
				            Project_Final_Shaped,
				            TM_Final_Shaped
				        }),
				
				    // Enforce final schema + ordering
				    ALL_BILLINGS_F =
				        Table.SelectColumns(
				            Table.TransformColumnTypes(
				                Combined,
				                {
				                    {"BillingDate", type date},
				                    {"Customer Key", type text},
				                    {"Billing Stream", type text},
				                    {"AgreementKey", type text},
				                    {"Project Key", type text},
				                    {"Billing Amount", type number}
				                }
				            ),
				            {
				                "BillingDate",
				                "Customer Key",
				                "Billing Stream",
				                "AgreementKey",
				                "Project Key",
				                "Billing Amount"
				            }
				        )
				in
				    ALL_BILLINGS_F

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

