createOrReplace

	ref table 'GP Floor'

		measure 'At Or Above Floor' =
				
				VAR gp = [GP %]
				  VAR floor = [GP Floor Value]
				  RETURN
				  IF(
				  ISBLANK(gp) || ISBLANK(floor),
				  BLANK(),
				  IF(gp >= floor, "Yes", "No")
				  )
			lineageTag: 7528d5ff-3172-48bc-bbc0-3535adbdb348

