table GL_ACCT_D
	lineageTag: 429944f9-fc34-41d2-9b67-5ea6c9c5031e

	column ACCTIDX_KEY
		dataType: string
		lineageTag: ad045386-075b-4248-add9-f60d22a8e132
		summarizeBy: none
		sourceColumn: ACCTIDX_KEY

		annotation SummarizationSetBy = Automatic

	column SOURCE
		dataType: string
		lineageTag: b73aa290-7882-4c7c-9d90-efe84867a9d6
		summarizeBy: none
		sourceColumn: SOURCE

		annotation SummarizationSetBy = Automatic

	column ACTNUMBR_1
		dataType: string
		lineageTag: ed19e6b1-5cf8-420f-8feb-0ab691b4e582
		summarizeBy: none
		sourceColumn: ACTNUMBR_1

		annotation SummarizationSetBy = Automatic

	column ACTNUMBR_2
		dataType: string
		lineageTag: f90eef8d-9b11-4036-a4b6-cbca473e8145
		summarizeBy: none
		sourceColumn: ACTNUMBR_2

		annotation SummarizationSetBy = Automatic

	column ACTNUMBR_3
		dataType: string
		lineageTag: 82e5b408-0400-4ac0-8f33-0a39945e1aef
		summarizeBy: none
		sourceColumn: ACTNUMBR_3

		annotation SummarizationSetBy = Automatic

	column ACTNUMST
		dataType: string
		lineageTag: 643c9982-4351-4903-9794-f45354e45fe8
		summarizeBy: none
		sourceColumn: ACTNUMST

		annotation SummarizationSetBy = Automatic

	column ACTNUMBR_1_RANGE
		dataType: int64
		formatString: 0
		lineageTag: 408e1013-4a52-4842-b972-d9007ffd6bd9
		summarizeBy: sum
		sourceColumn: ACTNUMBR_1_RANGE

		annotation SummarizationSetBy = Automatic

	column NUMBR1_xx_NUMBR3
		dataType: string
		lineageTag: 098f926b-a706-43e1-b9d4-d099da5a70ba
		summarizeBy: none
		sourceColumn: NUMBR1_xx_NUMBR3

		annotation SummarizationSetBy = Automatic

	column REGION
		dataType: string
		lineageTag: 5787193c-83e0-4f2b-b029-db61b6805b67
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column ACCOUNT_TYPE
		dataType: string
		lineageTag: 506b42af-e3f0-4a5d-bc24-2412b7b773c0
		summarizeBy: none
		sourceColumn: ACCOUNT_TYPE

		annotation SummarizationSetBy = Automatic

	column COSTOFSALES_SUBCATEGORY
		dataType: string
		lineageTag: bc973961-795f-4958-9edb-afde887d97f2
		summarizeBy: none
		sourceColumn: COSTOFSALES_SUBCATEGORY

		annotation SummarizationSetBy = Automatic

	column MARKET
		dataType: string
		lineageTag: 48308bcc-7aac-4c6d-850b-57fb52ed2c19
		summarizeBy: none
		sourceColumn: MARKET

		annotation SummarizationSetBy = Automatic

	column ACTDESCR
		dataType: string
		lineageTag: c57aa127-b5dc-4781-8ba7-c59789716f6a
		summarizeBy: none
		sourceColumn: ACTDESCR

		annotation SummarizationSetBy = Automatic

	partition GL_ACCT_D = m
		mode: import
		queryGroup: DIM
		source = ```
				let
				  Source = Snowflake.Databases("ufwarhx-qo50284.snowflakecomputing.com", "COMPUTE_WH", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),
				  #"Navigation 1" = Source{[Name = "DATA_WAREHOUSE", Kind = "Database"]}[Data],
				  #"Navigation 2" = #"Navigation 1"{[Name = "DW_CLEAN", Kind = "Schema"]}[Data],
				  #"Navigation 3" = #"Navigation 2"{[Name = "GL_ACCT", Kind = "View"]}[Data],
				  #"Removed Other Columns" = Table.SelectColumns(#"Navigation 3", {"ACTNUMBR_1", "ACTNUMBR_2", "ACTNUMBR_3", "ACTNUMST", "ACCTTYPE", "ACTDESCR", "DIVISION", "CATEGORY", "SOURCE", "ACCTIDX_KEY"}),
				  #"Added ACTNUMBR1_RANGE" = Table.TransformColumnTypes(Table.AddColumn(#"Removed Other Columns", "ACTNUMBR_1_RANGE", each Number.RoundDown(Number.FromText([ACTNUMBR_1])/100)*100), {{"ACTNUMBR_1_RANGE", Int64.Type}}),
				  #"Added custom 1" = Table.AddColumn(#"Added ACTNUMBR1_RANGE", "NUMBR1_xx_NUMBR3", each Text.From([ACTNUMBR_1]) & "-xx-" & [ACTNUMBR_3]),
				  AddRegion = Table.AddColumn(#"Added custom 1", "REGION", each let value = Text.Trim([ACTNUMBR_2])
				      in
				        if [SOURCE] = "SERV_GP" then
				          if List.Contains({"20", "27"}, value) then "KNOXVILLE" else
				          if List.Contains({"00", "07"}, value) then "CINCINNATI" else
				          if List.Contains({"10", "17"}, value) then "LEXINGTON" else
				          if List.Contains({"90"}, value) then "LOUISVILLE" else
				          if List.Contains({"60", "67"}, value) then "NASHVILLE" else
				          if List.Contains({"30", "37"}, value) then "INDIANAPOLIS" else
				          if List.Contains({"40", "47"}, value) then "WEST VIRGINIA" else
				          if List.Contains({"70", "77"}, value) then "TFS" else
				          if List.Contains({"80", "81", "87", "85"}, value) then "DAYTON" else
				          "Missing Division" 
				        else if [SOURCE] = "MECH_GP" then
				          if List.Contains({"00", "01", "02", "04", "05"}, value) then "DESIGN BUILD" else
				          if List.Contains({"03", "09", "40"}, value) then "GREEN" else
				          if List.Contains({"20", "21"}, value) then "LEOPARDO" else
				          "Missing Division"
				        else "BROKEN"),
				  AddAccountType = Table.AddColumn(AddRegion, "ACCOUNT_TYPE", each let 
				      value = [ACTNUMBR_1_RANGE],
				      subcat = Text.Trim([ACTNUMBR_1])
				  in
				      if value = 500 then "OPERATIONS EXPENSE" else
				      if value = 600 then "SALES EXPENSE" else
				      if value = 700 then "G&A EXPENSE" else
				      if value = 800 then "OTHER INCOME & EXPENSE" else
				      if value = 300 then 
				          if List.Contains({"330", "331", "332"}, Text.From(subcat)) then "REVENUE" else
				          "COST OF SALES" 
				      else "BROKEN"),
				  AddSubcategory = Table.AddColumn(AddAccountType, "COSTOFSALES_SUBCATEGORY", each let
				    category = [ACCOUNT_TYPE],
				    act3 = Text.Trim([ACTNUMBR_3]),
				    lastDigit = Text.End(act3, 1)
				  in
				    if category = "COST OF SALES" then
				      if lastDigit = "2" then "EQUIPMENT & MATERIAL" else
				      if lastDigit = "3" then "LABOR" else
				      if lastDigit = "9" then "BURDEN" else
				      if lastDigit = "7" then "SUBCONTRACT" else
				      if lastDigit = "0" then "DISCOUNTS" else
				      if lastDigit = "6" then "VEHICLE EXPENSE" else
				      if lastDigit = "8" then "TAX EXPENSE" else
				      null
				    else
				      null),
				  AddSubCategory2 = Table.AddColumn(AddSubcategory, "MARKET", each let
				        source = Text.Trim([SOURCE]),
				        act3 = Text.Trim([ACTNUMBR_3]),
				        act2 = Text.Trim([ACTNUMBR_2]),
				        act1 = Text.Trim([ACTNUMBR_1]),
				        firstDigitAct3 = Text.Start(act3, 1),
				        firstDigitAct1 = Text.Start(act1, 1),
				        lastDigitAct2 = Text.End(act2, 1),
				        lastDigitAct1 = Text.End(act1, 1)
				    in
				        if source = "SERV_GP" then
				            if firstDigitAct1 = "3" then
				                if firstDigitAct3 = "4" then "CERTIFIED" else
				                if firstDigitAct3 = "7" then "INSPECTION" else
				                if firstDigitAct3 = "6" then
				                    if lastDigitAct1 = "5" or lastDigitAct2 = "5" then "INTERCOMPANY SPOT" else 
				                    if lastDigitAct2 = "7" then "O&M SPOT" else "SPOT" else
				                if firstDigitAct3 = "8" then "PROJECT REPAIR" else
				                if firstDigitAct3 = "3" then
				                    if lastDigitAct2 = "7" then "O&M" else "ASSURED"
				                else if firstDigitAct3 = "5" then
				                    if lastDigitAct2 = "7" then "O&M PROJECTS" else "PROJECTS"
				                else null
				            else
				                if firstDigitAct3 = "3" then
				                    if lastDigitAct2 = "7" then "O&M" else "A"
				                else if firstDigitAct3 = "5" then
				                    if lastDigitAct2 = "7" then "O&M PROJECTS" else "PROJECTS"
				                else null
				        else
				        if source = "MECH_GP" then
				            if firstDigitAct1 = "3" then
				                if lastDigitAct2 = "0" then "CONTROLS" else
				                if lastDigitAct2 = "1" then "DESIGN BUILD" else
				                if lastDigitAct2 = "2" then "INDUSTRIAL" else
				                if lastDigitAct2 = "3" then "PERFORMANCE CONTRACT" else 
				                if lastDigitAct2 = "4" then "PLAN SPEC" else
				                if lastDigitAct2 = "5" then "SPECIAL PROJECT" else      
				                null
				            else null
				        else null),
				  #"Removed other columns 1" = Table.SelectColumns(AddSubCategory2, {"ACTNUMBR_1", "ACTNUMBR_2", "ACTNUMBR_3", "ACTNUMST", "ACTDESCR", "SOURCE", "ACCTIDX_KEY", "ACTNUMBR_1_RANGE", "NUMBR1_xx_NUMBR3", "REGION", "ACCOUNT_TYPE", "COSTOFSALES_SUBCATEGORY", "MARKET"}),
				  #"Reordered columns" = Table.ReorderColumns(#"Removed other columns 1", {"ACCTIDX_KEY", "SOURCE", "ACTNUMBR_1", "ACTNUMBR_2", "ACTNUMBR_3", "ACTNUMST", "ACTNUMBR_1_RANGE", "NUMBR1_xx_NUMBR3", "REGION", "ACCOUNT_TYPE", "COSTOFSALES_SUBCATEGORY", "MARKET", "ACTDESCR"}),
				  #"Transform columns" = Table.TransformColumnTypes(#"Reordered columns", {{"NUMBR1_xx_NUMBR3", type text}, {"REGION", type text}, {"ACCOUNT_TYPE", type text}, {"COSTOFSALES_SUBCATEGORY", type text}, {"MARKET", type text}}),
				  #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"NUMBR1_xx_NUMBR3", null}, {"REGION", null}, {"ACCOUNT_TYPE", null}, {"COSTOFSALES_SUBCATEGORY", null}, {"MARKET", null}})
				 in
				  #"Replace errors"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

