table JOB_CHANGE_ORDERS_F
	isHidden
	lineageTag: 9ed1c1c8-a639-4837-99e9-d16fe3418e48

	column 'Job Number'
		dataType: string
		lineageTag: 18a3f9a4-8d46-431a-af51-fc01e59d8d3b
		summarizeBy: none
		sourceColumn: Job Number

		annotation SummarizationSetBy = Automatic

	column 'Change Order Number'
		dataType: string
		lineageTag: be2f19f4-f287-4ac4-9928-c426a4398977
		summarizeBy: none
		sourceColumn: Change Order Number

		annotation SummarizationSetBy = Automatic

	column 'Firscal Year'
		dataType: double
		lineageTag: 9a51bd5c-4cd2-4dc1-a69f-42742f77175f
		summarizeBy: sum
		sourceColumn: Firscal Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Month'
		dataType: double
		lineageTag: 3535e258-2584-4d20-98a7-b6d2fd2c45c7
		summarizeBy: sum
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Change Order Est Cost'
		dataType: double
		lineageTag: 58d59cc2-60e4-4a3c-8786-c27abb2a9657
		summarizeBy: sum
		sourceColumn: Change Order Est Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Source
		dataType: string
		lineageTag: 5f83fb54-0854-4e4c-8ae5-83b42b111a97
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column Rn
		dataType: double
		lineageTag: f400f24c-fe4a-4849-9377-2b32abf06d0c
		summarizeBy: sum
		sourceColumn: Rn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Job Key'
		dataType: string
		lineageTag: 798f999d-93bf-4e45-b1d3-d0a1fcebc4b4
		summarizeBy: none
		sourceColumn: Job Key

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 222a1ba4-f6d9-4791-a4f9-7c934e0220e2
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition JOB_CHANGE_ORDERS_F = m
		mode: import
		source =
				let
				     Source = Snowflake.Databases("ws53155.central-us.azure.snowflakecomputing.com","COMPUTE_WH"),
				    DATA_WAREHOUSE_Database = Source{[Name="DATA_WAREHOUSE",Kind="Database"]}[Data],
				    DW_CLEAN_Schema = DATA_WAREHOUSE_Database{[Name="DW_CLEAN",Kind="Schema"]}[Data],
				    JOB_CHANGE_ORDERS_View = DW_CLEAN_Schema{[Name="JOB_CHANGE_ORDERS",Kind="View"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(JOB_CHANGE_ORDERS_View),
				    ProperCase = Table.RenameColumns(#"Removed Duplicates", List.Transform(Table.ColumnNames(#"Removed Duplicates"), each {_, Text.Proper(Text.Replace(_, "_", " "))})),
				    CalcDate = Table.AddColumn(ProperCase, "Date", each Date.AddMonths(#date(Number.From([Firscal Year]), Number.From([Fiscal Month]), 1), -3), type date)
				in
				    CalcDate

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

